const en = {
  "admin.projects.confirm_delete": "Are you sure you want to delete this project?",
  "admin.projects.create_first": "Create Project", "admin.projects.empty_desc": "Create a project to connect portfolio items with registered clients.", "admin.projects.empty_title": "No projects found",
  "admin.projects.new_project": "New Project", "admin.projects.no_client_assigned": "No client assigned", "admin.projects.no_portfolio_linked": "No portfolio items linked",
  "admin.projects.no_projects_found": "No projects found matching your search criteria.", "admin.projects.search_placeholder": "Search projects...",
  "admin.projects.status_active": "Active", "admin.projects.status_all": "All statuses", "admin.projects.status_archived": "Archived", "admin.projects.status_completed": "Completed",
  "admin.projects.status_filter_label": "Status:", "admin.projects.th_actions": "Actions", "admin.projects.th_client": "Client", "admin.projects.th_linked_portfolios": "Linked portfolios",
  "admin.projects.th_portfolio": "Linked portfolio", "admin.projects.th_project": "Project", "admin.projects.th_status": "Status", "admin.projects.title": "Projects", "admin.projects.unassigned": "Unassigned",
  "admin.projects.timeline_action": "Milestones and project updates", "admin.projects.untitled": "Untitled", "admin.projects.save_failed": "Failed to save project."
};

export const adminProjectsTranslations: Record<string, Record<string, string>> = {
  en,
  hu: { ...en,
    "admin.projects.confirm_delete": "Biztosan törölni szeretné ezt a projektet?", "admin.projects.create_first": "Projekt létrehozása", "admin.projects.empty_desc": "Hozzon létre projektet a portfólióelemek és a regisztrált ügyfelek összekapcsolásához.", "admin.projects.empty_title": "Nem található projekt",
    "admin.projects.new_project": "Új projekt", "admin.projects.no_client_assigned": "Nincs hozzárendelt ügyfél", "admin.projects.no_portfolio_linked": "Nincs kapcsolt portfólióelem", "admin.projects.no_projects_found": "Nem található a keresési feltételeknek megfelelő projekt.", "admin.projects.search_placeholder": "Projektek keresése...",
    "admin.projects.status_active": "Aktív", "admin.projects.status_all": "Minden állapot", "admin.projects.status_archived": "Archivált", "admin.projects.status_completed": "Befejezett", "admin.projects.status_filter_label": "Állapot:", "admin.projects.th_actions": "Műveletek", "admin.projects.th_client": "Ügyfél", "admin.projects.th_linked_portfolios": "Kapcsolt portfóliók", "admin.projects.th_portfolio": "Kapcsolt portfólió", "admin.projects.th_project": "Projekt", "admin.projects.th_status": "Állapot", "admin.projects.title": "Projektek", "admin.projects.unassigned": "Nincs hozzárendelve", "admin.projects.timeline_action": "Mérföldkövek és projektfrissítések", "admin.projects.untitled": "Névtelen", "admin.projects.save_failed": "A projekt mentése sikertelen."
  },
  de: { ...en,
    "admin.projects.confirm_delete": "Möchten Sie dieses Projekt wirklich löschen?", "admin.projects.create_first": "Projekt erstellen", "admin.projects.empty_desc": "Erstellen Sie ein Projekt, um Portfolioelemente mit registrierten Kunden zu verknüpfen.", "admin.projects.empty_title": "Keine Projekte gefunden", "admin.projects.new_project": "Neues Projekt", "admin.projects.no_client_assigned": "Kein Kunde zugewiesen", "admin.projects.no_portfolio_linked": "Keine Portfolioelemente verknüpft", "admin.projects.no_projects_found": "Keine Projekte entsprechen Ihren Suchkriterien.", "admin.projects.search_placeholder": "Projekte durchsuchen...", "admin.projects.status_active": "Aktiv", "admin.projects.status_all": "Alle Status", "admin.projects.status_archived": "Archiviert", "admin.projects.status_completed": "Abgeschlossen", "admin.projects.status_filter_label": "Status:", "admin.projects.th_actions": "Aktionen", "admin.projects.th_client": "Kunde", "admin.projects.th_linked_portfolios": "Verknüpfte Portfolios", "admin.projects.th_portfolio": "Verknüpftes Portfolio", "admin.projects.th_project": "Projekt", "admin.projects.th_status": "Status", "admin.projects.title": "Projekte", "admin.projects.unassigned": "Nicht zugewiesen", "admin.projects.timeline_action": "Meilensteine und Projektaktualisierungen", "admin.projects.untitled": "Ohne Titel", "admin.projects.save_failed": "Projekt konnte nicht gespeichert werden."
  },
  es: { ...en,
    "admin.projects.confirm_delete": "¿Seguro que desea eliminar este proyecto?", "admin.projects.create_first": "Crear proyecto", "admin.projects.empty_desc": "Cree un proyecto para vincular elementos del portafolio con clientes registrados.", "admin.projects.empty_title": "No se encontraron proyectos", "admin.projects.new_project": "Nuevo proyecto", "admin.projects.no_client_assigned": "Sin cliente asignado", "admin.projects.no_portfolio_linked": "No hay elementos del portafolio vinculados", "admin.projects.no_projects_found": "No se encontraron proyectos que coincidan con sus criterios de búsqueda.", "admin.projects.search_placeholder": "Buscar proyectos...", "admin.projects.status_active": "Activo", "admin.projects.status_all": "Todos los estados", "admin.projects.status_archived": "Archivado", "admin.projects.status_completed": "Completado", "admin.projects.status_filter_label": "Estado:", "admin.projects.th_actions": "Acciones", "admin.projects.th_client": "Cliente", "admin.projects.th_linked_portfolios": "Portafolios vinculados", "admin.projects.th_portfolio": "Portafolio vinculado", "admin.projects.th_project": "Proyecto", "admin.projects.th_status": "Estado", "admin.projects.title": "Proyectos", "admin.projects.unassigned": "Sin asignar", "admin.projects.timeline_action": "Hitos y actualizaciones del proyecto", "admin.projects.untitled": "Sin título", "admin.projects.save_failed": "No se pudo guardar el proyecto."
  },
  fr: { ...en,
    "admin.projects.confirm_delete": "Voulez-vous vraiment supprimer ce projet ?", "admin.projects.create_first": "Créer un projet", "admin.projects.empty_desc": "Créez un projet pour associer des éléments du portfolio aux clients inscrits.", "admin.projects.empty_title": "Aucun projet trouvé", "admin.projects.new_project": "Nouveau projet", "admin.projects.no_client_assigned": "Aucun client attribué", "admin.projects.no_portfolio_linked": "Aucun élément de portfolio lié", "admin.projects.no_projects_found": "Aucun projet ne correspond à vos critères de recherche.", "admin.projects.search_placeholder": "Rechercher des projets...", "admin.projects.status_active": "Actif", "admin.projects.status_all": "Tous les statuts", "admin.projects.status_archived": "Archivé", "admin.projects.status_completed": "Terminé", "admin.projects.status_filter_label": "Statut :", "admin.projects.th_actions": "Actions", "admin.projects.th_client": "Client", "admin.projects.th_linked_portfolios": "Portfolios liés", "admin.projects.th_portfolio": "Portfolio lié", "admin.projects.th_project": "Projet", "admin.projects.th_status": "Statut", "admin.projects.title": "Projets", "admin.projects.unassigned": "Non attribué", "admin.projects.timeline_action": "Jalons et mises à jour du projet", "admin.projects.untitled": "Sans titre", "admin.projects.save_failed": "Impossible d’enregistrer le projet."
  }
};
