export const adminReferralsOverviewTranslations: Record<string, Record<string,string>> = {
en:{
"admin.referrals.page.loading_referral_management":"Loading referral management...","admin.referrals.page.vip_tiered_referral_program":"VIP tiered referral program","admin.referrals.page.manage_vip_membership_tiers_automate_referral_rewards_":"Manage VIP tiers, automate rewards, track invitation networks and issue credits.","admin.referrals.page.add_new_tier":"Add new tier","admin.referrals.page.total_referrals_logged":"Total referrals logged","admin.referrals.page.pending_first_shoot":"pending first shoot","admin.referrals.page.successful_conversions":"Successful conversions","admin.referrals.page.referred_revenue":"Referred revenue","admin.referrals.page.from_converted_client_bookings":"From converted client bookings","admin.referrals.page.rewards_credits_issued":"Rewards and credits issued","admin.referrals.page.active_vip_advocates":"active VIP advocates","admin.referrals.page.overview_top_referrers":"Overview and top referrers","admin.referrals.page.referrals_log":"Referrals log (","admin.referrals.page.vip_tiers":"VIP tiers (","admin.referrals.page.issued_rewards_vouchers":"Issued rewards and vouchers (","admin.referrals.page.program_settings":"Program settings","admin.referrals.page.top_client_advocates_leaderboard":"Top client advocates","admin.referrals.page.clients_who_generate_the_highest_volume_of_referral_bo":"Clients generating the most referral bookings and revenue.","admin.referrals.page.no_converted_referrals_yet":"No converted referrals yet."},
hu:{
"admin.referrals.page.loading_referral_management":"Ajánláskezelés betöltése...","admin.referrals.page.vip_tiered_referral_program":"VIP szintű ajánlási program","admin.referrals.page.manage_vip_membership_tiers_automate_referral_rewards_":"VIP-szintek, automatikus jutalmak, meghívási hálózatok és jóváírások kezelése.","admin.referrals.page.add_new_tier":"Új szint hozzáadása","admin.referrals.page.total_referrals_logged":"Rögzített ajánlások összesen","admin.referrals.page.pending_first_shoot":"első fotózásra vár","admin.referrals.page.successful_conversions":"Sikeres konverziók","admin.referrals.page.referred_revenue":"Ajánlásokból származó bevétel","admin.referrals.page.from_converted_client_bookings":"Konvertált ügyfelek foglalásaiból","admin.referrals.page.rewards_credits_issued":"Kiadott jutalmak és jóváírások","admin.referrals.page.active_vip_advocates":"aktív VIP ajánló","admin.referrals.page.overview_top_referrers":"Áttekintés és legjobb ajánlók","admin.referrals.page.referrals_log":"Ajánlási napló (","admin.referrals.page.vip_tiers":"VIP-szintek (","admin.referrals.page.issued_rewards_vouchers":"Kiadott jutalmak és utalványok (","admin.referrals.page.program_settings":"Programbeállítások","admin.referrals.page.top_client_advocates_leaderboard":"Legjobb ügyfélajánlók","admin.referrals.page.clients_who_generate_the_highest_volume_of_referral_bo":"A legtöbb ajánlási foglalást és bevételt hozó ügyfelek.","admin.referrals.page.no_converted_referrals_yet":"Még nincs konvertált ajánlás."},
de:{
"admin.referrals.page.loading_referral_management":"Empfehlungsverwaltung wird geladen...","admin.referrals.page.vip_tiered_referral_program":"VIP-Empfehlungsprogramm mit Stufen","admin.referrals.page.manage_vip_membership_tiers_automate_referral_rewards_":"VIP-Stufen, automatische Prämien, Einladungsnetzwerke und Gutschriften verwalten.","admin.referrals.page.add_new_tier":"Neue Stufe hinzufügen","admin.referrals.page.total_referrals_logged":"Erfasste Empfehlungen insgesamt","admin.referrals.page.pending_first_shoot":"wartet auf erstes Shooting","admin.referrals.page.successful_conversions":"Erfolgreiche Konvertierungen","admin.referrals.page.referred_revenue":"Empfehlungsumsatz","admin.referrals.page.from_converted_client_bookings":"Aus Buchungen konvertierter Kunden","admin.referrals.page.rewards_credits_issued":"Ausgestellte Prämien und Gutschriften","admin.referrals.page.active_vip_advocates":"aktive VIP-Empfehler","admin.referrals.page.overview_top_referrers":"Übersicht und beste Empfehler","admin.referrals.page.referrals_log":"Empfehlungsprotokoll (","admin.referrals.page.vip_tiers":"VIP-Stufen (","admin.referrals.page.issued_rewards_vouchers":"Ausgestellte Prämien und Gutscheine (","admin.referrals.page.program_settings":"Programmeinstellungen","admin.referrals.page.top_client_advocates_leaderboard":"Beste Kundenempfehler","admin.referrals.page.clients_who_generate_the_highest_volume_of_referral_bo":"Kunden mit den meisten Empfehlungsbuchungen und Umsätzen.","admin.referrals.page.no_converted_referrals_yet":"Noch keine konvertierten Empfehlungen."},
es:{
"admin.referrals.page.loading_referral_management":"Cargando la gestión de recomendaciones...","admin.referrals.page.vip_tiered_referral_program":"Programa VIP de recomendaciones por niveles","admin.referrals.page.manage_vip_membership_tiers_automate_referral_rewards_":"Gestiona niveles VIP, recompensas automáticas, redes de invitaciones y créditos.","admin.referrals.page.add_new_tier":"Añadir nivel","admin.referrals.page.total_referrals_logged":"Recomendaciones registradas","admin.referrals.page.pending_first_shoot":"pendiente de la primera sesión","admin.referrals.page.successful_conversions":"Conversiones correctas","admin.referrals.page.referred_revenue":"Ingresos por recomendaciones","admin.referrals.page.from_converted_client_bookings":"De reservas de clientes convertidos","admin.referrals.page.rewards_credits_issued":"Recompensas y créditos emitidos","admin.referrals.page.active_vip_advocates":"promotores VIP activos","admin.referrals.page.overview_top_referrers":"Resumen y mejores promotores","admin.referrals.page.referrals_log":"Registro de recomendaciones (","admin.referrals.page.vip_tiers":"Niveles VIP (","admin.referrals.page.issued_rewards_vouchers":"Recompensas y cupones emitidos (","admin.referrals.page.program_settings":"Configuración del programa","admin.referrals.page.top_client_advocates_leaderboard":"Mejores promotores clientes","admin.referrals.page.clients_who_generate_the_highest_volume_of_referral_bo":"Clientes que generan más reservas e ingresos por recomendaciones.","admin.referrals.page.no_converted_referrals_yet":"Aún no hay recomendaciones convertidas."},
fr:{
"admin.referrals.page.loading_referral_management":"Chargement de la gestion des recommandations...","admin.referrals.page.vip_tiered_referral_program":"Programme VIP de parrainage par niveaux","admin.referrals.page.manage_vip_membership_tiers_automate_referral_rewards_":"Gérez les niveaux VIP, les récompenses automatiques, les réseaux d’invitations et les crédits.","admin.referrals.page.add_new_tier":"Ajouter un niveau","admin.referrals.page.total_referrals_logged":"Recommandations enregistrées","admin.referrals.page.pending_first_shoot":"en attente de la première séance","admin.referrals.page.successful_conversions":"Conversions réussies","admin.referrals.page.referred_revenue":"Revenus issus des recommandations","admin.referrals.page.from_converted_client_bookings":"Des réservations de clients convertis","admin.referrals.page.rewards_credits_issued":"Récompenses et crédits émis","admin.referrals.page.active_vip_advocates":"ambassadeurs VIP actifs","admin.referrals.page.overview_top_referrers":"Aperçu et meilleurs parrains","admin.referrals.page.referrals_log":"Journal des recommandations (","admin.referrals.page.vip_tiers":"Niveaux VIP (","admin.referrals.page.issued_rewards_vouchers":"Récompenses et bons émis (","admin.referrals.page.program_settings":"Paramètres du programme","admin.referrals.page.top_client_advocates_leaderboard":"Meilleurs clients ambassadeurs","admin.referrals.page.clients_who_generate_the_highest_volume_of_referral_bo":"Clients générant le plus de réservations et de revenus par recommandation.","admin.referrals.page.no_converted_referrals_yet":"Aucune recommandation convertie pour le moment."}
};

Object.assign(adminReferralsOverviewTranslations.en, { "admin.referrals.page.conversion_rate": "{rate}% conversion rate" });
Object.assign(adminReferralsOverviewTranslations.hu, { "admin.referrals.page.conversion_rate": "{rate}% konverziós arány" });
Object.assign(adminReferralsOverviewTranslations.de, { "admin.referrals.page.conversion_rate": "{rate}% Konversionsrate" });
Object.assign(adminReferralsOverviewTranslations.es, { "admin.referrals.page.conversion_rate": "{rate}% de conversión" });
Object.assign(adminReferralsOverviewTranslations.fr, { "admin.referrals.page.conversion_rate": "Taux de conversion : {rate} %" });
