const en = {
  "admin.portfolio.gallery.all_items": "All items ({count})", "admin.portfolio.gallery.photos": "Photos / images (Row 1) ({count})", "admin.portfolio.gallery.drone_videos": "Drone videos (Row 2) ({count})", "admin.portfolio.gallery.interior_videos": "Interior walkthroughs (Row 3) ({count})", "admin.portfolio.gallery.drone_photos": "Drone photos (Row 4) ({count})", "admin.portfolio.gallery.search_items": "Search by title, keywords or description...", "admin.portfolio.gallery.all_categories": "All item categories", "admin.portfolio.gallery.photos_filter": "Photos / images (Row 1)", "admin.portfolio.gallery.drone_videos_filter": "Drone aerial videos (Row 2)", "admin.portfolio.gallery.interior_videos_filter": "Interior walkthroughs (Row 3)", "admin.portfolio.gallery.drone_photos_filter": "Drone photos (Row 4)", "admin.portfolio.gallery.all_videos": "All video items", "admin.portfolio.gallery.mixed": "Mixed galleries", "admin.portfolio.gallery.all_status": "All statuses", "common.published": "Published", "admin.portfolio.gallery.draft_hidden": "Draft (hidden)", "admin.portfolio.gallery.bulk": "Bulk:", "common.publish": "Publish", "admin.portfolio.gallery.draft": "Draft", "admin.portfolio.gallery.no_portfolio_items": "No portfolio items found", "admin.portfolio.gallery.select_all_count": "Select All ({count})", "admin.portfolio.gallery.selected_count": "{count} Selected", "admin.portfolio.gallery.empty_add_hint": "Click 'Add Portfolio Item' above to upload photography, video walkthroughs, or YouTube/Vimeo embeds.", "admin.portfolio.gallery.empty_filter_hint": "No portfolio items matched your current search filters."
};

export const adminPortfolioGalleryTranslations = {
  en,
  hu: { ...en,
    "admin.portfolio.gallery.all_items": "Összes elem ({count})", "admin.portfolio.gallery.photos": "Fotók / képek (1. sor) ({count})", "admin.portfolio.gallery.drone_videos": "Drónvideók (2. sor) ({count})", "admin.portfolio.gallery.interior_videos": "Beltéri bejárások (3. sor) ({count})", "admin.portfolio.gallery.drone_photos": "Drónfotók (4. sor) ({count})", "admin.portfolio.gallery.search_items": "Keresés cím, kulcsszó vagy leírás alapján...", "admin.portfolio.gallery.all_categories": "Minden elemtípus", "admin.portfolio.gallery.photos_filter": "Fotók / képek (1. sor)", "admin.portfolio.gallery.drone_videos_filter": "Légi drónvideók (2. sor)", "admin.portfolio.gallery.interior_videos_filter": "Beltéri bejárások (3. sor)", "admin.portfolio.gallery.drone_photos_filter": "Drónfotók (4. sor)", "admin.portfolio.gallery.all_videos": "Minden videó", "admin.portfolio.gallery.mixed": "Vegyes galériák", "admin.portfolio.gallery.all_status": "Minden állapot", "common.published": "Közzétéve", "admin.portfolio.gallery.draft_hidden": "Piszkozat (rejtett)", "admin.portfolio.gallery.bulk": "Tömeges művelet:", "common.publish": "Közzététel", "admin.portfolio.gallery.draft": "Piszkozat", "admin.portfolio.gallery.no_portfolio_items": "Nem található portfólióelem", "admin.portfolio.gallery.select_all_count": "Összes kijelölése ({count})", "admin.portfolio.gallery.selected_count": "{count} kijelölve", "admin.portfolio.gallery.empty_add_hint": "Fotók, videós bejárások vagy YouTube/Vimeo-beágyazások feltöltéséhez kattints fent a „Portfólióelem hozzáadása” gombra.", "admin.portfolio.gallery.empty_filter_hint": "Egyetlen portfólióelem sem felel meg a jelenlegi keresési szűrőknek."
  },
  de: { ...en,
    "admin.portfolio.gallery.all_items": "Alle Elemente ({count})", "admin.portfolio.gallery.photos": "Fotos / Bilder (Zeile 1) ({count})", "admin.portfolio.gallery.drone_videos": "Drohnenvideos (Zeile 2) ({count})", "admin.portfolio.gallery.interior_videos": "Innenrundgänge (Zeile 3) ({count})", "admin.portfolio.gallery.drone_photos": "Drohnenfotos (Zeile 4) ({count})", "admin.portfolio.gallery.search_items": "Nach Titel, Stichwort oder Beschreibung suchen...", "admin.portfolio.gallery.all_categories": "Alle Elementkategorien", "admin.portfolio.gallery.photos_filter": "Fotos / Bilder (Zeile 1)", "admin.portfolio.gallery.drone_videos_filter": "Drohnen-Luftvideos (Zeile 2)", "admin.portfolio.gallery.interior_videos_filter": "Innenrundgänge (Zeile 3)", "admin.portfolio.gallery.drone_photos_filter": "Drohnenfotos (Zeile 4)", "admin.portfolio.gallery.all_videos": "Alle Videoelemente", "admin.portfolio.gallery.mixed": "Gemischte Galerien", "admin.portfolio.gallery.all_status": "Alle Statuswerte", "common.published": "Veröffentlicht", "admin.portfolio.gallery.draft_hidden": "Entwurf (ausgeblendet)", "admin.portfolio.gallery.bulk": "Mehrfachaktion:", "common.publish": "Veröffentlichen", "admin.portfolio.gallery.draft": "Entwurf", "admin.portfolio.gallery.no_portfolio_items": "Keine Portfolioelemente gefunden", "admin.portfolio.gallery.select_all_count": "Alle auswählen ({count})", "admin.portfolio.gallery.selected_count": "{count} ausgewählt", "admin.portfolio.gallery.empty_add_hint": "Klicken Sie oben auf „Portfolioelement hinzufügen“, um Fotos, Videorundgänge oder YouTube-/Vimeo-Einbettungen hinzuzufügen.", "admin.portfolio.gallery.empty_filter_hint": "Keine Portfolioelemente entsprechen den aktuellen Suchfiltern."
  },
  es: { ...en,
    "admin.portfolio.gallery.all_items": "Todos los elementos ({count})", "admin.portfolio.gallery.photos": "Fotos / imágenes (fila 1) ({count})", "admin.portfolio.gallery.drone_videos": "Vídeos de dron (fila 2) ({count})", "admin.portfolio.gallery.interior_videos": "Recorridos interiores (fila 3) ({count})", "admin.portfolio.gallery.drone_photos": "Fotos de dron (fila 4) ({count})", "admin.portfolio.gallery.search_items": "Buscar por título, palabra clave o descripción...", "admin.portfolio.gallery.all_categories": "Todas las categorías", "admin.portfolio.gallery.photos_filter": "Fotos / imágenes (fila 1)", "admin.portfolio.gallery.drone_videos_filter": "Vídeos aéreos de dron (fila 2)", "admin.portfolio.gallery.interior_videos_filter": "Recorridos interiores (fila 3)", "admin.portfolio.gallery.drone_photos_filter": "Fotos de dron (fila 4)", "admin.portfolio.gallery.all_videos": "Todos los vídeos", "admin.portfolio.gallery.mixed": "Galerías mixtas", "admin.portfolio.gallery.all_status": "Todos los estados", "common.published": "Publicado", "admin.portfolio.gallery.draft_hidden": "Borrador (oculto)", "admin.portfolio.gallery.bulk": "Acción masiva:", "common.publish": "Publicar", "admin.portfolio.gallery.draft": "Borrador", "admin.portfolio.gallery.no_portfolio_items": "No se encontraron elementos del portafolio", "admin.portfolio.gallery.select_all_count": "Seleccionar todo ({count})", "admin.portfolio.gallery.selected_count": "{count} seleccionados", "admin.portfolio.gallery.empty_add_hint": "Haz clic arriba en «Añadir elemento al portafolio» para subir fotografías, recorridos en vídeo o contenido de YouTube/Vimeo.", "admin.portfolio.gallery.empty_filter_hint": "Ningún elemento del portafolio coincide con los filtros de búsqueda actuales."
  },
  fr: { ...en,
    "admin.portfolio.gallery.all_items": "Tous les éléments ({count})", "admin.portfolio.gallery.photos": "Photos / images (ligne 1) ({count})", "admin.portfolio.gallery.drone_videos": "Vidéos par drone (ligne 2) ({count})", "admin.portfolio.gallery.interior_videos": "Visites intérieures (ligne 3) ({count})", "admin.portfolio.gallery.drone_photos": "Photos par drone (ligne 4) ({count})", "admin.portfolio.gallery.search_items": "Rechercher par titre, mot-clé ou description...", "admin.portfolio.gallery.all_categories": "Toutes les catégories", "admin.portfolio.gallery.photos_filter": "Photos / images (ligne 1)", "admin.portfolio.gallery.drone_videos_filter": "Vidéos aériennes par drone (ligne 2)", "admin.portfolio.gallery.interior_videos_filter": "Visites intérieures (ligne 3)", "admin.portfolio.gallery.drone_photos_filter": "Photos par drone (ligne 4)", "admin.portfolio.gallery.all_videos": "Tous les éléments vidéo", "admin.portfolio.gallery.mixed": "Galeries mixtes", "admin.portfolio.gallery.all_status": "Tous les statuts", "common.published": "Publié", "admin.portfolio.gallery.draft_hidden": "Brouillon (masqué)", "admin.portfolio.gallery.bulk": "Action groupée :", "common.publish": "Publier", "admin.portfolio.gallery.draft": "Brouillon", "admin.portfolio.gallery.no_portfolio_items": "Aucun élément de portfolio trouvé", "admin.portfolio.gallery.select_all_count": "Tout sélectionner ({count})", "admin.portfolio.gallery.selected_count": "{count} sélectionnés", "admin.portfolio.gallery.empty_add_hint": "Cliquez ci-dessus sur « Ajouter un élément au portfolio » pour importer des photos, des visites vidéo ou des intégrations YouTube/Vimeo.", "admin.portfolio.gallery.empty_filter_hint": "Aucun élément du portfolio ne correspond aux filtres de recherche actuels."
  }
} as const;
