const en = {
  "admin.social.modal_close": "Close modal",
  "admin.social.group_title_placeholder": "e.g. Main Socials",
  "admin.social.link_title_placeholder": "e.g. Instagram",
  "admin.social.group_subtitle_placeholder": "e.g. Official channels",
  "admin.social.link_subtitle_placeholder": "e.g. @spsstudio",
  "admin.social.url_placeholder": "https://instagram.com/spsstudio or wa.me/...",
  "admin.social.badge_placeholder": "e.g. Daily, 4K Video, Fast Reply",
  "admin.social.preview_group_title": "Group Title",
  "admin.social.preview_platform_title": "Social Platform",
  "admin.social.color_hex_placeholder": "#E4405F",
  "admin.social.platform.instagram": "Instagram", "admin.social.platform.facebook": "Facebook", "admin.social.platform.youtube": "YouTube", "admin.social.platform.tiktok": "TikTok", "admin.social.platform.linkedin": "LinkedIn", "admin.social.platform.x": "X (Twitter)", "admin.social.platform.whatsapp": "WhatsApp", "admin.social.platform.telegram": "Telegram", "admin.social.platform.vimeo": "Vimeo", "admin.social.platform.pinterest": "Pinterest", "admin.social.platform.threads": "Threads", "admin.social.platform.website": "Website / Portal", "admin.social.platform.email": "Email / Direct", "admin.social.platform.phone": "Phone / Hotline", "admin.social.platform.github": "GitHub", "admin.social.platform.discord": "Discord", "admin.social.platform.behance": "Behance", "admin.social.platform.dribbble": "Dribbble", "admin.social.platform.custom": "Custom Channel",
  "admin.social.platform_badge.instagram": "Daily Shoots", "admin.social.platform_badge.facebook": "Community", "admin.social.platform_badge.youtube": "4K Tours", "admin.social.platform_badge.tiktok": "Trending", "admin.social.platform_badge.linkedin": "B2B Network", "admin.social.platform_badge.x": "Updates", "admin.social.platform_badge.whatsapp": "Fast Reply", "admin.social.platform_badge.telegram": "Channel", "admin.social.platform_badge.vimeo": "HDR Video", "admin.social.platform_badge.pinterest": "Moodboard", "admin.social.platform_badge.website": "Official", "admin.social.platform_badge.email": "Inquiry", "admin.social.platform_badge.phone": "Call Us", "admin.social.platform_badge.github": "Open Source", "admin.social.platform_badge.discord": "Server", "admin.social.platform_badge.behance": "Showcase", "admin.social.platform_badge.dribbble": "Design",
  "admin.social.group_icon.share-2": "Social Network", "admin.social.group_icon.folder": "Folder", "admin.social.group_icon.briefcase": "Professional / B2B", "admin.social.group_icon.message-circle": "Messaging", "admin.social.group_icon.layers": "Categories / Layers", "admin.social.group_icon.globe": "Regional / Web", "admin.social.group_icon.sparkles": "Featured Channels", "admin.social.group_icon.camera": "Photography", "admin.social.group_icon.video": "Video Showcase", "admin.social.group_icon.building": "Real Estate Portals", "admin.social.group_icon.star": "VIP / Direct", "admin.social.group_icon.compass": "Explore & Community",
  "admin.social.color.instagram": "Instagram Pink", "admin.social.color.facebook": "Facebook Blue", "admin.social.color.youtube": "YouTube Red", "admin.social.color.linkedin": "LinkedIn Blue", "admin.social.color.whatsapp": "WhatsApp Green", "admin.social.color.telegram": "Telegram Cyan", "admin.social.color.vimeo": "Vimeo Aqua", "admin.social.color.pinterest": "Pinterest Red"
};

export const adminSocialNodeModalTranslations = {
  en,
  hu: { ...en,
    "admin.social.modal_close": "Modal bezárása", "admin.social.group_title_placeholder": "pl. Fő közösségi csatornák", "admin.social.link_title_placeholder": "pl. Instagram", "admin.social.group_subtitle_placeholder": "pl. Hivatalos csatornák", "admin.social.link_subtitle_placeholder": "pl. @spsstudio", "admin.social.badge_placeholder": "pl. Napi, 4K videó, Gyors válasz", "admin.social.preview_group_title": "Csoport címe", "admin.social.preview_platform_title": "Közösségi platform",
    "admin.social.platform.website": "Weboldal / portál", "admin.social.platform.email": "E-mail / közvetlen", "admin.social.platform.phone": "Telefon / forródrót", "admin.social.platform.custom": "Egyéni csatorna",
    "admin.social.platform_badge.instagram": "Napi fotózások", "admin.social.platform_badge.facebook": "Közösség", "admin.social.platform_badge.youtube": "4K túrák", "admin.social.platform_badge.tiktok": "Felkapott", "admin.social.platform_badge.linkedin": "B2B hálózat", "admin.social.platform_badge.x": "Frissítések", "admin.social.platform_badge.whatsapp": "Gyors válasz", "admin.social.platform_badge.telegram": "Csatorna", "admin.social.platform_badge.vimeo": "HDR videó", "admin.social.platform_badge.website": "Hivatalos", "admin.social.platform_badge.email": "Érdeklődés", "admin.social.platform_badge.phone": "Hívj minket", "admin.social.platform_badge.github": "Nyílt forráskód", "admin.social.platform_badge.discord": "Szerver", "admin.social.platform_badge.behance": "Bemutató", "admin.social.platform_badge.dribbble": "Dizájn",
    "admin.social.group_icon.share-2": "Közösségi hálózat", "admin.social.group_icon.folder": "Mappa", "admin.social.group_icon.briefcase": "Professzionális / B2B", "admin.social.group_icon.message-circle": "Üzenetküldés", "admin.social.group_icon.layers": "Kategóriák / rétegek", "admin.social.group_icon.globe": "Regionális / web", "admin.social.group_icon.sparkles": "Kiemelt csatornák", "admin.social.group_icon.camera": "Fotózás", "admin.social.group_icon.video": "Videós bemutató", "admin.social.group_icon.building": "Ingatlanportálok", "admin.social.group_icon.star": "VIP / közvetlen", "admin.social.group_icon.compass": "Felfedezés és közösség",
    "admin.social.color.instagram": "Instagram-rózsaszín", "admin.social.color.facebook": "Facebook-kék", "admin.social.color.youtube": "YouTube-piros", "admin.social.color.linkedin": "LinkedIn-kék", "admin.social.color.whatsapp": "WhatsApp-zöld", "admin.social.color.telegram": "Telegram-cián", "admin.social.color.vimeo": "Vimeo-akva", "admin.social.color.pinterest": "Pinterest-piros"
  },
  de: { ...en,
    "admin.social.modal_close": "Dialog schließen", "admin.social.group_title_placeholder": "z. B. Wichtigste soziale Kanäle", "admin.social.link_title_placeholder": "z. B. Instagram", "admin.social.group_subtitle_placeholder": "z. B. Offizielle Kanäle", "admin.social.link_subtitle_placeholder": "z. B. @spsstudio", "admin.social.badge_placeholder": "z. B. Täglich, 4K-Video, Schnelle Antwort", "admin.social.preview_group_title": "Gruppentitel", "admin.social.preview_platform_title": "Soziale Plattform",
    "admin.social.platform.website": "Website / Portal", "admin.social.platform.email": "E-Mail / Direkt", "admin.social.platform.phone": "Telefon / Hotline", "admin.social.platform.custom": "Eigener Kanal",
    "admin.social.platform_badge.instagram": "Tägliche Shootings", "admin.social.platform_badge.facebook": "Community", "admin.social.platform_badge.youtube": "4K-Touren", "admin.social.platform_badge.tiktok": "Im Trend", "admin.social.platform_badge.linkedin": "B2B-Netzwerk", "admin.social.platform_badge.x": "Neuigkeiten", "admin.social.platform_badge.whatsapp": "Schnelle Antwort", "admin.social.platform_badge.telegram": "Kanal", "admin.social.platform_badge.vimeo": "HDR-Video", "admin.social.platform_badge.website": "Offiziell", "admin.social.platform_badge.email": "Anfrage", "admin.social.platform_badge.phone": "Jetzt anrufen", "admin.social.platform_badge.github": "Open Source", "admin.social.platform_badge.discord": "Server", "admin.social.platform_badge.behance": "Portfolio", "admin.social.platform_badge.dribbble": "Design",
    "admin.social.group_icon.share-2": "Soziales Netzwerk", "admin.social.group_icon.folder": "Ordner", "admin.social.group_icon.briefcase": "Professionell / B2B", "admin.social.group_icon.message-circle": "Nachrichten", "admin.social.group_icon.layers": "Kategorien / Ebenen", "admin.social.group_icon.globe": "Regional / Web", "admin.social.group_icon.sparkles": "Empfohlene Kanäle", "admin.social.group_icon.camera": "Fotografie", "admin.social.group_icon.video": "Video-Showcase", "admin.social.group_icon.building": "Immobilienportale", "admin.social.group_icon.star": "VIP / Direkt", "admin.social.group_icon.compass": "Entdecken & Community",
    "admin.social.color.instagram": "Instagram-Pink", "admin.social.color.facebook": "Facebook-Blau", "admin.social.color.youtube": "YouTube-Rot", "admin.social.color.linkedin": "LinkedIn-Blau", "admin.social.color.whatsapp": "WhatsApp-Grün", "admin.social.color.telegram": "Telegram-Cyan", "admin.social.color.vimeo": "Vimeo-Aqua", "admin.social.color.pinterest": "Pinterest-Rot"
  },
  es: { ...en,
    "admin.social.modal_close": "Cerrar ventana", "admin.social.group_title_placeholder": "p. ej., Redes principales", "admin.social.link_title_placeholder": "p. ej., Instagram", "admin.social.group_subtitle_placeholder": "p. ej., Canales oficiales", "admin.social.link_subtitle_placeholder": "p. ej., @spsstudio", "admin.social.badge_placeholder": "p. ej., Diario, Vídeo 4K, Respuesta rápida", "admin.social.preview_group_title": "Título del grupo", "admin.social.preview_platform_title": "Plataforma social",
    "admin.social.platform.website": "Sitio web / portal", "admin.social.platform.email": "Correo / directo", "admin.social.platform.phone": "Teléfono / línea directa", "admin.social.platform.custom": "Canal personalizado",
    "admin.social.platform_badge.instagram": "Sesiones diarias", "admin.social.platform_badge.facebook": "Comunidad", "admin.social.platform_badge.youtube": "Tours 4K", "admin.social.platform_badge.tiktok": "Tendencia", "admin.social.platform_badge.linkedin": "Red B2B", "admin.social.platform_badge.x": "Novedades", "admin.social.platform_badge.whatsapp": "Respuesta rápida", "admin.social.platform_badge.telegram": "Canal", "admin.social.platform_badge.vimeo": "Vídeo HDR", "admin.social.platform_badge.website": "Oficial", "admin.social.platform_badge.email": "Consulta", "admin.social.platform_badge.phone": "Llámanos", "admin.social.platform_badge.github": "Código abierto", "admin.social.platform_badge.discord": "Servidor", "admin.social.platform_badge.behance": "Muestra", "admin.social.platform_badge.dribbble": "Diseño",
    "admin.social.group_icon.share-2": "Red social", "admin.social.group_icon.folder": "Carpeta", "admin.social.group_icon.briefcase": "Profesional / B2B", "admin.social.group_icon.message-circle": "Mensajería", "admin.social.group_icon.layers": "Categorías / capas", "admin.social.group_icon.globe": "Regional / web", "admin.social.group_icon.sparkles": "Canales destacados", "admin.social.group_icon.camera": "Fotografía", "admin.social.group_icon.video": "Muestra de vídeo", "admin.social.group_icon.building": "Portales inmobiliarios", "admin.social.group_icon.star": "VIP / directo", "admin.social.group_icon.compass": "Explorar y comunidad",
    "admin.social.color.instagram": "Rosa de Instagram", "admin.social.color.facebook": "Azul de Facebook", "admin.social.color.youtube": "Rojo de YouTube", "admin.social.color.linkedin": "Azul de LinkedIn", "admin.social.color.whatsapp": "Verde de WhatsApp", "admin.social.color.telegram": "Cian de Telegram", "admin.social.color.vimeo": "Aguamarina de Vimeo", "admin.social.color.pinterest": "Rojo de Pinterest"
  },
  fr: { ...en,
    "admin.social.modal_close": "Fermer la fenêtre", "admin.social.group_title_placeholder": "p. ex. Réseaux principaux", "admin.social.link_title_placeholder": "p. ex. Instagram", "admin.social.group_subtitle_placeholder": "p. ex. Canaux officiels", "admin.social.link_subtitle_placeholder": "p. ex. @spsstudio", "admin.social.badge_placeholder": "p. ex. Quotidien, Vidéo 4K, Réponse rapide", "admin.social.preview_group_title": "Titre du groupe", "admin.social.preview_platform_title": "Plateforme sociale",
    "admin.social.platform.website": "Site web / portail", "admin.social.platform.email": "E-mail / direct", "admin.social.platform.phone": "Téléphone / assistance", "admin.social.platform.custom": "Canal personnalisé",
    "admin.social.platform_badge.instagram": "Séances quotidiennes", "admin.social.platform_badge.facebook": "Communauté", "admin.social.platform_badge.youtube": "Visites 4K", "admin.social.platform_badge.tiktok": "Tendance", "admin.social.platform_badge.linkedin": "Réseau B2B", "admin.social.platform_badge.x": "Actualités", "admin.social.platform_badge.whatsapp": "Réponse rapide", "admin.social.platform_badge.telegram": "Canal", "admin.social.platform_badge.vimeo": "Vidéo HDR", "admin.social.platform_badge.website": "Officiel", "admin.social.platform_badge.email": "Demande", "admin.social.platform_badge.phone": "Appelez-nous", "admin.social.platform_badge.github": "Open source", "admin.social.platform_badge.discord": "Serveur", "admin.social.platform_badge.behance": "Présentation", "admin.social.platform_badge.dribbble": "Design",
    "admin.social.group_icon.share-2": "Réseau social", "admin.social.group_icon.folder": "Dossier", "admin.social.group_icon.briefcase": "Professionnel / B2B", "admin.social.group_icon.message-circle": "Messagerie", "admin.social.group_icon.layers": "Catégories / calques", "admin.social.group_icon.globe": "Régional / web", "admin.social.group_icon.sparkles": "Canaux en vedette", "admin.social.group_icon.camera": "Photographie", "admin.social.group_icon.video": "Présentation vidéo", "admin.social.group_icon.building": "Portails immobiliers", "admin.social.group_icon.star": "VIP / direct", "admin.social.group_icon.compass": "Explorer et communauté",
    "admin.social.color.instagram": "Rose Instagram", "admin.social.color.facebook": "Bleu Facebook", "admin.social.color.youtube": "Rouge YouTube", "admin.social.color.linkedin": "Bleu LinkedIn", "admin.social.color.whatsapp": "Vert WhatsApp", "admin.social.color.telegram": "Cyan Telegram", "admin.social.color.vimeo": "Aqua Vimeo", "admin.social.color.pinterest": "Rouge Pinterest"
  }
} as const;
