const en = {
  "admin.portfolio.card.image_visual": "Image",
  "admin.portfolio.media.drag": "Drag to reorder", "admin.portfolio.media.select": "Select item", "admin.portfolio.media.drone_photo": "Drone photo (Row 4)", "admin.portfolio.media.drone_video": "Drone video (Row 2)", "admin.portfolio.media.interior_video": "Interior video (Row 3)", "admin.portfolio.media.no_preview": "No media preview",
  "admin.portfolio.card.untitled": "Untitled portfolio", "admin.portfolio.card.uncategorized": "Uncategorized", "admin.portfolio.card.drone_photo_hint": "Row 4: Drone Photo", "admin.portfolio.card.drone_video_hint": "Row 2: Drone Video", "admin.portfolio.card.interior_video_hint": "Row 3: Interior Video", "admin.portfolio.card.image_hint": "Row 1: Image", "admin.portfolio.card.image": "Image", "admin.portfolio.card.featured": "Featured item", "admin.portfolio.card.quick_edit_title": "Click to quick-edit title", "admin.portfolio.card.toggle_publish": "Click to toggle publish status", "admin.portfolio.card.save_quick_edit": "Save quick edit", "admin.portfolio.card.cancel_quick_edit": "Cancel quick edit", "admin.portfolio.card.delete": "Delete item"
};

export const adminPortfolioSortableItemTranslations = {
  en,
  hu: { ...en,
    "admin.portfolio.card.image_visual": "Kép",
    "admin.portfolio.media.drag": "Húzd az átrendezéshez", "admin.portfolio.media.select": "Elem kijelölése", "admin.portfolio.media.drone_photo": "Drónfotó (4. sor)", "admin.portfolio.media.drone_video": "Drónvideó (2. sor)", "admin.portfolio.media.interior_video": "Beltéri videó (3. sor)", "admin.portfolio.media.no_preview": "Nincs média-előnézet", "admin.portfolio.card.untitled": "Névtelen portfólió", "admin.portfolio.card.uncategorized": "Kategorizálatlan", "admin.portfolio.card.drone_photo_hint": "4. sor: drónfotó", "admin.portfolio.card.drone_video_hint": "2. sor: drónvideó", "admin.portfolio.card.interior_video_hint": "3. sor: beltéri videó", "admin.portfolio.card.image_hint": "1. sor: kép", "admin.portfolio.card.image": "Kép", "admin.portfolio.card.featured": "Kiemelt elem", "admin.portfolio.card.quick_edit_title": "Kattints a cím gyorsszerkesztéséhez", "admin.portfolio.card.toggle_publish": "Kattints a közzétételi állapot váltásához", "admin.portfolio.card.save_quick_edit": "Gyorsszerkesztés mentése", "admin.portfolio.card.cancel_quick_edit": "Gyorsszerkesztés megszakítása", "admin.portfolio.card.delete": "Elem törlése"
  },
  de: { ...en,
    "admin.portfolio.card.image_visual": "Bild",
    "admin.portfolio.media.drag": "Zum Sortieren ziehen", "admin.portfolio.media.select": "Element auswählen", "admin.portfolio.media.drone_photo": "Drohnenfoto (Zeile 4)", "admin.portfolio.media.drone_video": "Drohnenvideo (Zeile 2)", "admin.portfolio.media.interior_video": "Innenraumvideo (Zeile 3)", "admin.portfolio.media.no_preview": "Keine Medienvorschau", "admin.portfolio.card.untitled": "Unbenanntes Portfolio", "admin.portfolio.card.uncategorized": "Ohne Kategorie", "admin.portfolio.card.drone_photo_hint": "Zeile 4: Drohnenfoto", "admin.portfolio.card.drone_video_hint": "Zeile 2: Drohnenvideo", "admin.portfolio.card.interior_video_hint": "Zeile 3: Innenraumvideo", "admin.portfolio.card.image_hint": "Zeile 1: Bild", "admin.portfolio.card.image": "Bild", "admin.portfolio.card.featured": "Hervorgehobenes Element", "admin.portfolio.card.quick_edit_title": "Zum schnellen Bearbeiten des Titels klicken", "admin.portfolio.card.toggle_publish": "Zum Ändern des Veröffentlichungsstatus klicken", "admin.portfolio.card.save_quick_edit": "Schnellbearbeitung speichern", "admin.portfolio.card.cancel_quick_edit": "Schnellbearbeitung abbrechen", "admin.portfolio.card.delete": "Element löschen"
  },
  es: { ...en,
    "admin.portfolio.card.image_visual": "Imagen",
    "admin.portfolio.media.drag": "Arrastrar para reordenar", "admin.portfolio.media.select": "Seleccionar elemento", "admin.portfolio.media.drone_photo": "Foto de dron (fila 4)", "admin.portfolio.media.drone_video": "Vídeo de dron (fila 2)", "admin.portfolio.media.interior_video": "Vídeo interior (fila 3)", "admin.portfolio.media.no_preview": "Sin vista previa multimedia", "admin.portfolio.card.untitled": "Portafolio sin título", "admin.portfolio.card.uncategorized": "Sin categoría", "admin.portfolio.card.drone_photo_hint": "Fila 4: foto de dron", "admin.portfolio.card.drone_video_hint": "Fila 2: vídeo de dron", "admin.portfolio.card.interior_video_hint": "Fila 3: vídeo interior", "admin.portfolio.card.image_hint": "Fila 1: imagen", "admin.portfolio.card.image": "Imagen", "admin.portfolio.card.featured": "Elemento destacado", "admin.portfolio.card.quick_edit_title": "Haz clic para editar rápidamente el título", "admin.portfolio.card.toggle_publish": "Haz clic para cambiar el estado de publicación", "admin.portfolio.card.save_quick_edit": "Guardar edición rápida", "admin.portfolio.card.cancel_quick_edit": "Cancelar edición rápida", "admin.portfolio.card.delete": "Eliminar elemento"
  },
  fr: { ...en,
    "admin.portfolio.card.image_visual": "Visuel",
    "admin.portfolio.media.drag": "Faire glisser pour réorganiser", "admin.portfolio.media.select": "Sélectionner l'élément", "admin.portfolio.media.drone_photo": "Photo par drone (ligne 4)", "admin.portfolio.media.drone_video": "Vidéo par drone (ligne 2)", "admin.portfolio.media.interior_video": "Vidéo intérieure (ligne 3)", "admin.portfolio.media.no_preview": "Aucun aperçu multimédia", "admin.portfolio.card.untitled": "Portfolio sans titre", "admin.portfolio.card.uncategorized": "Sans catégorie", "admin.portfolio.card.drone_photo_hint": "Ligne 4 : photo par drone", "admin.portfolio.card.drone_video_hint": "Ligne 2 : vidéo par drone", "admin.portfolio.card.interior_video_hint": "Ligne 3 : vidéo intérieure", "admin.portfolio.card.image_hint": "Ligne 1 : image", "admin.portfolio.card.image": "Image", "admin.portfolio.card.featured": "Élément en vedette", "admin.portfolio.card.quick_edit_title": "Cliquez pour modifier rapidement le titre", "admin.portfolio.card.toggle_publish": "Cliquez pour changer le statut de publication", "admin.portfolio.card.save_quick_edit": "Enregistrer la modification rapide", "admin.portfolio.card.cancel_quick_edit": "Annuler la modification rapide", "admin.portfolio.card.delete": "Supprimer l'élément"
  }
} as const;
