const en = {
  "admin.portfolio.category_modal.name": "Category Name",
  "admin.portfolio.category_modal.name_placeholder": "e.g. Architecture & Interiors",
  "admin.portfolio.category_modal.slug": "URL Slug",
  "admin.portfolio.category_modal.auto": "Automatic",
  "admin.portfolio.category_modal.reset_auto": "Reset to automatic",
  "admin.portfolio.category_modal.slug_help": "Used in public portfolio URLs. Lowercase letters, numbers, and hyphens only.",
  "admin.portfolio.category_modal.parent": "Parent Category",
  "admin.portfolio.category_modal.top_level": "Top level category",
  "admin.portfolio.category_modal.parent_help": "Optional. Select a parent to create a nested category.",
  "admin.portfolio.category_modal.description": "Description",
  "admin.portfolio.category_modal.description_placeholder": "Describe what belongs in this portfolio category...",
  "admin.portfolio.category_modal.sort_order": "Display Order",
  "admin.portfolio.category_modal.sort_help": "Lower numbers appear first.",
  "admin.portfolio.category_modal.press": "Press",
  "admin.portfolio.category_modal.to_exit": "to close",
  "admin.portfolio.category_modal.error_name": "Please provide a category name.",
  "admin.portfolio.category_modal.error_save": "Failed to save category. Please try again.",
  "admin.portfolio.category_modal.edit_title": "Edit Category",
  "admin.portfolio.category_modal.create_title": "Add Portfolio Category",
  "admin.portfolio.category_modal.edit_subtitle": "Update category naming, hierarchy, and public portfolio grouping.",
  "admin.portfolio.category_modal.create_subtitle": "Create a new portfolio category to organize showcase galleries and projects.",
  "admin.portfolio.category_modal.close": "Close dialog",
  "admin.portfolio.category_modal.slug_placeholder": "e.g. architecture-interiors",
  "admin.portfolio.category_modal.escape_key": "Esc",
  "admin.portfolio.category_modal.save_changes": "Save Changes",
  "admin.portfolio.category_modal.create_button": "Create Category"
};

export const adminPortfolioCategoryModalTranslations = {
  en,
  hu: { ...en,
    "admin.portfolio.category_modal.escape_key": "Escape",
    "admin.portfolio.category_modal.name": "Kategória neve", "admin.portfolio.category_modal.name_placeholder": "pl. Építészet és enteriőrök", "admin.portfolio.category_modal.slug": "URL-azonosító", "admin.portfolio.category_modal.auto": "Automatikus", "admin.portfolio.category_modal.reset_auto": "Automatikus visszaállítása", "admin.portfolio.category_modal.slug_help": "A nyilvános portfólió URL-jeiben használatos. Csak kisbetűk, számok és kötőjelek lehetnek benne.", "admin.portfolio.category_modal.parent": "Szülőkategória", "admin.portfolio.category_modal.top_level": "Felső szintű kategória", "admin.portfolio.category_modal.parent_help": "Opcionális. Beágyazott kategóriához válassz szülőkategóriát.", "admin.portfolio.category_modal.description": "Leírás", "admin.portfolio.category_modal.description_placeholder": "Írd le, mi tartozik ebbe a portfóliókategóriába...", "admin.portfolio.category_modal.sort_order": "Megjelenítési sorrend", "admin.portfolio.category_modal.sort_help": "Az alacsonyabb számok jelennek meg előbb.", "admin.portfolio.category_modal.press": "Nyomd meg az", "admin.portfolio.category_modal.to_exit": "billentyűt a bezáráshoz", "admin.portfolio.category_modal.error_name": "Adj meg egy kategórianevet.", "admin.portfolio.category_modal.error_save": "A kategória mentése sikertelen. Próbáld újra.", "admin.portfolio.category_modal.edit_title": "Kategória szerkesztése", "admin.portfolio.category_modal.create_title": "Portfóliókategória hozzáadása", "admin.portfolio.category_modal.edit_subtitle": "Módosítsd a kategória nevét, hierarchiáját és nyilvános portfólióbeli csoportosítását.", "admin.portfolio.category_modal.create_subtitle": "Hozz létre új kategóriát a bemutatógalériák és projektek rendszerezéséhez.", "admin.portfolio.category_modal.close": "Párbeszédablak bezárása", "admin.portfolio.category_modal.slug_placeholder": "pl. epiteszet-enteriorok", "admin.portfolio.category_modal.save_changes": "Módosítások mentése", "admin.portfolio.category_modal.create_button": "Kategória létrehozása"
  },
  de: { ...en,
    "admin.portfolio.category_modal.escape_key": "Escape",
    "admin.portfolio.category_modal.name": "Kategoriename", "admin.portfolio.category_modal.name_placeholder": "z. B. Architektur & Innenräume", "admin.portfolio.category_modal.slug": "URL-Kennung", "admin.portfolio.category_modal.auto": "Automatisch", "admin.portfolio.category_modal.reset_auto": "Automatik wiederherstellen", "admin.portfolio.category_modal.slug_help": "Wird in öffentlichen Portfolio-URLs verwendet. Nur Kleinbuchstaben, Zahlen und Bindestriche.", "admin.portfolio.category_modal.parent": "Übergeordnete Kategorie", "admin.portfolio.category_modal.top_level": "Kategorie der obersten Ebene", "admin.portfolio.category_modal.parent_help": "Optional. Wählen Sie eine übergeordnete Kategorie für eine Verschachtelung.", "admin.portfolio.category_modal.description": "Beschreibung", "admin.portfolio.category_modal.description_placeholder": "Beschreiben Sie den Inhalt dieser Portfolio-Kategorie...", "admin.portfolio.category_modal.sort_order": "Anzeigereihenfolge", "admin.portfolio.category_modal.sort_help": "Niedrigere Zahlen werden zuerst angezeigt.", "admin.portfolio.category_modal.press": "Drücken Sie", "admin.portfolio.category_modal.to_exit": "zum Schließen", "admin.portfolio.category_modal.error_name": "Bitte geben Sie einen Kategorienamen ein.", "admin.portfolio.category_modal.error_save": "Kategorie konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.", "admin.portfolio.category_modal.edit_title": "Kategorie bearbeiten", "admin.portfolio.category_modal.create_title": "Portfolio-Kategorie hinzufügen", "admin.portfolio.category_modal.edit_subtitle": "Bearbeiten Sie Name, Hierarchie und öffentliche Portfolio-Gruppierung.", "admin.portfolio.category_modal.create_subtitle": "Erstellen Sie eine Kategorie zum Ordnen von Präsentationsgalerien und Projekten.", "admin.portfolio.category_modal.close": "Dialog schließen", "admin.portfolio.category_modal.slug_placeholder": "z. B. architektur-innenraeume", "admin.portfolio.category_modal.save_changes": "Änderungen speichern", "admin.portfolio.category_modal.create_button": "Kategorie erstellen"
  },
  es: { ...en,
    "admin.portfolio.category_modal.escape_key": "Escape",
    "admin.portfolio.category_modal.name": "Nombre de la categoría", "admin.portfolio.category_modal.name_placeholder": "p. ej., Arquitectura e interiores", "admin.portfolio.category_modal.slug": "Identificador URL", "admin.portfolio.category_modal.auto": "Automático", "admin.portfolio.category_modal.reset_auto": "Restablecer automático", "admin.portfolio.category_modal.slug_help": "Se usa en las URL públicas del portafolio. Solo minúsculas, números y guiones.", "admin.portfolio.category_modal.parent": "Categoría superior", "admin.portfolio.category_modal.top_level": "Categoría de nivel superior", "admin.portfolio.category_modal.parent_help": "Opcional. Selecciona una categoría superior para crear una categoría anidada.", "admin.portfolio.category_modal.description": "Descripción", "admin.portfolio.category_modal.description_placeholder": "Describe qué pertenece a esta categoría del portafolio...", "admin.portfolio.category_modal.sort_order": "Orden de visualización", "admin.portfolio.category_modal.sort_help": "Los números más bajos aparecen primero.", "admin.portfolio.category_modal.press": "Pulsa", "admin.portfolio.category_modal.to_exit": "para cerrar", "admin.portfolio.category_modal.error_name": "Introduce un nombre para la categoría.", "admin.portfolio.category_modal.error_save": "No se pudo guardar la categoría. Inténtalo de nuevo.", "admin.portfolio.category_modal.edit_title": "Editar categoría", "admin.portfolio.category_modal.create_title": "Añadir categoría de portafolio", "admin.portfolio.category_modal.edit_subtitle": "Actualiza el nombre, la jerarquía y la agrupación pública del portafolio.", "admin.portfolio.category_modal.create_subtitle": "Crea una categoría para organizar galerías y proyectos destacados.", "admin.portfolio.category_modal.close": "Cerrar ventana", "admin.portfolio.category_modal.slug_placeholder": "p. ej., arquitectura-interiores", "admin.portfolio.category_modal.save_changes": "Guardar cambios", "admin.portfolio.category_modal.create_button": "Crear categoría"
  },
  fr: { ...en,
    "admin.portfolio.category_modal.escape_key": "Échap",
    "admin.portfolio.category_modal.name": "Nom de la catégorie", "admin.portfolio.category_modal.name_placeholder": "p. ex. Architecture et intérieurs", "admin.portfolio.category_modal.slug": "Identifiant URL", "admin.portfolio.category_modal.auto": "Automatique", "admin.portfolio.category_modal.reset_auto": "Rétablir le mode automatique", "admin.portfolio.category_modal.slug_help": "Utilisé dans les URL publiques du portfolio. Uniquement des minuscules, chiffres et tirets.", "admin.portfolio.category_modal.parent": "Catégorie parente", "admin.portfolio.category_modal.top_level": "Catégorie de premier niveau", "admin.portfolio.category_modal.parent_help": "Facultatif. Sélectionnez une catégorie parente pour créer une catégorie imbriquée.", "admin.portfolio.category_modal.description": "Description", "admin.portfolio.category_modal.description_placeholder": "Décrivez le contenu de cette catégorie du portfolio...", "admin.portfolio.category_modal.sort_order": "Ordre d'affichage", "admin.portfolio.category_modal.sort_help": "Les nombres les plus bas apparaissent en premier.", "admin.portfolio.category_modal.press": "Appuyez sur", "admin.portfolio.category_modal.to_exit": "pour fermer", "admin.portfolio.category_modal.error_name": "Veuillez saisir un nom de catégorie.", "admin.portfolio.category_modal.error_save": "Impossible d'enregistrer la catégorie. Veuillez réessayer.", "admin.portfolio.category_modal.edit_title": "Modifier la catégorie", "admin.portfolio.category_modal.create_title": "Ajouter une catégorie de portfolio", "admin.portfolio.category_modal.edit_subtitle": "Modifiez le nom, la hiérarchie et le regroupement public du portfolio.", "admin.portfolio.category_modal.create_subtitle": "Créez une catégorie pour organiser les galeries et projets présentés.", "admin.portfolio.category_modal.close": "Fermer la fenêtre", "admin.portfolio.category_modal.slug_placeholder": "p. ex. architecture-interieurs", "admin.portfolio.category_modal.save_changes": "Enregistrer les modifications", "admin.portfolio.category_modal.create_button": "Créer la catégorie"
  }
} as const;
