// Generated by scripts/generate-api-route-index.mjs. Do not edit manually.
export const generatedApiRoutes = [
  {
    "method": "PUT",
    "path": "/api/admin/account/password",
    "summary": "Replaces or updates the account resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/account/profile",
    "summary": "Reads the account resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/account/profile",
    "summary": "Partially updates the account resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/audit-logs",
    "summary": "Reads the audit logs resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/branding/upload",
    "summary": "Creates or triggers an action for the branding resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/budgets",
    "summary": "Reads the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/budgets",
    "summary": "Creates or triggers an action for the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/budgets/:id",
    "summary": "Deletes the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/budgets/:id",
    "summary": "Replaces or updates the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/budgets/admins",
    "summary": "Reads the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/budgets/audit-logs",
    "summary": "Reads the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/budgets/settings",
    "summary": "Reads the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/budgets/settings",
    "summary": "Replaces or updates the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/budgets/summary",
    "summary": "Reads the budgets resource.",
    "access": "Admin",
    "source": "budgetRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/business-relations/audit",
    "summary": "Reads the business relations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/calendar-events",
    "summary": "Reads the calendar events resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/calendar-events",
    "summary": "Creates or triggers an action for the calendar events resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/calendar-events/:id",
    "summary": "Deletes the calendar events resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/calendar-events/:id",
    "summary": "Replaces or updates the calendar events resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/calendar-team-members",
    "summary": "Reads the calendar team members resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/campaigns",
    "summary": "Reads the campaigns resource.",
    "access": "Admin",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/campaigns",
    "summary": "Creates or triggers an action for the campaigns resource.",
    "access": "Admin",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/campaigns/:id",
    "summary": "Deletes the campaigns resource.",
    "access": "Admin",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/campaigns/:id",
    "summary": "Replaces or updates the campaigns resource.",
    "access": "Admin",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/campaigns/:id/active",
    "summary": "Partially updates the campaigns resource.",
    "access": "Admin",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/campaigns/:id/submissions",
    "summary": "Reads the campaigns resource.",
    "access": "Admin",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/campaigns/available-coupons",
    "summary": "Reads the campaigns resource.",
    "access": "Admin",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/categories",
    "summary": "Reads the categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/categories",
    "summary": "Creates or triggers an action for the categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/categories/:id",
    "summary": "Deletes the categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/categories/:id",
    "summary": "Replaces or updates the categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/changelog",
    "summary": "Reads the changelog resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/changelog",
    "summary": "Creates or triggers an action for the changelog resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/changelog/:id",
    "summary": "Deletes the changelog resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/changelog/:id",
    "summary": "Replaces or updates the changelog resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/client-feedback",
    "summary": "Reads the client feedback resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/client-feedback/:id",
    "summary": "Partially updates the client feedback resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/client-feedback/:id/messages",
    "summary": "Reads the client feedback resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/client-feedback/:id/messages",
    "summary": "Creates or triggers an action for the client feedback resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/client-feedback/:id/typing",
    "summary": "Reads the client feedback resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/client-feedback/:id/typing",
    "summary": "Creates or triggers an action for the client feedback resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/clients",
    "summary": "Reads the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/clients",
    "summary": "Creates or triggers an action for the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/clients/:id",
    "summary": "Deletes the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/clients/:id",
    "summary": "Reads the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/clients/:id",
    "summary": "Replaces or updates the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/clients/:id/links",
    "summary": "Reads the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/clients/:id/links",
    "summary": "Creates or triggers an action for the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/clients/:id/links/:linkId",
    "summary": "Deletes the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/clients/:id/links/:linkId",
    "summary": "Replaces or updates the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/clients/:id/links/reorder",
    "summary": "Creates or triggers an action for the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/clients/:id/properties",
    "summary": "Reads the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/clients/:id/properties",
    "summary": "Creates or triggers an action for the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/clients/:id/properties/:propertyId",
    "summary": "Deletes the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/clients/:id/properties/:propertyId",
    "summary": "Replaces or updates the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/clients/:id/properties/reorder",
    "summary": "Creates or triggers an action for the clients resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/contacts",
    "summary": "Reads the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/contacts/:id",
    "summary": "Deletes the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/contacts/:id",
    "summary": "Replaces or updates the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/contacts/:id/archive",
    "summary": "Replaces or updates the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/contacts/:id/read",
    "summary": "Replaces or updates the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/contacts/:id/unarchive",
    "summary": "Replaces or updates the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/contacts/bulk-archive",
    "summary": "Creates or triggers an action for the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/contacts/bulk-delete",
    "summary": "Creates or triggers an action for the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/contacts/bulk-unarchive",
    "summary": "Creates or triggers an action for the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/contacts/bulk-update",
    "summary": "Creates or triggers an action for the contacts resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/cookie-catalog",
    "summary": "Reads the cookie catalog resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/cookie-catalog",
    "summary": "Replaces or updates the cookie catalog resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/cookie-catalog/infrastructure-audit",
    "summary": "Reads the cookie catalog resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/cookie-catalog/infrastructure-audit",
    "summary": "Creates or triggers an action for the cookie catalog resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/crm/:id",
    "summary": "Deletes the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/crm/:id",
    "summary": "Replaces or updates the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/crm/:id/links",
    "summary": "Reads the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm/:id/links",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/crm/:id/links/:linkId",
    "summary": "Deletes the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/crm/:id/links/:linkId",
    "summary": "Replaces or updates the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm/:id/links/reorder",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/crm/:id/properties",
    "summary": "Reads the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm/:id/properties",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/crm/:id/properties/:propertyId",
    "summary": "Deletes the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/crm/:id/properties/:propertyId",
    "summary": "Replaces or updates the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm/:id/properties/reorder",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/crm/:type",
    "summary": "Reads the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/crm/check-email",
    "summary": "Reads the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/crm/check-portal",
    "summary": "Reads the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/crm/customers/:id/audit-logs",
    "summary": "Reads the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/crm/customers/:id/overview",
    "summary": "Reads the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm/customers/:id/portal-access",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm/customers/:id/send-portal-invite",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm/customers/bulk-portal-invite",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/crm/customers/bulk-status",
    "summary": "Creates or triggers an action for the crm resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/email/config",
    "summary": "Reads the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/email/logs",
    "summary": "Deletes the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/email/logs",
    "summary": "Reads the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/email/preview",
    "summary": "Creates or triggers an action for the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/email/send-test",
    "summary": "Creates or triggers an action for the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/email/templates",
    "summary": "Reads the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/email/templates/:key",
    "summary": "Reads the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/email/templates/:key",
    "summary": "Replaces or updates the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/email/templates/:key/reset",
    "summary": "Creates or triggers an action for the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/email/templates/marketing",
    "summary": "Creates or triggers an action for the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/email/templates/marketing/:key",
    "summary": "Deletes the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/email/templates/marketing/:key/metadata",
    "summary": "Replaces or updates the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/email/templates/marketing/:key/send",
    "summary": "Creates or triggers an action for the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/email/templates/preview",
    "summary": "Creates or triggers an action for the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/email/templates/send-test",
    "summary": "Creates or triggers an action for the email resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/exchange-rates",
    "summary": "Reads the exchange rates resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/exit-coupons/config",
    "summary": "Reads the exit coupons resource.",
    "access": "Admin",
    "source": "exitCouponRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/exit-coupons/config",
    "summary": "Replaces or updates the exit coupons resource.",
    "access": "Admin",
    "source": "exitCouponRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/exit-coupons/issues",
    "summary": "Reads the exit coupons resource.",
    "access": "Admin",
    "source": "exitCouponRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/extra-services",
    "summary": "Reads the extra services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/extra-services",
    "summary": "Creates or triggers an action for the extra services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/extra-services/:id",
    "summary": "Deletes the extra services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/extra-services/:id",
    "summary": "Replaces or updates the extra services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/extra-services/:id/toggle",
    "summary": "Partially updates the extra services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/extra-services/reorder",
    "summary": "Creates or triggers an action for the extra services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/faq-categories",
    "summary": "Reads the faq categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/faq-categories",
    "summary": "Creates or triggers an action for the faq categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/faq-categories/:id",
    "summary": "Deletes the faq categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/faq-categories/:id",
    "summary": "Replaces or updates the faq categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/faq-categories/:id/publish",
    "summary": "Partially updates the faq categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/faq-categories/reorder",
    "summary": "Creates or triggers an action for the faq categories resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/faqs",
    "summary": "Reads the faqs resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/faqs",
    "summary": "Creates or triggers an action for the faqs resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/faqs/:id",
    "summary": "Deletes the faqs resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/faqs/:id",
    "summary": "Replaces or updates the faqs resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/faqs/:id/publish",
    "summary": "Partially updates the faqs resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/faqs/reorder",
    "summary": "Creates or triggers an action for the faqs resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/fee-rules",
    "summary": "Reads the fee rules resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/fee-rules",
    "summary": "Creates or triggers an action for the fee rules resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/fee-rules/:id",
    "summary": "Deletes the fee rules resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/fee-rules/:id",
    "summary": "Replaces or updates the fee rules resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/fee-rules/:id/toggle",
    "summary": "Partially updates the fee rules resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/fee-rules/reorder",
    "summary": "Creates or triggers an action for the fee rules resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/google-analytics",
    "summary": "Reads the google analytics resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/info-bar/categories",
    "summary": "Reads the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/info-bar/categories",
    "summary": "Creates or triggers an action for the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/info-bar/categories/:id",
    "summary": "Deletes the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/info-bar/categories/:id",
    "summary": "Replaces or updates the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/info-bar/messages",
    "summary": "Reads the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/info-bar/messages",
    "summary": "Creates or triggers an action for the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/info-bar/messages/:id",
    "summary": "Deletes the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/info-bar/messages/:id",
    "summary": "Replaces or updates the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/info-bar/messages/reorder",
    "summary": "Creates or triggers an action for the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/info-bar/settings",
    "summary": "Reads the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/info-bar/settings",
    "summary": "Replaces or updates the info bar resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/invitations",
    "summary": "Reads the invitations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/invitations",
    "summary": "Creates or triggers an action for the invitations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/invitations/:id",
    "summary": "Deletes the invitations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/invitations/:id/resend",
    "summary": "Creates or triggers an action for the invitations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/invitations/:id/revoke",
    "summary": "Creates or triggers an action for the invitations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/invoices",
    "summary": "Reads the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/invoices",
    "summary": "Creates or triggers an action for the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/invoices/:id",
    "summary": "Deletes the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/invoices/:id",
    "summary": "Reads the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/invoices/:id",
    "summary": "Replaces or updates the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/invoices/:id/archive",
    "summary": "Partially updates the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/invoices/:id/payments",
    "summary": "Creates or triggers an action for the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/invoices/:id/send",
    "summary": "Creates or triggers an action for the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/invoices/:id/send-reminder",
    "summary": "Creates or triggers an action for the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/invoices/:id/status",
    "summary": "Partially updates the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/invoices/clients-lookup",
    "summary": "Reads the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/invoices/from-budget/:budgetId",
    "summary": "Creates or triggers an action for the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/invoices/next-number",
    "summary": "Reads the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/invoices/stripe-settings",
    "summary": "Reads the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/invoices/stripe-settings",
    "summary": "Replaces or updates the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/invoices/summary",
    "summary": "Reads the invoices resource.",
    "access": "Admin",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/legal-documents",
    "summary": "Reads the legal documents resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/legal-documents/:type/:locale",
    "summary": "Replaces or updates the legal documents resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/media-library/browse",
    "summary": "Reads the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media-library/download-link",
    "summary": "Creates or triggers an action for the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/media-library/editor-access",
    "summary": "Reads the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/media-library/editor-access/:userId",
    "summary": "Deletes the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/media-library/editor-access/:userId",
    "summary": "Replaces or updates the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/media-library/file-request",
    "summary": "Reads the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/media-library/file-requests",
    "summary": "Deletes the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/media-library/file-requests",
    "summary": "Reads the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/media-library/file-requests",
    "summary": "Replaces or updates the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media-library/folders",
    "summary": "Creates or triggers an action for the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/media-library/status",
    "summary": "Reads the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media-library/upload",
    "summary": "Creates or triggers an action for the media library resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/batch-restructure",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/restructure-item",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload-structured",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload/appwrite/register",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload/appwrite/session",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload/chunk",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload/chunk-complete",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload/direct/abort",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload/direct/complete",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload/direct/init",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/upload/direct/sign-part",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/media/validate-filename",
    "summary": "Creates or triggers an action for the media resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/notifications",
    "summary": "Reads the notifications resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/notifications/:id",
    "summary": "Deletes the notifications resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/notifications/:id/archive",
    "summary": "Partially updates the notifications resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/notifications/:id/read",
    "summary": "Partially updates the notifications resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/notifications/:id/unarchive",
    "summary": "Partially updates the notifications resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/notifications/read-all",
    "summary": "Partially updates the notifications resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/open-source-settings",
    "summary": "Reads the open source settings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/open-source-settings",
    "summary": "Replaces or updates the open source settings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/payment-requests",
    "summary": "Reads the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/payment-requests",
    "summary": "Creates or triggers an action for the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/payment-requests/:id",
    "summary": "Deletes the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/payment-requests/:id",
    "summary": "Reads the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/payment-requests/:id",
    "summary": "Replaces or updates the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/payment-requests/:id/review",
    "summary": "Creates or triggers an action for the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/payment-requests/categories",
    "summary": "Reads the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/payment-requests/categories",
    "summary": "Creates or triggers an action for the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/payment-requests/categories/:id",
    "summary": "Deletes the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/payment-requests/categories/:id",
    "summary": "Replaces or updates the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/payment-requests/links-lookup",
    "summary": "Reads the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/payment-requests/summary",
    "summary": "Reads the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/payment-requests/upload",
    "summary": "Creates or triggers an action for the payment requests resource.",
    "access": "Admin",
    "source": "paymentRequestRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/portfolio",
    "summary": "Reads the portfolio resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/portfolio",
    "summary": "Creates or triggers an action for the portfolio resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/portfolio/:id",
    "summary": "Deletes the portfolio resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/portfolio/:id",
    "summary": "Replaces or updates the portfolio resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/portfolio/:id/media",
    "summary": "Creates or triggers an action for the portfolio resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/portfolio/bulk",
    "summary": "Creates or triggers an action for the portfolio resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/portfolio/reorder",
    "summary": "Creates or triggers an action for the portfolio resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/pricing",
    "summary": "Reads the pricing resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/pricing",
    "summary": "Creates or triggers an action for the pricing resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/pricing/:id",
    "summary": "Deletes the pricing resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/pricing/:id",
    "summary": "Replaces or updates the pricing resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/pricing/:id/feature",
    "summary": "Partially updates the pricing resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/pricing/:id/publish",
    "summary": "Partially updates the pricing resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/pricing/reorder",
    "summary": "Creates or triggers an action for the pricing resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/projects",
    "summary": "Reads the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/projects",
    "summary": "Creates or triggers an action for the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/projects/:id",
    "summary": "Deletes the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/projects/:id",
    "summary": "Replaces or updates the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/projects/:id/milestones",
    "summary": "Creates or triggers an action for the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/projects/:id/milestones/:milestoneId",
    "summary": "Deletes the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/projects/:id/milestones/:milestoneId",
    "summary": "Replaces or updates the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/projects/:id/notify-client",
    "summary": "Creates or triggers an action for the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/projects/:id/timeline",
    "summary": "Reads the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/projects/:id/updates",
    "summary": "Creates or triggers an action for the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/projects/:id/updates/:updateId",
    "summary": "Deletes the projects resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/properties-core",
    "summary": "Reads the properties core resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/properties-core",
    "summary": "Creates or triggers an action for the properties core resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/properties-core/:id/archive",
    "summary": "Partially updates the properties core resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/properties-core/:id/detail",
    "summary": "Reads the properties core resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/property-listings",
    "summary": "Reads the property listings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/property-listings",
    "summary": "Creates or triggers an action for the property listings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/property-listings/:id",
    "summary": "Deletes the property listings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/property-listings/:id",
    "summary": "Replaces or updates the property listings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/property-listings/:id/visibility",
    "summary": "Partially updates the property listings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/public-notifications/broadcast",
    "summary": "Creates or triggers an action for the public notifications resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/push/public-key",
    "summary": "Reads the push resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/push/subscribe",
    "summary": "Creates or triggers an action for the push resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/push/unsubscribe",
    "summary": "Creates or triggers an action for the push resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/referrals/clients",
    "summary": "Reads the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/referrals/custom-codes",
    "summary": "Reads the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/custom-codes",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/referrals/custom-codes/:id",
    "summary": "Deletes the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/referrals/custom-codes/:id",
    "summary": "Partially updates the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/referrals/custom-codes/:id",
    "summary": "Replaces or updates the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/referrals/dashboard",
    "summary": "Reads the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/referrals/list",
    "summary": "Reads the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/referrals/referrals/:id/status",
    "summary": "Partially updates the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/referrals/:id/status",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/referrals/relationships/:id/status",
    "summary": "Partially updates the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/relationships/:id/status",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/referrals/rewards",
    "summary": "Reads the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/referrals/rewards/:id/status",
    "summary": "Partially updates the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/rewards/:id/status",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/rewards/grant",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/rewards/issue",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/rewards/redeem",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/referrals/settings",
    "summary": "Reads the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/referrals/settings",
    "summary": "Replaces or updates the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/referrals/stats",
    "summary": "Reads the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/referrals/tiers",
    "summary": "Reads the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/tiers",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/referrals/tiers/:id",
    "summary": "Deletes the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/referrals/tiers/:id",
    "summary": "Replaces or updates the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/referrals/users/:userId/tier",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Admin",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/role-menu-permissions",
    "summary": "Reads the role menu permissions resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/role-menu-permissions",
    "summary": "Replaces or updates the role menu permissions resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/services",
    "summary": "Reads the services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/services",
    "summary": "Creates or triggers an action for the services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/services/:id",
    "summary": "Deletes the services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/services/:id",
    "summary": "Replaces or updates the services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/services/:id/publish",
    "summary": "Partially updates the services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/services/reorder",
    "summary": "Creates or triggers an action for the services resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/settings",
    "summary": "Reads the settings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/settings",
    "summary": "Creates or triggers an action for the settings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/social-links",
    "summary": "Reads the social links resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/social-links",
    "summary": "Creates or triggers an action for the social links resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/social-links/:id",
    "summary": "Deletes the social links resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/social-links/:id",
    "summary": "Replaces or updates the social links resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/social-links/:id/toggle",
    "summary": "Partially updates the social links resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/social-links/reorder",
    "summary": "Creates or triggers an action for the social links resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/social-links/reset-defaults",
    "summary": "Creates or triggers an action for the social links resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/social-links/tree",
    "summary": "Reads the social links resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/sps-raw",
    "summary": "Reads the sps raw resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/sps-raw/posts",
    "summary": "Creates or triggers an action for the sps raw resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/sps-raw/posts/:id",
    "summary": "Deletes the sps raw resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/admin/sps-raw/posts/:id",
    "summary": "Partially updates the sps raw resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/sps-raw/settings",
    "summary": "Replaces or updates the sps raw resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/storage/diagnose-appwrite",
    "summary": "Reads the storage resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/storage/test-appwrite",
    "summary": "Creates or triggers an action for the storage resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/team",
    "summary": "Reads the team resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/team",
    "summary": "Creates or triggers an action for the team resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/team/:id",
    "summary": "Deletes the team resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/team/:id",
    "summary": "Replaces or updates the team resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/team/verification-code",
    "summary": "Creates or triggers an action for the team resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/teams",
    "summary": "Reads the teams resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/teams",
    "summary": "Creates or triggers an action for the teams resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/teams/:id",
    "summary": "Deletes the teams resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/teams/:id",
    "summary": "Replaces or updates the teams resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/testimonials",
    "summary": "Reads the testimonials resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/testimonials",
    "summary": "Creates or triggers an action for the testimonials resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/testimonials/:id",
    "summary": "Deletes the testimonials resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/testimonials/:id",
    "summary": "Replaces or updates the testimonials resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/themes",
    "summary": "Reads the themes resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/themes",
    "summary": "Creates or triggers an action for the themes resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/themes/:id",
    "summary": "Deletes the themes resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/themes/:id",
    "summary": "Replaces or updates the themes resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/themes/apply",
    "summary": "Creates or triggers an action for the themes resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/translations",
    "summary": "Reads the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/translations",
    "summary": "Creates or triggers an action for the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/translations/:locale/:key",
    "summary": "Deletes the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/translations/batch",
    "summary": "Creates or triggers an action for the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/admin/translations/key/:key",
    "summary": "Deletes the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/translations/migrate",
    "summary": "Creates or triggers an action for the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/translations/missing",
    "summary": "Reads the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/translations/scan-import",
    "summary": "Creates or triggers an action for the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/translations/stats",
    "summary": "Reads the translations resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/verify",
    "summary": "Reads the verify resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/whatsapp-settings",
    "summary": "Reads the whatsapp settings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/admin/whatsapp-settings",
    "summary": "Replaces or updates the whatsapp settings resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/workspace-chat/staff/conversations",
    "summary": "Reads the workspace chat resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/workspace-chat/staff/conversations",
    "summary": "Creates or triggers an action for the workspace chat resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/workspace-chat/staff/conversations/:id/messages",
    "summary": "Reads the workspace chat resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/workspace-chat/staff/conversations/:id/messages",
    "summary": "Creates or triggers an action for the workspace chat resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/workspace-chat/staff/conversations/:id/typing",
    "summary": "Reads the workspace chat resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/admin/workspace-chat/staff/conversations/:id/typing",
    "summary": "Creates or triggers an action for the workspace chat resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/admin/workspace-chat/staff/members",
    "summary": "Reads the workspace chat resource.",
    "access": "Admin",
    "source": "adminRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/email/disable/confirm",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/email/disable/start",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/email/enrollment/confirm",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/email/enrollment/start",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/email/resend",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "PUT",
    "path": "/api/auth/2fa/login-mode",
    "summary": "Replaces or updates the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/auth/2fa/status",
    "summary": "Reads the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/totp/disable",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/totp/enrollment/confirm",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/totp/enrollment/start",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/2fa/verify",
    "summary": "Creates or triggers an action for the 2fa resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/forgot-password",
    "summary": "Creates or triggers an action for the forgot password resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/login",
    "summary": "Creates or triggers an action for the login resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/magic-link",
    "summary": "Creates or triggers an action for the magic link resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/register",
    "summary": "Creates or triggers an action for the register resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/reset-password",
    "summary": "Creates or triggers an action for the reset password resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/auth/verify-magic-link",
    "summary": "Creates or triggers an action for the verify magic link resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/bonus-codes/redeem",
    "summary": "Creates or triggers an action for the bonus codes resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/dashboard",
    "summary": "Reads the dashboard resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/feedback/conversations",
    "summary": "Reads the feedback resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/feedback/conversations",
    "summary": "Creates or triggers an action for the feedback resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/feedback/conversations/:id/messages",
    "summary": "Reads the feedback resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/feedback/conversations/:id/messages",
    "summary": "Creates or triggers an action for the feedback resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/feedback/conversations/:id/typing",
    "summary": "Reads the feedback resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/feedback/conversations/:id/typing",
    "summary": "Creates or triggers an action for the feedback resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/help",
    "summary": "Reads the help resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/invoices",
    "summary": "Reads the invoices resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/invoices/:id",
    "summary": "Reads the invoices resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/links",
    "summary": "Reads the links resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/links",
    "summary": "Creates or triggers an action for the links resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/client/links/:id",
    "summary": "Deletes the links resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/client/links/:id",
    "summary": "Replaces or updates the links resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/notifications",
    "summary": "Reads the notifications resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/client/notifications/:id",
    "summary": "Deletes the notifications resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/client/notifications/:id/archive",
    "summary": "Partially updates the notifications resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/client/notifications/:id/read",
    "summary": "Partially updates the notifications resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/client/notifications/:id/unarchive",
    "summary": "Partially updates the notifications resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/client/notifications/read-all",
    "summary": "Partially updates the notifications resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/projects",
    "summary": "Reads the projects resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/projects/:projectId/galleries/:galleryId/download",
    "summary": "Creates or triggers an action for the projects resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/projects/:projectId/galleries/:galleryId/preview",
    "summary": "Creates or triggers an action for the projects resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/projects/:projectId/galleries/:galleryId/unlock",
    "summary": "Creates or triggers an action for the projects resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/projects/:projectId/gallery-pin/resend",
    "summary": "Creates or triggers an action for the projects resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/properties",
    "summary": "Reads the properties resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/properties",
    "summary": "Creates or triggers an action for the properties resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/client/properties/:id",
    "summary": "Deletes the properties resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/client/properties/:id",
    "summary": "Replaces or updates the properties resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/property-listing-account",
    "summary": "Reads the property listing account resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/property-listing-account/migrate",
    "summary": "Creates or triggers an action for the property listing account resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/property-listings",
    "summary": "Reads the property listings resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/property-listings",
    "summary": "Creates or triggers an action for the property listings resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "DELETE",
    "path": "/api/client/property-listings/:id",
    "summary": "Deletes the property listings resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/client/property-listings/:id",
    "summary": "Replaces or updates the property listings resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/push/public-key",
    "summary": "Reads the push resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/push/subscribe",
    "summary": "Creates or triggers an action for the push resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/push/unsubscribe",
    "summary": "Creates or triggers an action for the push resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/referrals/invite-email",
    "summary": "Creates or triggers an action for the referrals resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/referrals/profile",
    "summary": "Reads the referrals resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/client/rewards/redeem",
    "summary": "Creates or triggers an action for the rewards resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PUT",
    "path": "/api/client/settings/password",
    "summary": "Replaces or updates the settings resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/settings/profile",
    "summary": "Reads the settings resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "PATCH",
    "path": "/api/client/settings/profile",
    "summary": "Partially updates the settings resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/sps-raw/access",
    "summary": "Reads the sps raw resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/client/sps-raw/feed",
    "summary": "Reads the sps raw resource.",
    "access": "Client",
    "source": "clientRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/development/demo-accounts",
    "summary": "Reads the demo accounts resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/health",
    "summary": "Reads the resource resource.",
    "access": "Public",
    "source": "systemRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/health/lou",
    "summary": "Reads the lou resource.",
    "access": "Public",
    "source": "systemRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/invitations/accept",
    "summary": "Creates or triggers an action for the accept resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/invitations/validate",
    "summary": "Reads the validate resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/property-auth/login",
    "summary": "Creates or triggers an action for the login resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/bonus-codes/preview",
    "summary": "Reads the bonus codes resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/bootstrap",
    "summary": "Reads the bootstrap resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/campaigns/:slug",
    "summary": "Reads the campaigns resource.",
    "access": "Public",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/public/campaigns/:slug/submit",
    "summary": "Creates or triggers an action for the campaigns resource.",
    "access": "Public",
    "source": "landingCampaignRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/categories",
    "summary": "Reads the categories resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/changelog",
    "summary": "Reads the changelog resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/changelog/featured",
    "summary": "Reads the changelog resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/coming-soon-config",
    "summary": "Reads the coming soon config resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/public/contact",
    "summary": "Creates or triggers an action for the contact resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/cookie-catalog",
    "summary": "Reads the cookie catalog resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/public/exit-coupons/claim",
    "summary": "Creates or triggers an action for the exit coupons resource.",
    "access": "Public",
    "source": "exitCouponRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/exit-coupons/config",
    "summary": "Reads the exit coupons resource.",
    "access": "Public",
    "source": "exitCouponRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/extra-services",
    "summary": "Reads the extra services resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/faq-categories",
    "summary": "Reads the faq categories resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/faqs",
    "summary": "Reads the faqs resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/fee-rules",
    "summary": "Reads the fee rules resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/google-review/:token",
    "summary": "Reads the google review resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/info-bar",
    "summary": "Reads the info bar resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/invoices/:id",
    "summary": "Reads the invoices resource.",
    "access": "Public",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/public/invoices/:id/notify-intent",
    "summary": "Creates or triggers an action for the invoices resource.",
    "access": "Public",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/public/invoices/:id/stripe-checkout",
    "summary": "Creates or triggers an action for the invoices resource.",
    "access": "Public",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/public/invoices/:id/stripe-confirm",
    "summary": "Creates or triggers an action for the invoices resource.",
    "access": "Public",
    "source": "invoiceRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/legal-documents",
    "summary": "Reads the legal documents resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/open-source",
    "summary": "Reads the open source resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/open-source/:repository",
    "summary": "Reads the open source resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/portfolio",
    "summary": "Reads the portfolio resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/portfolio/:slug",
    "summary": "Reads the portfolio resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/portfolio/:slug/media/:index/watermarked",
    "summary": "Reads the portfolio resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/pricing",
    "summary": "Reads the pricing resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/properties",
    "summary": "Reads the properties resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/properties/:id",
    "summary": "Reads the properties resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/push/public-key",
    "summary": "Reads the push resource.",
    "access": "Public",
    "source": "publicPushRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/public/push/subscribe",
    "summary": "Creates or triggers an action for the push resource.",
    "access": "Public",
    "source": "publicPushRouter.ts"
  },
  {
    "method": "POST",
    "path": "/api/public/push/unsubscribe",
    "summary": "Creates or triggers an action for the push resource.",
    "access": "Public",
    "source": "publicPushRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/referrals/program-status",
    "summary": "Reads the referrals resource.",
    "access": "Public",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/referrals/validate-code/:code",
    "summary": "Reads the referrals resource.",
    "access": "Public",
    "source": "referralRouter.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/seo-home",
    "summary": "Reads the seo home resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/services",
    "summary": "Reads the services resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/settings",
    "summary": "Reads the settings resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/social-links",
    "summary": "Reads the social links resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/social-links/tree",
    "summary": "Reads the social links resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/testimonials",
    "summary": "Reads the testimonials resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/translations",
    "summary": "Reads the translations resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/translations/:locale",
    "summary": "Reads the translations resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/travel-distance",
    "summary": "Reads the travel distance resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/public/whatsapp-config",
    "summary": "Reads the whatsapp config resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "POST",
    "path": "/api/setup",
    "summary": "Creates or triggers an action for the resource resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/setup/status",
    "summary": "Reads the status resource.",
    "access": "Public",
    "source": "api.ts"
  },
  {
    "method": "GET",
    "path": "/api/status-summary",
    "summary": "Reads the resource resource.",
    "access": "Public",
    "source": "systemRouter.ts"
  }
] as const;
