type PortalDictionary = Record<string, string>;

const en: PortalDictionary = {
  "client.nav.invoices": "Invoices & Statements", "client.nav.rewards": "VIP Rewards",
  "client.invoices.loading": "Loading your invoices…", "client.invoices.title": "Invoices & Statements",
  "client.invoices.subtitle": "View your media production invoices, download PDF receipts, and settle outstanding balances.",
  "client.invoices.empty_title": "No invoices yet", "client.invoices.empty_desc": "You currently have no billing statements or payment requests. When invoices are generated for your properties, they will appear here.",
  "client.invoices.number": "Invoice #", "client.invoices.property": "Property location", "client.invoices.dates": "Issue / due date",
  "client.invoices.status": "Status", "client.invoices.total": "Total", "client.invoices.amount_due": "Amount due", "client.invoices.action": "Action",
  "client.invoices.media_production": "Media production", "client.invoices.due": "Due: {date}", "client.invoices.paid": "Paid", "client.invoices.view_pay": "View & pay",
  "client.gallery.original_unlocked": "Original files unlocked", "client.gallery.protected": "Protected gallery downloads",
  "client.gallery.unlocked_desc": "Downloads contain the original files without a watermark.",
  "client.gallery.locked_desc": "Enter the PIN from your gallery-ready email. Without it, images are downloaded with the SPS Studio watermark and videos remain locked.",
  "client.gallery.pin_placeholder": "4-digit PIN", "client.gallery.pin_label": "Gallery download PIN", "client.gallery.unlock": "Unlock",
  "client.gallery.email_new_pin": "Email me a new PIN", "client.gallery.select_all": "Select all", "client.gallery.clear": "Clear",
  "client.gallery.download_selected": "Download selected ({count})", "client.gallery.download_zip": "Download gallery ZIP",
  "client.gallery.optimized_title": "Optimized photos – under 10 MB", "client.gallery.optimized_desc": "Web, listing and email-ready versions in a separate ZIP archive. The same PIN and watermark protection apply.",
  "client.gallery.optimized_available": "{count} optimized photos available", "client.gallery.optimized_available_one": "1 optimized photo available",
  "client.gallery.optimized_selected": "Selected optimized ({count})", "client.gallery.optimized_zip": "Download optimized ZIP",
  "client.gallery.download_item": "Download this item", "client.gallery.view_large": "View large", "client.gallery.close_large": "Close large image",
  "client.gallery.previous": "Previous image", "client.gallery.next": "Next image", "client.gallery.preparing": "Preparing ZIP archive…",
  "client.gallery.download_started": "ZIP download started.", "client.gallery.sending_pin": "Sending a new PIN…",
  "client.gallery.pin_sent": "A new PIN was sent to your email address.", "client.gallery.unlock_success": "Original downloads unlocked for every gallery in this project.",
  "client.gallery.pin_verify_failed": "The PIN could not be verified.", "client.gallery.download_failed": "Download failed.", "client.gallery.pin_email_failed": "The PIN email could not be sent."
};

const hu: PortalDictionary = {
  "client.nav.invoices": "Számlák és kimutatások", "client.nav.rewards": "VIP jutalmak",
  "client.invoices.loading": "Számlák betöltése…", "client.invoices.title": "Számlák és kimutatások",
  "client.invoices.subtitle": "Tekintse meg a médiagyártási számláit, töltse le a PDF bizonylatokat, és rendezze a fennálló egyenlegeket.",
  "client.invoices.empty_title": "Még nincsenek számlák", "client.invoices.empty_desc": "Jelenleg nincs számlája vagy fizetési kérelme. Az ingatlanjaihoz kiállított számlák itt jelennek majd meg.",
  "client.invoices.number": "Számlaszám", "client.invoices.property": "Ingatlan helyszíne", "client.invoices.dates": "Kiállítás / határidő",
  "client.invoices.status": "Állapot", "client.invoices.total": "Végösszeg", "client.invoices.amount_due": "Fizetendő", "client.invoices.action": "Művelet",
  "client.invoices.media_production": "Médiagyártás", "client.invoices.due": "Határidő: {date}", "client.invoices.paid": "Fizetve", "client.invoices.view_pay": "Megtekintés és fizetés",
  "client.gallery.original_unlocked": "Eredeti fájlok feloldva", "client.gallery.protected": "Védett galérialetöltések",
  "client.gallery.unlocked_desc": "A letöltések az eredeti, vízjelmentes fájlokat tartalmazzák.",
  "client.gallery.locked_desc": "Adja meg a kész galéria emailben kapott PIN-t. Enélkül a képek SPS Studio-vízjellel tölthetők le, a videók pedig zárolva maradnak.",
  "client.gallery.pin_placeholder": "4 jegyű PIN", "client.gallery.pin_label": "Galérialetöltési PIN", "client.gallery.unlock": "Feloldás",
  "client.gallery.email_new_pin": "Új PIN kérése emailben", "client.gallery.select_all": "Összes kijelölése", "client.gallery.clear": "Kijelölés törlése",
  "client.gallery.download_selected": "Kijelöltek letöltése ({count})", "client.gallery.download_zip": "Galéria ZIP letöltése",
  "client.gallery.optimized_title": "Optimalizált képek – 10 MB alatt", "client.gallery.optimized_desc": "Webre, hirdetéshez és emailhez kész változatok külön ZIP-ben. Ugyanaz a PIN- és vízjelvédelem vonatkozik rájuk.",
  "client.gallery.optimized_available": "{count} optimalizált kép érhető el", "client.gallery.optimized_available_one": "1 optimalizált kép érhető el",
  "client.gallery.optimized_selected": "Kijelölt optimalizált ({count})", "client.gallery.optimized_zip": "Optimalizált ZIP letöltése",
  "client.gallery.download_item": "Elem letöltése", "client.gallery.view_large": "Nagy méretű megtekintés", "client.gallery.close_large": "Nagy kép bezárása",
  "client.gallery.previous": "Előző kép", "client.gallery.next": "Következő kép", "client.gallery.preparing": "ZIP archívum előkészítése…",
  "client.gallery.download_started": "A ZIP letöltése elindult.", "client.gallery.sending_pin": "Új PIN küldése…",
  "client.gallery.pin_sent": "Az új PIN-t elküldtük az email-címére.", "client.gallery.unlock_success": "A projekt összes galériájának eredeti letöltése feloldva.",
  "client.gallery.pin_verify_failed": "A PIN ellenőrzése nem sikerült.", "client.gallery.download_failed": "A letöltés nem sikerült.", "client.gallery.pin_email_failed": "A PIN-emailt nem sikerült elküldeni."
};

const de: PortalDictionary = {
  "client.nav.invoices":"Rechnungen & Abrechnungen","client.nav.rewards":"VIP-Prämien","client.invoices.loading":"Rechnungen werden geladen…","client.invoices.title":"Rechnungen & Abrechnungen","client.invoices.subtitle":"Medienrechnungen ansehen, PDF-Belege herunterladen und offene Beträge begleichen.","client.invoices.empty_title":"Noch keine Rechnungen","client.invoices.empty_desc":"Derzeit liegen keine Rechnungen oder Zahlungsanforderungen vor. Neue Rechnungen erscheinen hier.","client.invoices.number":"Rechnungsnr.","client.invoices.property":"Objektstandort","client.invoices.dates":"Ausstellung / Fälligkeit","client.invoices.status":"Status","client.invoices.total":"Gesamt","client.invoices.amount_due":"Offener Betrag","client.invoices.action":"Aktion","client.invoices.media_production":"Medienproduktion","client.invoices.due":"Fällig: {date}","client.invoices.paid":"Bezahlt","client.invoices.view_pay":"Ansehen & bezahlen",
  "client.gallery.original_unlocked":"Originaldateien freigeschaltet","client.gallery.protected":"Geschützte Galerie-Downloads","client.gallery.unlocked_desc":"Downloads enthalten die Originaldateien ohne Wasserzeichen.","client.gallery.locked_desc":"Geben Sie die PIN aus der Galerie-E-Mail ein. Ohne PIN werden Bilder mit SPS-Studio-Wasserzeichen geladen und Videos bleiben gesperrt.","client.gallery.pin_placeholder":"4-stellige PIN","client.gallery.pin_label":"Galerie-Download-PIN","client.gallery.unlock":"Freischalten","client.gallery.email_new_pin":"Neue PIN per E-Mail","client.gallery.select_all":"Alle auswählen","client.gallery.clear":"Auswahl löschen","client.gallery.download_selected":"Auswahl herunterladen ({count})","client.gallery.download_zip":"Galerie-ZIP herunterladen","client.gallery.optimized_title":"Optimierte Fotos – unter 10 MB","client.gallery.optimized_desc":"Für Web, Inserate und E-Mail optimierte Versionen in einem separaten ZIP. Gleicher PIN- und Wasserzeichenschutz.","client.gallery.optimized_available":"{count} optimierte Fotos verfügbar","client.gallery.optimized_available_one":"1 optimiertes Foto verfügbar","client.gallery.optimized_selected":"Optimierte Auswahl ({count})","client.gallery.optimized_zip":"Optimiertes ZIP herunterladen","client.gallery.download_item":"Element herunterladen","client.gallery.view_large":"Groß anzeigen","client.gallery.close_large":"Großansicht schließen","client.gallery.previous":"Vorheriges Bild","client.gallery.next":"Nächstes Bild","client.gallery.preparing":"ZIP-Archiv wird erstellt…","client.gallery.download_started":"ZIP-Download gestartet.","client.gallery.sending_pin":"Neue PIN wird gesendet…","client.gallery.pin_sent":"Eine neue PIN wurde an Ihre E-Mail-Adresse gesendet.","client.gallery.unlock_success":"Originaldownloads für alle Galerien dieses Projekts freigeschaltet.","client.gallery.pin_verify_failed":"Die PIN konnte nicht überprüft werden.","client.gallery.download_failed":"Download fehlgeschlagen.","client.gallery.pin_email_failed":"Die PIN-E-Mail konnte nicht gesendet werden."
};

const es: PortalDictionary = {
  "client.nav.invoices":"Facturas y estados","client.nav.rewards":"Recompensas VIP","client.invoices.loading":"Cargando facturas…","client.invoices.title":"Facturas y estados","client.invoices.subtitle":"Consulta tus facturas de producción, descarga recibos PDF y paga saldos pendientes.","client.invoices.empty_title":"Aún no hay facturas","client.invoices.empty_desc":"Actualmente no tienes facturas ni solicitudes de pago. Las nuevas facturas aparecerán aquí.","client.invoices.number":"N.º de factura","client.invoices.property":"Ubicación","client.invoices.dates":"Emisión / vencimiento","client.invoices.status":"Estado","client.invoices.total":"Total","client.invoices.amount_due":"Importe pendiente","client.invoices.action":"Acción","client.invoices.media_production":"Producción multimedia","client.invoices.due":"Vence: {date}","client.invoices.paid":"Pagada","client.invoices.view_pay":"Ver y pagar",
  "client.gallery.original_unlocked":"Archivos originales desbloqueados","client.gallery.protected":"Descargas protegidas","client.gallery.unlocked_desc":"Las descargas contienen los archivos originales sin marca de agua.","client.gallery.locked_desc":"Introduce el PIN del correo de galería. Sin él, las imágenes llevan la marca de SPS Studio y los vídeos permanecen bloqueados.","client.gallery.pin_placeholder":"PIN de 4 dígitos","client.gallery.pin_label":"PIN de descarga","client.gallery.unlock":"Desbloquear","client.gallery.email_new_pin":"Enviar nuevo PIN por correo","client.gallery.select_all":"Seleccionar todo","client.gallery.clear":"Limpiar","client.gallery.download_selected":"Descargar selección ({count})","client.gallery.download_zip":"Descargar ZIP de la galería","client.gallery.optimized_title":"Fotos optimizadas – menos de 10 MB","client.gallery.optimized_desc":"Versiones listas para web, anuncios y correo en un ZIP separado. Se aplica la misma protección.","client.gallery.optimized_available":"{count} fotos optimizadas disponibles","client.gallery.optimized_available_one":"1 foto optimizada disponible","client.gallery.optimized_selected":"Optimizadas seleccionadas ({count})","client.gallery.optimized_zip":"Descargar ZIP optimizado","client.gallery.download_item":"Descargar elemento","client.gallery.view_large":"Ver en grande","client.gallery.close_large":"Cerrar imagen grande","client.gallery.previous":"Imagen anterior","client.gallery.next":"Imagen siguiente","client.gallery.preparing":"Preparando archivo ZIP…","client.gallery.download_started":"La descarga ZIP ha comenzado.","client.gallery.sending_pin":"Enviando un PIN nuevo…","client.gallery.pin_sent":"Se envió un PIN nuevo a tu correo.","client.gallery.unlock_success":"Descargas originales desbloqueadas para todas las galerías del proyecto.","client.gallery.pin_verify_failed":"No se pudo verificar el PIN.","client.gallery.download_failed":"Error de descarga.","client.gallery.pin_email_failed":"No se pudo enviar el correo con el PIN."
};

const fr: PortalDictionary = {
  "client.nav.invoices":"Factures et relevés","client.nav.rewards":"Récompenses VIP","client.invoices.loading":"Chargement des factures…","client.invoices.title":"Factures et relevés","client.invoices.subtitle":"Consultez vos factures, téléchargez les reçus PDF et réglez les soldes dus.","client.invoices.empty_title":"Aucune facture","client.invoices.empty_desc":"Vous n’avez actuellement aucune facture ni demande de paiement. Les nouvelles factures apparaîtront ici.","client.invoices.number":"N° de facture","client.invoices.property":"Lieu du bien","client.invoices.dates":"Émission / échéance","client.invoices.status":"Statut","client.invoices.total":"Total","client.invoices.amount_due":"Montant dû","client.invoices.action":"Action","client.invoices.media_production":"Production média","client.invoices.due":"Échéance : {date}","client.invoices.paid":"Payée","client.invoices.view_pay":"Voir et payer",
  "client.gallery.original_unlocked":"Fichiers originaux déverrouillés","client.gallery.protected":"Téléchargements protégés","client.gallery.unlocked_desc":"Les téléchargements contiennent les fichiers originaux sans filigrane.","client.gallery.locked_desc":"Saisissez le PIN reçu par e-mail. Sans PIN, les images portent le filigrane SPS Studio et les vidéos restent verrouillées.","client.gallery.pin_placeholder":"PIN à 4 chiffres","client.gallery.pin_label":"PIN de téléchargement","client.gallery.unlock":"Déverrouiller","client.gallery.email_new_pin":"Recevoir un nouveau PIN","client.gallery.select_all":"Tout sélectionner","client.gallery.clear":"Effacer","client.gallery.download_selected":"Télécharger la sélection ({count})","client.gallery.download_zip":"Télécharger le ZIP","client.gallery.optimized_title":"Photos optimisées – moins de 10 Mo","client.gallery.optimized_desc":"Versions adaptées au web, aux annonces et aux e-mails dans un ZIP séparé. Même protection par PIN et filigrane.","client.gallery.optimized_available":"{count} photos optimisées disponibles","client.gallery.optimized_available_one":"1 photo optimisée disponible","client.gallery.optimized_selected":"Optimisées sélectionnées ({count})","client.gallery.optimized_zip":"Télécharger le ZIP optimisé","client.gallery.download_item":"Télécharger l’élément","client.gallery.view_large":"Agrandir","client.gallery.close_large":"Fermer l’image agrandie","client.gallery.previous":"Image précédente","client.gallery.next":"Image suivante","client.gallery.preparing":"Préparation de l’archive ZIP…","client.gallery.download_started":"Le téléchargement ZIP a commencé.","client.gallery.sending_pin":"Envoi d’un nouveau PIN…","client.gallery.pin_sent":"Un nouveau PIN a été envoyé à votre adresse e-mail.","client.gallery.unlock_success":"Téléchargements originaux déverrouillés pour toutes les galeries du projet.","client.gallery.pin_verify_failed":"Le PIN n’a pas pu être vérifié.","client.gallery.download_failed":"Échec du téléchargement.","client.gallery.pin_email_failed":"L’e-mail contenant le PIN n’a pas pu être envoyé."
};

const extraEn: PortalDictionary = {
  "client.referrals.share_whatsapp":"WhatsApp","client.referrals.share_email":"Email","client.referrals.email_placeholder":"realtor.partner@agency.com","client.referrals.name_placeholder":"e.g. Sarah Jenkins","client.referrals.note_placeholder":"e.g. I use SPS Studio for my listings and highly recommend their work.","client.home.link_url_placeholder":"https://example.com/property-listing",
  "client.common.retry":"Retry","client.common.copied":"Copied",
  "client.home.properties":"Properties","client.home.listing_links":"Listing links","client.home.links_summary":"MLS, virtual tour & ad URLs","client.home.vip_title":"VIP Referral & Rewards Program","client.home.open_vip":"Open VIP dashboard","client.home.my_properties":"My properties","client.home.properties_desc":"Addresses associated with your account","client.home.add_property":"Add property","client.home.loading_properties":"Loading properties…","client.home.no_properties":"No property addresses registered yet.","client.home.add_first_property":"Add first property","client.home.copy_address":"Copy address","client.home.view_maps":"View on Google Maps","client.home.edit_property":"Edit property","client.home.delete_property":"Delete property","client.home.links_title":"Listing & ad links","client.home.links_desc":"Realtor, MLS, and promotion URLs","client.home.add_link":"Add link","client.home.loading_links":"Loading links…","client.home.no_links":"No listing links registered yet.","client.home.add_first_link":"Add first link","client.home.copy_link":"Copy link URL","client.home.open_link":"Open link in new tab","client.home.edit_link":"Edit link","client.home.delete_link":"Delete link","client.home.property_label":"Property label","client.home.property_label_placeholder":"e.g. Vacation Villa, Downtown Condo","client.home.address_placeholder":"e.g. 742 Evergreen Terrace, Springfield","client.home.save_property":"Save property","client.home.link_label":"Link label","client.home.link_label_placeholder":"e.g. Zillow Listing, 3D Matterport Tour","client.home.save_link":"Save link",
  "client.referrals.loading":"Loading VIP Referral Program…","client.referrals.load_failed":"Failed to load referral program","client.referrals.available_credits":"Available store credits","client.referrals.invited":"Invited","client.referrals.successful":"Successful","client.referrals.pending":"Pending","client.referrals.progress_to":"Progress to {tier}","client.referrals.max_status":"Maximum VIP status reached!","client.referrals.active_perks":"Your active tier perks:","client.referrals.invite_link":"Your unique invite link","client.referrals.quick_share":"Quick share via:","client.referrals.direct_invite":"Send direct email invitation","client.referrals.colleague_name":"Colleague's name (optional)","client.referrals.personal_note":"Personal note (optional)","client.referrals.sending":"Dispatching invitation…","client.referrals.send":"Send VIP invitation","client.referrals.vouchers":"My earned vouchers & discounts","client.referrals.no_vouchers":"No reward vouchers issued yet.","client.referrals.no_vouchers_desc":"Invite your first client to start unlocking studio credits and vouchers!","client.referrals.copy_voucher":"Copy voucher","client.referrals.roadmap":"VIP tier roadmap & milestones","client.referrals.status_title":"Invited friends & referral status","client.referrals.no_activity":"No referral activity recorded yet.","client.referrals.no_activity_desc":"Send your invite link to your first colleague today!","client.referrals.colleague":"Colleague / friend","client.referrals.status":"Status","client.referrals.invited_date":"Invited date","client.referrals.reward_status":"Reward status","client.referrals.pending_booking":"Pending first booking",
  "client.invoice_status.sent":"Sent","client.invoice_status.overdue":"Overdue","client.invoice_status.partially_paid":"Partially paid","client.invoice_status.paid":"Paid"
};
const extraHu: PortalDictionary = {
  "client.referrals.share_whatsapp":"WhatsApp","client.referrals.share_email":"Email","client.referrals.email_placeholder":"ingatlanos.partner@iroda.hu","client.referrals.name_placeholder":"pl. Kovács Anna","client.referrals.note_placeholder":"pl. Az SPS Studio szolgáltatásait használom a hirdetéseimhez, és jó szívvel ajánlom őket.","client.home.link_url_placeholder":"https://pelda.hu/ingatlan-hirdetes",
  "client.common.retry":"Újrapróbálás","client.common.copied":"Másolva",
  "client.home.properties":"Ingatlanok","client.home.listing_links":"Hirdetési linkek","client.home.links_summary":"MLS-, virtuális túra- és hirdetési URL-ek","client.home.vip_title":"VIP ajánlási és jutalomprogram","client.home.open_vip":"VIP irányítópult megnyitása","client.home.my_properties":"Ingatlanjaim","client.home.properties_desc":"A fiókjához társított címek","client.home.add_property":"Ingatlan hozzáadása","client.home.loading_properties":"Ingatlanok betöltése…","client.home.no_properties":"Még nincs regisztrált ingatlancím.","client.home.add_first_property":"Első ingatlan hozzáadása","client.home.copy_address":"Cím másolása","client.home.view_maps":"Megtekintés a Google Térképen","client.home.edit_property":"Ingatlan szerkesztése","client.home.delete_property":"Ingatlan törlése","client.home.links_title":"Hirdetési és promóciós linkek","client.home.links_desc":"Ingatlanos, MLS- és promóciós URL-ek","client.home.add_link":"Link hozzáadása","client.home.loading_links":"Linkek betöltése…","client.home.no_links":"Még nincs regisztrált hirdetési link.","client.home.add_first_link":"Első link hozzáadása","client.home.copy_link":"Link másolása","client.home.open_link":"Link megnyitása új lapon","client.home.edit_link":"Link szerkesztése","client.home.delete_link":"Link törlése","client.home.property_label":"Ingatlan megnevezése","client.home.property_label_placeholder":"pl. Nyaralóvilla, belvárosi lakás","client.home.address_placeholder":"pl. 1051 Budapest, Fő utca 1.","client.home.save_property":"Ingatlan mentése","client.home.link_label":"Link megnevezése","client.home.link_label_placeholder":"pl. Ingatlan.com hirdetés, 3D Matterport túra","client.home.save_link":"Link mentése",
  "client.referrals.loading":"VIP ajánlási program betöltése…","client.referrals.load_failed":"Az ajánlási program nem tölthető be","client.referrals.available_credits":"Elérhető stúdiójóváírás","client.referrals.invited":"Meghívott","client.referrals.successful":"Sikeres","client.referrals.pending":"Függőben","client.referrals.progress_to":"Haladás a(z) {tier} szinthez","client.referrals.max_status":"Elérte a legmagasabb VIP-szintet!","client.referrals.active_perks":"Aktív szintjének előnyei:","client.referrals.invite_link":"Egyedi meghívólinkje","client.referrals.quick_share":"Gyors megosztás:","client.referrals.direct_invite":"Közvetlen emailes meghívás","client.referrals.colleague_name":"Kolléga neve (opcionális)","client.referrals.personal_note":"Személyes üzenet (opcionális)","client.referrals.sending":"Meghívó küldése…","client.referrals.send":"VIP meghívó küldése","client.referrals.vouchers":"Megszerzett kuponjaim és kedvezményeim","client.referrals.no_vouchers":"Még nincs kiállított jutalomkupon.","client.referrals.no_vouchers_desc":"Hívja meg első ügyfelét, és szerezzen stúdiójóváírásokat és kuponokat!","client.referrals.copy_voucher":"Kupon másolása","client.referrals.roadmap":"VIP-szintek és mérföldkövek","client.referrals.status_title":"Meghívott ismerősök és ajánlási állapot","client.referrals.no_activity":"Még nincs ajánlási aktivitás.","client.referrals.no_activity_desc":"Küldje el meghívólinkjét első kollégájának!","client.referrals.colleague":"Kolléga / ismerős","client.referrals.status":"Állapot","client.referrals.invited_date":"Meghívás dátuma","client.referrals.reward_status":"Jutalom állapota","client.referrals.pending_booking":"Első foglalásra vár",
  "client.invoice_status.sent":"Elküldve","client.invoice_status.overdue":"Lejárt","client.invoice_status.partially_paid":"Részben fizetve","client.invoice_status.paid":"Fizetve"
};

Object.assign(en, extraEn); Object.assign(hu, extraHu);
for (const dictionary of [de, es, fr]) for (const [key, value] of Object.entries(extraEn)) if (!(key in dictionary)) dictionary[key] = value;

export const clientPortalTranslations = { en, hu, de, es, fr };
