export const comingSoonTranslations: Record<string, Record<string, string>> = {
  en: {
    "admin.coming_soon.title": "Coming soon mode", "admin.coming_soon.description": "Temporarily replace public website pages with a branded countdown screen.", "admin.coming_soon.enabled": "Mode enabled", "admin.coming_soon.disabled": "Mode disabled", "admin.coming_soon.access_note": "The homepage, portfolio galleries and public property pages will show the countdown. Admin, client, advertiser and public invoice routes remain available.", "admin.coming_soon.field_title": "Page title", "admin.coming_soon.field_description": "Description", "admin.coming_soon.target": "Countdown target", "admin.coming_soon.background": "Blurred background image or video", "admin.coming_soon.upload": "Upload media", "admin.coming_soon.blur": "Background blur", "admin.coming_soon.overlay": "Dark overlay", "admin.coming_soon.socials": "Show social media links", "admin.coming_soon.footer": "Show website footer", "admin.coming_soon.media_invalid": "Choose an image or video file.", "admin.coming_soon.media_failed": "Background upload failed.",
    "coming_soon.default_title": "Something new is coming", "coming_soon.default_description": "We are preparing a new experience. Please check back soon.", "coming_soon.eyebrow": "Coming soon", "coming_soon.days": "Days", "coming_soon.hours": "Hours", "coming_soon.minutes": "Minutes", "coming_soon.seconds": "Seconds", "coming_soon.socials": "Social media",
  },
  hu: {
    "admin.coming_soon.title": "Hamarosan mód", "admin.coming_soon.description": "A publikus weboldal ideiglenes lecserélése márkázott visszaszámláló oldalra.", "admin.coming_soon.enabled": "Mód bekapcsolva", "admin.coming_soon.disabled": "Mód kikapcsolva", "admin.coming_soon.access_note": "A főoldal, a portfóliógalériák és a publikus ingatlanoldalak a visszaszámlálót mutatják. Az admin-, ügyfél-, hirdetői és publikus számlaútvonalak továbbra is elérhetők.", "admin.coming_soon.field_title": "Oldal címe", "admin.coming_soon.field_description": "Leírás", "admin.coming_soon.target": "Visszaszámlálás céldátuma", "admin.coming_soon.background": "Elmosott háttérkép vagy videó", "admin.coming_soon.upload": "Média feltöltése", "admin.coming_soon.blur": "Háttér elmosása", "admin.coming_soon.overlay": "Sötétítő réteg", "admin.coming_soon.socials": "Közösségi média linkek megjelenítése", "admin.coming_soon.footer": "Weboldal footer megjelenítése", "admin.coming_soon.media_invalid": "Kép- vagy videófájlt válasszon.", "admin.coming_soon.media_failed": "A háttér feltöltése sikertelen.",
    "coming_soon.default_title": "Valami új érkezik", "coming_soon.default_description": "Új élménnyel készülünk. Kérjük, látogasson vissza hamarosan.", "coming_soon.eyebrow": "Hamarosan", "coming_soon.days": "Nap", "coming_soon.hours": "Óra", "coming_soon.minutes": "Perc", "coming_soon.seconds": "Másodperc", "coming_soon.socials": "Közösségi média",
  },
  de: {
    "admin.coming_soon.title": "Demnächst-Modus", "admin.coming_soon.description": "Öffentliche Webseiten vorübergehend durch einen gebrandeten Countdown ersetzen.", "admin.coming_soon.enabled": "Modus aktiviert", "admin.coming_soon.disabled": "Modus deaktiviert", "admin.coming_soon.access_note": "Startseite, Portfolios und öffentliche Immobilienseiten zeigen den Countdown. Admin-, Kunden-, Inserenten- und Rechnungsseiten bleiben erreichbar.", "admin.coming_soon.field_title": "Seitentitel", "admin.coming_soon.field_description": "Beschreibung", "admin.coming_soon.target": "Countdown-Ziel", "admin.coming_soon.background": "Unscharfes Hintergrundbild oder Video", "admin.coming_soon.upload": "Medium hochladen", "admin.coming_soon.blur": "Hintergrundunschärfe", "admin.coming_soon.overlay": "Dunkle Überlagerung", "admin.coming_soon.socials": "Social-Media-Links anzeigen", "admin.coming_soon.footer": "Website-Fußzeile anzeigen", "admin.coming_soon.media_invalid": "Wählen Sie ein Bild oder Video.", "admin.coming_soon.media_failed": "Hintergrund konnte nicht hochgeladen werden.",
    "coming_soon.default_title": "Etwas Neues kommt", "coming_soon.default_description": "Wir bereiten ein neues Erlebnis vor. Schauen Sie bald wieder vorbei.", "coming_soon.eyebrow": "Demnächst", "coming_soon.days": "Tage", "coming_soon.hours": "Stunden", "coming_soon.minutes": "Minuten", "coming_soon.seconds": "Sekunden", "coming_soon.socials": "Soziale Medien",
  },
  es: {
    "admin.coming_soon.title": "Modo próximamente", "admin.coming_soon.description": "Sustituya temporalmente las páginas públicas por una cuenta atrás con su marca.", "admin.coming_soon.enabled": "Modo activado", "admin.coming_soon.disabled": "Modo desactivado", "admin.coming_soon.access_note": "El inicio, los portafolios y las propiedades públicas mostrarán la cuenta atrás. Las rutas de administración, clientes, anunciantes y facturas seguirán disponibles.", "admin.coming_soon.field_title": "Título de la página", "admin.coming_soon.field_description": "Descripción", "admin.coming_soon.target": "Objetivo de la cuenta atrás", "admin.coming_soon.background": "Imagen o vídeo de fondo desenfocado", "admin.coming_soon.upload": "Subir contenido", "admin.coming_soon.blur": "Desenfoque del fondo", "admin.coming_soon.overlay": "Capa oscura", "admin.coming_soon.socials": "Mostrar redes sociales", "admin.coming_soon.footer": "Mostrar pie de página", "admin.coming_soon.media_invalid": "Seleccione una imagen o un vídeo.", "admin.coming_soon.media_failed": "Error al subir el fondo.",
    "coming_soon.default_title": "Algo nuevo está por llegar", "coming_soon.default_description": "Estamos preparando una nueva experiencia. Vuelva pronto.", "coming_soon.eyebrow": "Próximamente", "coming_soon.days": "Días", "coming_soon.hours": "Horas", "coming_soon.minutes": "Minutos", "coming_soon.seconds": "Segundos", "coming_soon.socials": "Redes sociales",
  },
  fr: {
    "admin.coming_soon.title": "Mode bientôt disponible", "admin.coming_soon.description": "Remplacez temporairement les pages publiques par un compte à rebours aux couleurs de la marque.", "admin.coming_soon.enabled": "Mode activé", "admin.coming_soon.disabled": "Mode désactivé", "admin.coming_soon.access_note": "L’accueil, les portfolios et les biens publics afficheront le compte à rebours. Les espaces admin, client, annonceur et les factures restent accessibles.", "admin.coming_soon.field_title": "Titre de la page", "admin.coming_soon.field_description": "Description", "admin.coming_soon.target": "Date du compte à rebours", "admin.coming_soon.background": "Image ou vidéo d’arrière-plan floutée", "admin.coming_soon.upload": "Téléverser un média", "admin.coming_soon.blur": "Flou d’arrière-plan", "admin.coming_soon.overlay": "Superposition sombre", "admin.coming_soon.socials": "Afficher les réseaux sociaux", "admin.coming_soon.footer": "Afficher le pied de page", "admin.coming_soon.media_invalid": "Sélectionnez une image ou une vidéo.", "admin.coming_soon.media_failed": "Échec du téléversement de l’arrière-plan.",
    "coming_soon.default_title": "Quelque chose de nouveau arrive", "coming_soon.default_description": "Nous préparons une nouvelle expérience. Revenez bientôt.", "coming_soon.eyebrow": "Bientôt disponible", "coming_soon.days": "Jours", "coming_soon.hours": "Heures", "coming_soon.minutes": "Minutes", "coming_soon.seconds": "Secondes", "coming_soon.socials": "Réseaux sociaux",
  },
};
