export const financialTranslations: Record<string, Record<string, string>> = {
  en: {
    "admin.financial.title_budget": "Budget & Cashflow", "admin.financial.title_billing": "Invoices & Payment Requests", "admin.financial.badge": "Financial Suite",
    "admin.financial.subtitle_budget": "Track studio revenues, operational expenses, cashflow forecasts, and per-admin financial targets.", "admin.financial.subtitle_invoices": "Generate professional client invoices, dispatch branded payment links, and track receivables.", "admin.financial.subtitle_requests": "Coworker payment requests, contractor expense claims, and Superadmin approval workflow.",
    "admin.financial.tab_budget": "Cashflow & Budget", "admin.financial.tab_invoices": "Invoices", "admin.financial.tab_requests": "Payment Requests", "admin.financial.new_transaction": "New Transaction", "admin.financial.create_invoice": "Create Invoice", "admin.financial.currency": "Currency: {currency}",
    "admin.budget.stats.total_incomes": "Total Incomes", "admin.budget.stats.total_outcomes": "Total Expenses", "admin.budget.stats.net_balance": "Net Balance", "admin.budget.stats.profit_status": "Profit Margin & Status", "admin.budget.stats.confirmed_amount": "{amount} confirmed", "admin.budget.stats.planned_amount": "{amount} planned", "admin.budget.stats.confirmed_net": "Confirmed Net:",
    "admin.budget.status.on_track": "On Track", "admin.budget.status.in_progress": "In Progress", "admin.budget.status.over_budget": "Over Budget", "admin.budget.status.planned": "Planned", "admin.budget.status.reviewed": "Reviewed", "admin.budget.status.closed": "Period Closed",
    "admin.invoices.stats.total_invoiced": "Total Invoiced", "admin.invoices.stats.counts": "{total} invoices · {drafts} drafts", "admin.invoices.stats.collected": "Collected (Paid)", "admin.invoices.stats.settled": "{count} fully settled", "admin.invoices.stats.outstanding": "Outstanding", "admin.invoices.stats.sent_viewed": "{sent} sent · {viewed} viewed", "admin.invoices.stats.overdue": "Overdue", "admin.invoices.stats.past_due": "{count} past due", "admin.invoices.stats.collection_rate": "Collection Rate",
    "admin.payment_requests.title": "Internal Payment Requests & Approval Workflow", "admin.payment_requests.subtitle_admin": "Review, approve, or deny coworker expense claims, contractor payouts, and budget requests.", "admin.payment_requests.subtitle_user": "Submit payment requests and reimbursement claims to the Superadmin for review and authorization.", "admin.payment_requests.manage_categories": "Manage Categories", "admin.payment_requests.manage_categories_title": "Manage payment request categories", "admin.payment_requests.refresh": "Refresh payment requests", "admin.payment_requests.new": "New Payment Request", "admin.payment_requests.deleted": "Payment request deleted successfully", "admin.payment_requests.delete_failed": "Failed to delete payment request", "admin.payment_requests.load_failed": "Failed to load payment requests",
    "admin.payment_requests.stats.pending": "Pending Review", "admin.payment_requests.stats.approved": "Approved Requests", "admin.payment_requests.stats.denied": "Denied Requests", "admin.payment_requests.stats.on_hold": "On Hold Requests", "admin.payment_requests.stats.total": "Total Requests", "admin.payment_requests.stats.request_one": "request", "admin.payment_requests.stats.request_many": "requests", "admin.payment_requests.stats.awaiting": "awaiting decision", "admin.payment_requests.stats.cleared": "cleared & logged", "admin.payment_requests.stats.denied_note": "denied with review notes", "admin.payment_requests.stats.on_hold_count": "{count} on hold", "admin.payment_requests.stats.all_records": "All status records"
  },
  hu: {
    "admin.financial.title_budget": "Költségvetés és pénzforgalom", "admin.financial.title_billing": "Számlák és fizetési kérelmek", "admin.financial.badge": "Pénzügyi rendszer",
    "admin.financial.subtitle_budget": "Kövesd a stúdió bevételeit, működési kiadásait, pénzforgalmi előrejelzéseit és pénzügyi céljait.", "admin.financial.subtitle_invoices": "Készíts professzionális ügyfélszámlákat, küldj fizetési hivatkozásokat és kövesd a kintlévőségeket.", "admin.financial.subtitle_requests": "Munkatársi fizetési kérelmek, költségtérítések és szuperadminisztrátori jóváhagyási folyamat.",
    "admin.financial.tab_budget": "Pénzforgalom és költségvetés", "admin.financial.tab_invoices": "Számlák", "admin.financial.tab_requests": "Fizetési kérelmek", "admin.financial.new_transaction": "Új tranzakció", "admin.financial.create_invoice": "Számla létrehozása", "admin.financial.currency": "Pénznem: {currency}",
    "admin.budget.stats.total_incomes": "Összes bevétel", "admin.budget.stats.total_outcomes": "Összes kiadás", "admin.budget.stats.net_balance": "Nettó egyenleg", "admin.budget.stats.profit_status": "Haszonkulcs és állapot", "admin.budget.stats.confirmed_amount": "{amount} megerősítve", "admin.budget.stats.planned_amount": "{amount} tervezett", "admin.budget.stats.confirmed_net": "Megerősített nettó:",
    "admin.budget.status.on_track": "Terv szerint", "admin.budget.status.in_progress": "Folyamatban", "admin.budget.status.over_budget": "Keret felett", "admin.budget.status.planned": "Tervezett", "admin.budget.status.reviewed": "Felülvizsgálva", "admin.budget.status.closed": "Lezárt időszak",
    "admin.invoices.stats.total_invoiced": "Összes számlázott", "admin.invoices.stats.counts": "{total} számla · {drafts} piszkozat", "admin.invoices.stats.collected": "Beérkezett (fizetett)", "admin.invoices.stats.settled": "{count} teljesen rendezve", "admin.invoices.stats.outstanding": "Kintlévőség", "admin.invoices.stats.sent_viewed": "{sent} elküldve · {viewed} megtekintve", "admin.invoices.stats.overdue": "Lejárt", "admin.invoices.stats.past_due": "{count} határidőn túl", "admin.invoices.stats.collection_rate": "Beszedési arány",
    "admin.payment_requests.title": "Belső fizetési kérelmek és jóváhagyási folyamat", "admin.payment_requests.subtitle_admin": "Munkatársi költségigények, vállalkozói kifizetések és költségvetési kérelmek ellenőrzése és elbírálása.", "admin.payment_requests.subtitle_user": "Fizetési és költségtérítési kérelmek beküldése szuperadminisztrátori jóváhagyásra.", "admin.payment_requests.manage_categories": "Kategóriák kezelése", "admin.payment_requests.manage_categories_title": "Fizetésikérelem-kategóriák kezelése", "admin.payment_requests.refresh": "Fizetési kérelmek frissítése", "admin.payment_requests.new": "Új fizetési kérelem", "admin.payment_requests.deleted": "A fizetési kérelem sikeresen törölve", "admin.payment_requests.delete_failed": "A fizetési kérelem törlése sikertelen", "admin.payment_requests.load_failed": "A fizetési kérelmek betöltése sikertelen",
    "admin.payment_requests.stats.pending": "Ellenőrzésre vár", "admin.payment_requests.stats.approved": "Jóváhagyott kérelmek", "admin.payment_requests.stats.denied": "Elutasított kérelmek", "admin.payment_requests.stats.on_hold": "Felfüggesztett kérelmek", "admin.payment_requests.stats.total": "Összes kérelem", "admin.payment_requests.stats.request_one": "kérelem", "admin.payment_requests.stats.request_many": "kérelem", "admin.payment_requests.stats.awaiting": "döntésre vár", "admin.payment_requests.stats.cleared": "jóváhagyva és naplózva", "admin.payment_requests.stats.denied_note": "elutasítva, indoklással", "admin.payment_requests.stats.on_hold_count": "{count} felfüggesztve", "admin.payment_requests.stats.all_records": "Minden állapot"
  },
  de: {}, es: {}, fr: {}
};

// Until dedicated translations are customized, non-English locales receive a
// complete English fallback instead of exposing raw translation keys.
for (const locale of ["de", "es", "fr"]) financialTranslations[locale] = { ...financialTranslations.en };
