export const financialTranslations: Record<string, Record<string, string>> = {
  en: {
    "admin.financial.title_budget": "Budget & Cashflow", "admin.financial.title_billing": "Invoices & Payment Requests", "admin.financial.badge": "Financial Suite",
    "admin.financial.subtitle_budget": "Track studio revenues, operational expenses, cashflow forecasts, and per-admin financial targets.", "admin.financial.subtitle_invoices": "Generate professional client invoices, dispatch branded payment links, and track receivables.", "admin.financial.subtitle_requests": "Coworker payment requests, contractor expense claims, and Superadmin approval workflow.",
    "admin.financial.tab_budget": "Cashflow & Budget", "admin.financial.tab_invoices": "Invoices", "admin.financial.tab_requests": "Payment Requests", "admin.financial.new_transaction": "New Transaction", "admin.financial.create_invoice": "Create Invoice", "admin.financial.currency": "Currency: {currency}",
    "admin.budget.stats.total_incomes": "Total Incomes", "admin.budget.stats.total_outcomes": "Total Expenses", "admin.budget.stats.net_balance": "Net Balance", "admin.budget.stats.profit_status": "Profit Margin & Status", "admin.budget.stats.confirmed_amount": "{amount} confirmed", "admin.budget.stats.planned_amount": "{amount} planned", "admin.budget.stats.confirmed_net": "Confirmed Net:",
    "admin.budget.status.on_track": "On Track", "admin.budget.status.in_progress": "In Progress", "admin.budget.status.over_budget": "Over Budget", "admin.budget.status.planned": "Planned", "admin.budget.status.reviewed": "Reviewed", "admin.budget.status.closed": "Period Closed",
    "admin.invoices.stats.total_invoiced": "Total Invoiced", "admin.invoices.stats.counts": "{total} invoices · {drafts} drafts", "admin.invoices.stats.collected": "Collected (Paid)", "admin.invoices.stats.settled": "{count} fully settled", "admin.invoices.stats.outstanding": "Outstanding", "admin.invoices.stats.sent_viewed": "{sent} sent · {viewed} viewed", "admin.invoices.stats.overdue": "Overdue", "admin.invoices.stats.past_due": "{count} past due", "admin.invoices.stats.collection_rate": "Collection Rate",
    "admin.payment_requests.title": "Internal Payment Requests & Approval Workflow", "admin.payment_requests.subtitle_admin": "Review, approve, or deny coworker expense claims, contractor payouts, and budget requests.", "admin.payment_requests.subtitle_user": "Submit payment requests and reimbursement claims to the Superadmin for review and authorization.", "admin.payment_requests.manage_categories": "Manage Categories", "admin.payment_requests.manage_categories_title": "Manage payment request categories", "admin.payment_requests.refresh": "Refresh payment requests", "admin.payment_requests.new": "New Payment Request", "admin.payment_requests.deleted": "Payment request deleted successfully", "admin.payment_requests.delete_failed": "Failed to delete payment request", "admin.payment_requests.load_failed": "Failed to load payment requests",
    "admin.payment_requests.stats.pending": "Pending Review", "admin.payment_requests.stats.approved": "Approved Requests", "admin.payment_requests.stats.denied": "Denied Requests", "admin.payment_requests.stats.on_hold": "On Hold Requests", "admin.payment_requests.stats.total": "Total Requests", "admin.payment_requests.stats.request_one": "request", "admin.payment_requests.stats.request_many": "requests", "admin.payment_requests.stats.awaiting": "awaiting decision", "admin.payment_requests.stats.cleared": "cleared & logged", "admin.payment_requests.stats.denied_note": "denied with review notes", "admin.payment_requests.stats.on_hold_count": "{count} on hold", "admin.payment_requests.stats.all_records": "All status records",
    "admin.budget.filter.search_admins": "Search descriptions, categories, or admins...", "admin.budget.filter.table": "Table", "admin.budget.filter.board": "Board", "admin.budget.filter.refresh": "Refresh budget data", "admin.budget.filter.export": "Export", "admin.budget.filter.admin": "Admin:", "admin.budget.filter.all_admins": "All Admins (Consolidated)", "admin.budget.filter.all_dates": "All Dates", "admin.budget.filter.this_month": "This Month", "admin.budget.filter.last_month": "Last Month", "admin.budget.filter.this_quarter": "This Quarter", "admin.budget.filter.this_year": "This Year", "admin.budget.filter.custom_range": "Custom Date Range", "admin.budget.filter.to": "to",
    "admin.budget.table.empty_filtered": "No financial entries match the active filters. Create a transaction to start tracking.", "admin.budget.table.add_first": "Add First Entry", "admin.budget.table.th_category_details": "Category & Details", "admin.budget.table.th_owner": "Owner (Admin)", "admin.budget.table.you": "You", "admin.budget.table.read_only": "Read-only", "admin.budget.table.read_only_help": "Superadmins have read-only access to entries owned by other admins.", "admin.budget.table.create_invoice": "Create Invoice from this Entry", "admin.budget.table.duplicate": "Duplicate Entry", "admin.budget.general": "General", "admin.budget.optional": "(optional)", "admin.budget.saving": "Saving...",
    "admin.budget.modal.invalid_date": "Please select a valid date.", "admin.budget.modal.save_failed": "Failed to save budget entry.", "admin.budget.modal.custom_category": "+ Custom Category", "admin.budget.modal.custom_category_placeholder": "Enter custom category...", "admin.budget.modal.linked_project": "Linked Project", "admin.budget.modal.description_placeholder": "e.g. Luxury property drone photoshoot and post-production...",
    "admin.budget.modal.today": "Today", "admin.budget.modal.yesterday": "Yesterday", "admin.budget.modal.first_of_month": "1st of Month", "admin.budget.modal.no_project": "-- No project linked --", "admin.budget.settings.color_help": "Your entries in studio and consolidated views use this accent color.", "admin.budget.settings.status_on_track": "On Track (Revenue beating forecasts)", "admin.budget.settings.status_in_progress": "In Progress (Standard monthly cadence)", "admin.budget.settings.status_over_budget": "Over Budget (Expenses exceeding limits)",
    "admin.budget.category.client_invoices": "Client Invoices", "admin.budget.category.real_estate_shoots": "Real Estate Shoots", "admin.budget.category.drone_aerials": "Drone Aerials", "admin.budget.category.virtual_tours": "Virtual 3D Tours", "admin.budget.category.commercial_video": "Commercial Video", "admin.budget.category.studio_retainer": "Studio Retainer", "admin.budget.category.license_fees": "License Fees", "admin.budget.category.other_income": "Other Income", "admin.budget.category.studio_rental": "Studio Rental & Space", "admin.budget.category.equipment": "Equipment & Camera Gear", "admin.budget.category.drone_maintenance": "Drone Maintenance & FAA", "admin.budget.category.software": "Software & Cloud Licenses", "admin.budget.category.contractor": "Contractor & Freelancer", "admin.budget.category.marketing": "Marketing & Lead Generation", "admin.budget.category.travel": "Travel, Fuel & Transport", "admin.budget.category.post_production": "Editing & Post-Production", "admin.budget.category.office": "Office & Supplies", "admin.budget.category.taxes": "Taxes & Legal Fees", "admin.budget.category.other_expense": "Other Expense",
    "admin.budget.settings.save_failed": "Failed to save budget preferences.", "admin.budget.settings.status_planned": "Planned (Initial projections)", "admin.budget.settings.status_reviewed": "Reviewed (Audit completed)", "admin.budget.settings.status_closed": "Closed (Period finalized and archived)", "admin.budget.settings.notes_placeholder": "e.g. Focus on premium campaigns and reinvestment goals...",
    "admin.budget.audit.refresh": "Refresh logs", "admin.budget.audit.updated_changes": "Updated budget item changes:", "admin.budget.audit.previous": "Previous", "admin.budget.audit.updated_value": "Updated", "admin.budget.audit.created_summary": "Created {type}: {amount} {currency} ({category}) on {date}, status: {status}",
    "admin.budget.kanban.planned": "Planned & Projected", "admin.budget.kanban.pending": "Pending Review", "admin.budget.kanban.confirmed": "Confirmed & Cleared", "admin.budget.kanban.rejected": "Rejected / Cancelled", "admin.budget.kanban.advance_title": "Move to next status", "admin.budget.kanban.advance": "Advance",
    "admin.budget.banner.studio_net": "Studio Net", "admin.budget.banner.active_admins": "Active Admins", "admin.budget.stats.net_margin": "net margin", "admin.budget.stats.total_entries": "Total Entries",
    "admin.budget.chart.income_categories": "Income Categories", "admin.budget.chart.no_income_categories": "No income categories logged.", "admin.budget.chart.expense_categories": "Expense Categories", "admin.budget.chart.no_expense_categories": "No expense categories logged.", "admin.budget.chart.no_status": "No status data available.", "admin.budget.chart.confirmed_entries": "Confirmed Entries", "admin.budget.chart.confirmed_help": "Locked in, billed, or paid", "admin.budget.chart.planned_entries": "Planned Entries", "admin.budget.chart.planned_help": "Scheduled work and forecasts", "admin.budget.chart.pending_entries": "Pending Review", "admin.budget.chart.pending_help": "Awaiting payment or receipt verification", "admin.budget.chart.rejected_entries": "Rejected Entries", "admin.budget.chart.rejected_help": "Cancelled work or denied expenses", "admin.budget.chart.net": "Net", "admin.budget.chart.no_admin_comparison": "No admin comparisons available.",
    "admin.financial.page_title_budget": "Budget & Cashflow", "admin.financial.page_title_invoices": "Client Invoices", "admin.financial.page_title_requests": "Payment Requests & Approvals", "admin.financial.currency_help": "Set the default currency for all financial summary cards", "admin.budget.toast.load_failed": "Failed to load budget data. Please try again.", "admin.budget.toast.updated": "Budget entry updated successfully", "admin.budget.toast.created": "Budget entry created successfully", "admin.budget.toast.deleted": "Budget entry deleted successfully", "admin.budget.toast.settings_saved": "Budget preferences saved successfully", "admin.budget.toast.no_export": "No entries to export.", "admin.budget.toast.exported": "CSV export downloaded successfully", "admin.invoices.toast.load_failed": "Failed to load invoice data.", "admin.invoices.toast.updated": "Invoice updated successfully", "admin.invoices.toast.created": "Invoice created successfully", "admin.invoices.toast.deleted": "Invoice deleted successfully"
  },
  hu: {
    "admin.financial.title_budget": "Költségvetés és pénzforgalom", "admin.financial.title_billing": "Számlák és fizetési kérelmek", "admin.financial.badge": "Pénzügyi rendszer",
    "admin.financial.subtitle_budget": "Kövesd a stúdió bevételeit, működési kiadásait, pénzforgalmi előrejelzéseit és pénzügyi céljait.", "admin.financial.subtitle_invoices": "Készíts professzionális ügyfélszámlákat, küldj fizetési hivatkozásokat és kövesd a kintlévőségeket.", "admin.financial.subtitle_requests": "Munkatársi fizetési kérelmek, költségtérítések és szuperadminisztrátori jóváhagyási folyamat.",
    "admin.financial.tab_budget": "Pénzforgalom és költségvetés", "admin.financial.tab_invoices": "Számlák", "admin.financial.tab_requests": "Fizetési kérelmek", "admin.financial.new_transaction": "Új tranzakció", "admin.financial.create_invoice": "Számla létrehozása", "admin.financial.currency": "Pénznem: {currency}",
    "admin.budget.stats.total_incomes": "Összes bevétel", "admin.budget.stats.total_outcomes": "Összes kiadás", "admin.budget.stats.net_balance": "Nettó egyenleg", "admin.budget.stats.profit_status": "Haszonkulcs és állapot", "admin.budget.stats.confirmed_amount": "{amount} megerősítve", "admin.budget.stats.planned_amount": "{amount} tervezett", "admin.budget.stats.confirmed_net": "Megerősített nettó:",
    "admin.budget.status.on_track": "Terv szerint", "admin.budget.status.in_progress": "Folyamatban", "admin.budget.status.over_budget": "Keret felett", "admin.budget.status.planned": "Tervezett", "admin.budget.status.reviewed": "Felülvizsgálva", "admin.budget.status.closed": "Lezárt időszak",
    "admin.invoices.stats.total_invoiced": "Összes számlázott", "admin.invoices.stats.counts": "{total} számla · {drafts} piszkozat", "admin.invoices.stats.collected": "Beérkezett (fizetett)", "admin.invoices.stats.settled": "{count} teljesen rendezve", "admin.invoices.stats.outstanding": "Kintlévőség", "admin.invoices.stats.sent_viewed": "{sent} elküldve · {viewed} megtekintve", "admin.invoices.stats.overdue": "Lejárt", "admin.invoices.stats.past_due": "{count} határidőn túl", "admin.invoices.stats.collection_rate": "Beszedési arány",
    "admin.payment_requests.title": "Belső fizetési kérelmek és jóváhagyási folyamat", "admin.payment_requests.subtitle_admin": "Munkatársi költségigények, vállalkozói kifizetések és költségvetési kérelmek ellenőrzése és elbírálása.", "admin.payment_requests.subtitle_user": "Fizetési és költségtérítési kérelmek beküldése szuperadminisztrátori jóváhagyásra.", "admin.payment_requests.manage_categories": "Kategóriák kezelése", "admin.payment_requests.manage_categories_title": "Fizetésikérelem-kategóriák kezelése", "admin.payment_requests.refresh": "Fizetési kérelmek frissítése", "admin.payment_requests.new": "Új fizetési kérelem", "admin.payment_requests.deleted": "A fizetési kérelem sikeresen törölve", "admin.payment_requests.delete_failed": "A fizetési kérelem törlése sikertelen", "admin.payment_requests.load_failed": "A fizetési kérelmek betöltése sikertelen",
    "admin.payment_requests.stats.pending": "Ellenőrzésre vár", "admin.payment_requests.stats.approved": "Jóváhagyott kérelmek", "admin.payment_requests.stats.denied": "Elutasított kérelmek", "admin.payment_requests.stats.on_hold": "Felfüggesztett kérelmek", "admin.payment_requests.stats.total": "Összes kérelem", "admin.payment_requests.stats.request_one": "kérelem", "admin.payment_requests.stats.request_many": "kérelem", "admin.payment_requests.stats.awaiting": "döntésre vár", "admin.payment_requests.stats.cleared": "jóváhagyva és naplózva", "admin.payment_requests.stats.denied_note": "elutasítva, indoklással", "admin.payment_requests.stats.on_hold_count": "{count} felfüggesztve", "admin.payment_requests.stats.all_records": "Minden állapot",
    "admin.budget.filter.search_admins": "Keresés leírás, kategória vagy admin alapján...", "admin.budget.filter.table": "Táblázat", "admin.budget.filter.board": "Tábla", "admin.budget.filter.refresh": "Költségvetési adatok frissítése", "admin.budget.filter.export": "Exportálás", "admin.budget.filter.admin": "Admin:", "admin.budget.filter.all_admins": "Minden admin (összesítve)", "admin.budget.filter.all_dates": "Minden időszak", "admin.budget.filter.this_month": "Aktuális hónap", "admin.budget.filter.last_month": "Előző hónap", "admin.budget.filter.this_quarter": "Aktuális negyedév", "admin.budget.filter.this_year": "Aktuális év", "admin.budget.filter.custom_range": "Egyéni időszak", "admin.budget.filter.to": "–",
    "admin.budget.table.empty_filtered": "Az aktív szűrőknek egyetlen pénzügyi tétel sem felel meg. A követéshez hozz létre egy új tranzakciót.", "admin.budget.table.add_first": "Első tétel hozzáadása", "admin.budget.table.th_category_details": "Kategória és részletek", "admin.budget.table.th_owner": "Tulajdonos (admin)", "admin.budget.table.you": "Te", "admin.budget.table.read_only": "Csak olvasható", "admin.budget.table.read_only_help": "A szuperadminisztrátor más adminok tételeit csak olvashatja.", "admin.budget.table.create_invoice": "Számla létrehozása ebből a tételből", "admin.budget.table.duplicate": "Tétel másolása", "admin.budget.general": "Általános", "admin.budget.optional": "(nem kötelező)", "admin.budget.saving": "Mentés...",
    "admin.budget.modal.invalid_date": "Válassz érvényes dátumot.", "admin.budget.modal.save_failed": "A költségvetési tétel mentése sikertelen.", "admin.budget.modal.custom_category": "+ Egyéni kategória", "admin.budget.modal.custom_category_placeholder": "Egyéni kategória megadása...", "admin.budget.modal.linked_project": "Kapcsolt projekt", "admin.budget.modal.description_placeholder": "pl. prémium ingatlan drónfotózása és utómunkája...",
    "admin.budget.modal.today": "Ma", "admin.budget.modal.yesterday": "Tegnap", "admin.budget.modal.first_of_month": "Hónap első napja", "admin.budget.modal.no_project": "-- Nincs kapcsolt projekt --", "admin.budget.settings.color_help": "A stúdió- és összesített nézetekben a tételek ezt a kiemelő színt használják.", "admin.budget.settings.status_on_track": "Terv szerint (a bevétel meghaladja az előrejelzést)", "admin.budget.settings.status_in_progress": "Folyamatban (szokásos havi működés)", "admin.budget.settings.status_over_budget": "Keret felett (a kiadások meghaladják a limitet)",
    "admin.budget.category.client_invoices": "Ügyfélszámlák", "admin.budget.category.real_estate_shoots": "Ingatlanfotózások", "admin.budget.category.drone_aerials": "Drónfelvételek", "admin.budget.category.virtual_tours": "Virtuális 3D túrák", "admin.budget.category.commercial_video": "Reklámvideó", "admin.budget.category.studio_retainer": "Stúdió átalánydíj", "admin.budget.category.license_fees": "Licencdíjak", "admin.budget.category.other_income": "Egyéb bevétel", "admin.budget.category.studio_rental": "Stúdió- és helyiségbérlet", "admin.budget.category.equipment": "Felszerelés és kameratechnika", "admin.budget.category.drone_maintenance": "Drónkarbantartás és engedélyek", "admin.budget.category.software": "Szoftver- és felhőlicencek", "admin.budget.category.contractor": "Vállalkozók és szabadúszók", "admin.budget.category.marketing": "Marketing és érdeklődőszerzés", "admin.budget.category.travel": "Utazás, üzemanyag és szállítás", "admin.budget.category.post_production": "Vágás és utómunka", "admin.budget.category.office": "Iroda és kellékek", "admin.budget.category.taxes": "Adók és jogi díjak", "admin.budget.category.other_expense": "Egyéb kiadás",
    "admin.budget.settings.save_failed": "A költségvetési beállítások mentése sikertelen.", "admin.budget.settings.status_planned": "Tervezett (kezdeti előrejelzés)", "admin.budget.settings.status_reviewed": "Felülvizsgálva (ellenőrzés lezárva)", "admin.budget.settings.status_closed": "Lezárva (időszak véglegesítve és archiválva)", "admin.budget.settings.notes_placeholder": "pl. prémium kampányok és visszaforgatási célok...",
    "admin.budget.audit.refresh": "Napló frissítése", "admin.budget.audit.updated_changes": "A költségvetési tétel módosításai:", "admin.budget.audit.previous": "Korábbi", "admin.budget.audit.updated_value": "Módosított", "admin.budget.audit.created_summary": "Létrehozva: {type}, {amount} {currency} ({category}), dátum: {date}, állapot: {status}",
    "admin.budget.kanban.planned": "Tervezett és előrejelzett", "admin.budget.kanban.pending": "Ellenőrzésre vár", "admin.budget.kanban.confirmed": "Megerősített és rendezett", "admin.budget.kanban.rejected": "Elutasított / törölt", "admin.budget.kanban.advance_title": "Tovább a következő állapotba", "admin.budget.kanban.advance": "Tovább",
    "admin.budget.banner.studio_net": "Stúdió nettó", "admin.budget.banner.active_admins": "Aktív adminok", "admin.budget.stats.net_margin": "nettó haszonkulcs", "admin.budget.stats.total_entries": "Összes tétel",
    "admin.budget.chart.income_categories": "Bevételi kategóriák", "admin.budget.chart.no_income_categories": "Nincs rögzített bevételi kategória.", "admin.budget.chart.expense_categories": "Kiadási kategóriák", "admin.budget.chart.no_expense_categories": "Nincs rögzített kiadási kategória.", "admin.budget.chart.no_status": "Nincs elérhető állapotadat.", "admin.budget.chart.confirmed_entries": "Megerősített tételek", "admin.budget.chart.confirmed_help": "Rögzített, számlázott vagy kifizetett", "admin.budget.chart.planned_entries": "Tervezett tételek", "admin.budget.chart.planned_help": "Ütemezett munkák és előrejelzések", "admin.budget.chart.pending_entries": "Ellenőrzésre vár", "admin.budget.chart.pending_help": "Fizetésre vagy bizonylat-ellenőrzésre vár", "admin.budget.chart.rejected_entries": "Elutasított tételek", "admin.budget.chart.rejected_help": "Törölt munkák vagy elutasított kiadások", "admin.budget.chart.net": "Nettó", "admin.budget.chart.no_admin_comparison": "Nincs összehasonlítható adminadat.",
    "admin.financial.page_title_budget": "Költségvetés és pénzforgalom", "admin.financial.page_title_invoices": "Ügyfélszámlák", "admin.financial.page_title_requests": "Fizetési kérelmek és jóváhagyások", "admin.financial.currency_help": "A pénzügyi összesítő kártyák alapértelmezett pénznemének beállítása", "admin.budget.toast.load_failed": "A költségvetési adatok betöltése sikertelen. Próbáld újra.", "admin.budget.toast.updated": "A költségvetési tétel sikeresen frissült", "admin.budget.toast.created": "A költségvetési tétel sikeresen létrejött", "admin.budget.toast.deleted": "A költségvetési tétel sikeresen törölve", "admin.budget.toast.settings_saved": "A költségvetési beállítások sikeresen mentve", "admin.budget.toast.no_export": "Nincs exportálható tétel.", "admin.budget.toast.exported": "A CSV-export sikeresen letöltve", "admin.invoices.toast.load_failed": "A számlaadatok betöltése sikertelen.", "admin.invoices.toast.updated": "A számla sikeresen frissült", "admin.invoices.toast.created": "A számla sikeresen létrejött", "admin.invoices.toast.deleted": "A számla sikeresen törölve"
  },
  de: {}, es: {}, fr: {}
};

// Until dedicated translations are customized, non-English locales receive a
// complete English fallback instead of exposing raw translation keys.
for (const locale of ["de", "es", "fr"]) financialTranslations[locale] = { ...financialTranslations.en };
