type InvoiceCopy = Record<string, string>;

const en: InvoiceCopy = {
  loading: "Loading invoice…", invoice: "Invoice", paidFull: "Paid in full", due: "Due: {date}", paidThanks: "Thank you! This invoice has been settled in full.", amountDue: "Amount due: {amount}", amountDueLabel: "Amount due", print: "Print / Save PDF", payOnline: "Pay online", paymentSent: "I have sent payment", issued: "Issue date", dueDate: "Due date", invoiceNumber: "Invoice number", paymentStatus: "Payment status", billedTo: "Billed to", serviceLocation: "Service / property location", serviceDescription: "Premium real estate photography & visual media", serviceFallback: "Real estate photography and digital content production", description: "Description", quantity: "Qty", unitPrice: "Unit price", amount: "Amount", paymentTerms: "Payment terms", paymentInstructions: "Bank transfer / payment instructions", notes: "Notes", subtotal: "Subtotal", tax: "Tax", discount: "Discount", total: "Total", amountPaid: "Amount paid", balanceDue: "Balance due", receipts: "Confirmed payments", date: "Date", method: "Method", reference: "Reference", footer: "Thank you for choosing SPS Studio for your property's visual presentation.", billingContact: "For billing questions, contact us at", notifyTitle: "Notify payment", notifyText: "If you paid by bank transfer or another method, share the details below so our finance team can verify the payment.", notifySent: "Your payment notification has been sent!", transactionReference: "Bank reference / transaction ID", transactionPlaceholder: "e.g. transfer confirmation or transaction ID", additionalNotes: "Additional notes", notesPlaceholder: "e.g. the transfer was sent from an account ending in 4102…", cancel: "Cancel", sendConfirmation: "Send confirmation", sending: "Sending…", property: "Property", fullySettled: "PAID IN FULL"
};

const hu: InvoiceCopy = {
  loading: "Számla betöltése…", invoice: "Számla", paidFull: "Teljesen rendezve", due: "Fizetési határidő: {date}", paidThanks: "Köszönjük! A számla teljes összege rendezve lett.", amountDue: "Fizetendő összeg: {amount}", amountDueLabel: "Fizetendő összeg", print: "Nyomtatás / PDF mentése", payOnline: "Online fizetés", paymentSent: "Fizetést indítottam", issued: "Kiállítás dátuma", dueDate: "Fizetési határidő", invoiceNumber: "Számlaszám", paymentStatus: "Fizetési állapot", billedTo: "Számlázási adatok", serviceLocation: "Szolgáltatás / ingatlan helyszíne", serviceDescription: "Prémium ingatlanfotó és vizuális tartalom", serviceFallback: "Ingatlanfotó és digitális tartalomkészítés", description: "Megnevezés", quantity: "Mennyiség", unitPrice: "Egységár", amount: "Összeg", paymentTerms: "Fizetési feltételek", paymentInstructions: "Banki átutalási / fizetési információk", notes: "Megjegyzés", subtotal: "Nettó összeg", tax: "ÁFA", discount: "Kedvezmény", total: "Végösszeg", amountPaid: "Befizetett összeg", balanceDue: "Fennmaradó összeg", receipts: "Visszaigazolt fizetések", date: "Dátum", method: "Fizetési mód", reference: "Hivatkozás", footer: "Köszönjük, hogy az SPS Studio szolgáltatásait választotta ingatlanja vizuális megjelenítéséhez.", billingContact: "Számlázással kapcsolatos kérdés esetén írjon nekünk:", notifyTitle: "Fizetés bejelentése", notifyText: "Ha átutalással vagy más banki fizetési móddal rendezte a számlát, adja meg az alábbi adatokat, hogy a pénzügy ellenőrizhesse és jóváírhassa a befizetést.", notifySent: "A fizetési értesítést elküldtük!", transactionReference: "Banki közlemény / tranzakcióazonosító", transactionPlaceholder: "pl. átutalási bizonylat száma vagy tranzakcióazonosító", additionalNotes: "További megjegyzés", notesPlaceholder: "pl. az utalás a 4102 végű számláról indult…", cancel: "Mégse", sendConfirmation: "Visszaigazolás küldése", sending: "Küldés…", property: "Ingatlan", fullySettled: "TELJESEN RENDEZVE"
};

const de: InvoiceCopy = { ...en, loading: "Rechnung wird geladen…", invoice: "Rechnung", paidFull: "Vollständig bezahlt", due: "Fällig am: {date}", paidThanks: "Vielen Dank! Diese Rechnung wurde vollständig beglichen.", amountDue: "Fälliger Betrag: {amount}", print: "Drucken / PDF speichern", payOnline: "Online bezahlen", paymentSent: "Zahlung veranlasst", issued: "Rechnungsdatum", dueDate: "Fälligkeitsdatum", invoiceNumber: "Rechnungsnummer", paymentStatus: "Zahlungsstatus", billedTo: "Rechnungsempfänger", serviceLocation: "Leistung / Objektadresse", serviceFallback: "Immobilienfotografie und digitale Medienproduktion", description: "Bezeichnung", quantity: "Menge", unitPrice: "Einzelpreis", amount: "Betrag", paymentTerms: "Zahlungsbedingungen", paymentInstructions: "Überweisungs- / Zahlungsinformationen", notes: "Hinweis", subtotal: "Zwischensumme", tax: "Steuer", discount: "Rabatt", total: "Gesamtsumme", amountPaid: "Gezahlter Betrag", balanceDue: "Offener Betrag", receipts: "Bestätigte Zahlungen", date: "Datum", method: "Zahlungsart", reference: "Referenz", notifyTitle: "Zahlung melden", notifyText: "Wenn Sie per Überweisung oder auf anderem Weg bezahlt haben, teilen Sie uns die Angaben zur Prüfung mit.", notifySent: "Ihre Zahlungsmitteilung wurde gesendet!", transactionReference: "Bankreferenz / Transaktions-ID", additionalNotes: "Zusätzliche Hinweise", cancel: "Abbrechen", sendConfirmation: "Bestätigung senden", sending: "Wird gesendet…", property: "Objekt", fullySettled: "VOLLSTÄNDIG BEZAHLT" };
const es: InvoiceCopy = { ...en, loading: "Cargando factura…", invoice: "Factura", paidFull: "Pagada por completo", due: "Vence: {date}", paidThanks: "¡Gracias! Esta factura se ha pagado por completo.", amountDue: "Importe pendiente: {amount}", print: "Imprimir / Guardar PDF", payOnline: "Pagar en línea", paymentSent: "He enviado el pago", issued: "Fecha de emisión", dueDate: "Fecha de vencimiento", invoiceNumber: "Número de factura", paymentStatus: "Estado de pago", billedTo: "Facturado a", serviceLocation: "Servicio / ubicación de la propiedad", serviceFallback: "Fotografía inmobiliaria y producción de contenido digital", description: "Descripción", quantity: "Cant.", unitPrice: "Precio unitario", amount: "Importe", paymentTerms: "Condiciones de pago", paymentInstructions: "Instrucciones de transferencia / pago", notes: "Notas", subtotal: "Subtotal", tax: "Impuesto", discount: "Descuento", total: "Total", amountPaid: "Importe pagado", balanceDue: "Saldo pendiente", receipts: "Pagos confirmados", date: "Fecha", method: "Método", reference: "Referencia", notifyTitle: "Notificar pago", notifyText: "Si ha pagado mediante transferencia bancaria u otro método, comparta los datos para que nuestro equipo pueda verificarlo.", notifySent: "¡Se ha enviado su aviso de pago!", transactionReference: "Referencia bancaria / ID de transacción", additionalNotes: "Notas adicionales", cancel: "Cancelar", sendConfirmation: "Enviar confirmación", sending: "Enviando…", property: "Propiedad", fullySettled: "PAGADA POR COMPLETO" };
const fr: InvoiceCopy = { ...en, loading: "Chargement de la facture…", invoice: "Facture", paidFull: "Entièrement réglée", due: "Échéance : {date}", paidThanks: "Merci ! Cette facture a été entièrement réglée.", amountDue: "Montant dû : {amount}", print: "Imprimer / Enregistrer en PDF", payOnline: "Payer en ligne", paymentSent: "J'ai envoyé le paiement", issued: "Date d'émission", dueDate: "Date d'échéance", invoiceNumber: "Numéro de facture", paymentStatus: "Statut du paiement", billedTo: "Facturé à", serviceLocation: "Service / adresse du bien", serviceFallback: "Photographie immobilière et production de contenu numérique", description: "Description", quantity: "Qté", unitPrice: "Prix unitaire", amount: "Montant", paymentTerms: "Conditions de paiement", paymentInstructions: "Instructions de virement / paiement", notes: "Remarques", subtotal: "Sous-total", tax: "Taxe", discount: "Remise", total: "Total", amountPaid: "Montant payé", balanceDue: "Solde dû", receipts: "Paiements confirmés", date: "Date", method: "Méthode", reference: "Référence", notifyTitle: "Signaler un paiement", notifyText: "Si vous avez payé par virement ou par un autre moyen, transmettez les informations afin que notre équipe puisse vérifier le paiement.", notifySent: "Votre notification de paiement a été envoyée !", transactionReference: "Référence bancaire / identifiant de transaction", additionalNotes: "Remarques supplémentaires", cancel: "Annuler", sendConfirmation: "Envoyer la confirmation", sending: "Envoi…", property: "Bien", fullySettled: "ENTIÈREMENT RÉGLÉ" };

Object.assign(de, { amountDueLabel: "Fälliger Betrag", serviceDescription: "Premium-Immobilienfotografie und visuelle Medien", footer: "Vielen Dank, dass Sie SPS Studio für die visuelle Präsentation Ihrer Immobilie gewählt haben.", billingContact: "Bei Fragen zur Rechnung kontaktieren Sie uns unter", transactionPlaceholder: "z. B. Überweisungsbestätigung oder Transaktions-ID", notesPlaceholder: "z. B. die Überweisung erfolgte von einem Konto mit der Endung 4102…" });
Object.assign(es, { amountDueLabel: "Importe pendiente", serviceDescription: "Fotografía inmobiliaria y medios visuales premium", footer: "Gracias por elegir SPS Studio para la presentación visual de su propiedad.", billingContact: "Para consultas de facturación, contáctenos en", transactionPlaceholder: "p. ej., confirmación de transferencia o ID de transacción", notesPlaceholder: "p. ej., la transferencia se envió desde una cuenta terminada en 4102…" });
Object.assign(fr, { amountDueLabel: "Montant dû", serviceDescription: "Photographie immobilière et médias visuels haut de gamme", footer: "Merci d'avoir choisi SPS Studio pour la présentation visuelle de votre bien.", billingContact: "Pour toute question de facturation, contactez-nous à", transactionPlaceholder: "ex. confirmation de virement ou identifiant de transaction", notesPlaceholder: "ex. le virement a été effectué depuis un compte se terminant par 4102…" });

const dictionaries: Record<string, InvoiceCopy> = { en, hu, de, es, fr };

export function getInvoiceCopy(language: string, key: string, replacements: Record<string, string | number> = {}) {
  let value = (dictionaries[language] || en)[key] || en[key] || key;
  for (const [token, replacement] of Object.entries(replacements)) value = value.replaceAll(`{${token}}`, String(replacement));
  return value;
}

export const invoiceLocale: Record<string, string> = { en: "en-US", hu: "hu-HU", de: "de-DE", es: "es-ES", fr: "fr-FR" };
