type Dictionary = Record<string, string>;

const en: Dictionary = {
  "Language": "Language", "client.nav.help": "Help",
  "admin.workspace.open_messages": "Open messages", "admin.workspace.messages": "Messages", "admin.workspace.messages_subtitle": "Client and internal conversations", "admin.workspace.clients": "Clients", "admin.workspace.staff": "Staff", "admin.workspace.client_conversation": "Client conversation", "admin.workspace.staff_conversation": "Internal conversation", "admin.workspace.back_to_conversations": "Back to conversations", "admin.workspace.close_chat": "Close chat", "admin.workspace.close_messages": "Close messages", "admin.workspace.minimize_chat": "Minimize chat", "admin.workspace.write_message": "Write a message…", "admin.workspace.send_message": "Send message", "admin.workspace.client_typing": "The client is typing…", "admin.workspace.staff_typing": "A colleague is typing…", "admin.workspace.sent": "Sent", "admin.workspace.delivered": "Delivered", "admin.workspace.read": "Read", "admin.workspace.client_conversations": "Client conversations", "admin.workspace.staff_conversations": "Internal conversations", "admin.workspace.recent_staff_chat": "Recent internal chats", "admin.workspace.new_staff_chat": "New internal conversation", "admin.workspace.new_conversation": "New conversation", "admin.workspace.loading": "Loading…", "admin.workspace.no_client_chats": "There are no client conversations yet.", "admin.workspace.no_staff_chats": "Start an internal conversation with a colleague.", "admin.workspace.analytics": "Analytics", "admin.workspace.analytics_description": "Detailed traffic data is available on a separate page.", "admin.workspace.open_analytics": "Open analytics", "admin.workspace.open_panel": "Open workspace", "admin.workspace.close_panel": "Close workspace",
  "client.help.title": "Client portal help", "client.help.description": "We help you find projects, galleries, downloads and important account features step by step.", "client.help.messages": "Messages", "client.help.new": "New", "client.help.no_conversations": "There are no conversations yet.", "client.help.contact_us": "Write to us", "client.help.auto_refresh": "New replies refresh automatically.", "client.help.start_message": "Start new feedback or a support request.", "client.help.subject": "Subject", "client.help.write_message": "Write your message…", "client.help.send": "Send", "client.help.admin_typing": "The administrator is typing…", "client.help.sent": "Sent", "client.help.delivered": "Delivered", "client.help.read": "Read", "client.help.send_failed": "The message could not be sent.", "client.help.loading": "Loading help…", "client.help.load_failed": "Help could not be loaded.", "client.help.coming_soon": "Help is coming soon", "client.help.coming_soon_description": "There are no published help topics for the client portal yet.", "client.help.no_more_steps": "No additional steps have been added for this topic.", "client.help.help_image": "Help image"
};

const hu: Dictionary = {
  "Language": "Nyelv", "client.nav.help": "Súgó",
  "admin.workspace.open_messages": "Üzenetek megnyitása", "admin.workspace.messages": "Üzenetek", "admin.workspace.messages_subtitle": "Ügyfél- és belső beszélgetések", "admin.workspace.clients": "Ügyfelek", "admin.workspace.staff": "Munkatársak", "admin.workspace.client_conversation": "Ügyfélbeszélgetés", "admin.workspace.staff_conversation": "Belső beszélgetés", "admin.workspace.back_to_conversations": "Vissza a beszélgetésekhez", "admin.workspace.close_chat": "Chat bezárása", "admin.workspace.close_messages": "Üzenetek bezárása", "admin.workspace.minimize_chat": "Chat tálcázása", "admin.workspace.write_message": "Üzenet írása…", "admin.workspace.send_message": "Üzenet küldése", "admin.workspace.client_typing": "Az ügyfél gépel…", "admin.workspace.staff_typing": "A munkatárs gépel…", "admin.workspace.sent": "Elküldve", "admin.workspace.delivered": "Kézbesítve", "admin.workspace.read": "Olvasva", "admin.workspace.client_conversations": "Ügyfélbeszélgetések", "admin.workspace.staff_conversations": "Belső beszélgetések", "admin.workspace.recent_staff_chat": "Legutóbbi belső chat", "admin.workspace.new_staff_chat": "Új belső beszélgetés", "admin.workspace.new_conversation": "Új beszélgetés", "admin.workspace.loading": "Betöltés…", "admin.workspace.no_client_chats": "Még nincs ügyfélbeszélgetés.", "admin.workspace.no_staff_chats": "Indíts belső beszélgetést egy munkatárssal.", "admin.workspace.analytics": "Analitika", "admin.workspace.analytics_description": "A részletes forgalmi adatok külön oldalon érhetők el.", "admin.workspace.open_analytics": "Analitika megnyitása", "admin.workspace.open_panel": "Munkaterület megnyitása", "admin.workspace.close_panel": "Munkaterület bezárása",
  "client.help.title": "Ügyfélportál súgó", "client.help.description": "Lépésről lépésre segítünk megtalálni a projekteket, galériákat, letöltéseket és a fiókodhoz tartozó fontos funkciókat.", "client.help.messages": "Üzenetek", "client.help.new": "Új", "client.help.no_conversations": "Még nincs beszélgetés.", "client.help.contact_us": "Írj nekünk", "client.help.auto_refresh": "Az új válaszok automatikusan frissülnek.", "client.help.start_message": "Indíts új visszajelzést vagy segítségkérést.", "client.help.subject": "Tárgy", "client.help.write_message": "Írd meg az üzeneted…", "client.help.send": "Küldés", "client.help.admin_typing": "Az adminisztrátor gépel…", "client.help.sent": "Elküldve", "client.help.delivered": "Kézbesítve", "client.help.read": "Olvasva", "client.help.send_failed": "Az üzenet nem küldhető el.", "client.help.loading": "Súgó betöltése…", "client.help.load_failed": "A súgó nem tölthető be.", "client.help.coming_soon": "A súgó hamarosan elérhető", "client.help.coming_soon_description": "Jelenleg még nincs közzétett súgótopik az ügyfélportálhoz.", "client.help.no_more_steps": "Nincs további lépés megadva ehhez a topikhoz.", "client.help.help_image": "Súgó kép"
};

export const workspaceChatTranslations: Record<string, Dictionary> = {
  en, hu,
  de: { ...en, "Language": "Sprache", "client.nav.help": "Hilfe" },
  es: { ...en, "Language": "Idioma", "client.nav.help": "Ayuda" },
  fr: { ...en, "Language": "Langue", "client.nav.help": "Aide" }
};
