import { FormEvent, useState } from "react";
import { AlertTriangle, CheckCircle2, Radio } from "lucide-react";
import { useApi } from "../../hooks/useApi";
import { Button } from "../ui/Button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../ui/Card";
import { Input } from "../ui/Input";
import { Label } from "../ui/Label";

export function PublicPushBroadcastCard() {
  const { fetchApi } = useApi();
  const [category, setCategory] = useState("maintenance"); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [link, setLink] = useState("/"); const [sending, setSending] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const send = async (event: FormEvent) => { event.preventDefault(); setSending(true); setMessage(""); setError(""); try { const response = await fetchApi("/api/admin/public-notifications/broadcast", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category, title, body, link }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Az értesítés nem küldhető ki."); setMessage(`${data.recipients || 0} feliratkozott eszköz értesítve.`); setTitle(""); setBody(""); } catch (err: any) { setError(err.message || "Az értesítés nem küldhető ki."); } finally { setSending(false); } };
  return <Card className="border-border overflow-hidden"><CardHeader className="border-b border-border bg-surface/60"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-amber-500/10 text-amber-600 dark:text-amber-400"><Radio className="h-5 w-5" /></div><div><CardTitle className="text-lg">Nyilvános szolgáltatási értesítések</CardTitle><CardDescription className="mt-1">Fiók nélkül feliratkozott látogatóknak küldhető karbantartási vagy incidensriasztás. Nem kapcsolódik ügyfél- vagy adminfiókhoz.</CardDescription></div></div></CardHeader><CardContent className="p-5 sm:p-6"><form onSubmit={send} className="grid gap-4 sm:grid-cols-2"><div><Label>Esemény típusa</Label><select value={category} onChange={event => setCategory(event.target.value)} className="mt-1 h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-text"><option value="maintenance">Karbantartás</option><option value="incident">Incidens</option><option value="general">Általános közlemény</option></select></div><div><Label>Céloldal</Label><Input value={link} onChange={event => setLink(event.target.value)} required pattern="/.*" maxLength={1000} className="mt-1" placeholder="/" /></div><div className="sm:col-span-2"><Label>Cím</Label><Input value={title} onChange={event => setTitle(event.target.value)} required maxLength={160} className="mt-1" placeholder="Tervezett karbantartás" /></div><div className="sm:col-span-2"><Label>Üzenet</Label><textarea value={body} onChange={event => setBody(event.target.value)} required maxLength={500} rows={3} className="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-text" placeholder="A szolgáltatás rövid ideig nem lesz elérhető." /></div>{(message || error) && <div className={`sm:col-span-2 flex items-center gap-2 rounded-xl border p-3 text-sm ${error ? "border-red-500/25 bg-red-500/10 text-red-700" : "border-emerald-500/25 bg-emerald-500/10 text-emerald-700"}`}>{error ? <AlertTriangle className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}{error || message}</div>}<div className="sm:col-span-2 flex justify-end"><Button type="submit" disabled={sending}>{sending ? "Küldés…" : "Nyilvános értesítés kiküldése"}</Button></div></form></CardContent></Card>;
}
