import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, MessageCircle } from "lucide-react";
import { useApi } from "../../hooks/useApi";
import { Button } from "../ui/Button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../ui/Card";
import { Input } from "../ui/Input";
import { Label } from "../ui/Label";

type Config = { enabled: boolean; phone: string; message: string };
export function WhatsAppSettingsCard() {
  const { fetchApi } = useApi(); const [config, setConfig] = useState<Config>({ enabled: false, phone: "", message: "" }); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetchApi("/api/admin/whatsapp-settings").then(response => response.ok ? response.json() : null).then(data => data && setConfig({ enabled: Boolean(data.enabled), phone: data.phone || "", message: data.message || "" })).catch(() => setError("A WhatsApp beállítások nem tölthetők be.")); }, [fetchApi]);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setNotice(""); setError(""); try { const response = await fetchApi("/api/admin/whatsapp-settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(config) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "A beállítások nem menthetők."); setConfig(data); setNotice(data.enabled ? "A WhatsApp chat-buborék aktív." : "A WhatsApp chat-buborék kikapcsolva."); } catch (err: any) { setError(err.message || "A beállítások nem menthetők."); } finally { setSaving(false); } };
  return <Card className="border-border overflow-hidden"><CardHeader className="border-b border-border bg-surface/60"><div className="flex items-start gap-3"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-600"><MessageCircle className="h-5 w-5" /></div><div><CardTitle className="text-lg">WhatsApp chat</CardTitle><CardDescription className="mt-1">Kapcsolható WhatsApp chat-buborék a publikus oldalakon. A szám E.164 formátumban, szóközök nélkül is megadható.</CardDescription></div></div></CardHeader><CardContent className="p-5 sm:p-6"><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 flex items-center justify-between rounded-xl border border-border bg-background p-3"><span><span className="block text-sm font-semibold text-text">Chat-buborék engedélyezése</span><span className="mt-0.5 block text-xs text-muted-text">Csak aktív és érvényes telefonszám mellett jelenik meg a publikus oldalakon.</span></span><input type="checkbox" checked={config.enabled} onChange={event => setConfig(current => ({ ...current, enabled: event.target.checked }))} className="h-5 w-5 accent-primary" /></label><div><Label>WhatsApp telefonszám</Label><Input value={config.phone} onChange={event => setConfig(current => ({ ...current, phone: event.target.value }))} required={config.enabled} maxLength={30} className="mt-1" placeholder="+36 30 123 4567" /></div><div><Label>Előre kitöltött üzenet</Label><Input value={config.message} onChange={event => setConfig(current => ({ ...current, message: event.target.value }))} maxLength={1000} className="mt-1" placeholder="Szia! Érdeklődni szeretnék…" /></div>{(notice || error) && <p className={`sm:col-span-2 flex items-center gap-2 text-sm ${error ? "text-red-600" : "text-emerald-600"}`}><CheckCircle2 className="h-4 w-4" />{error || notice}</p>}<div className="sm:col-span-2 flex justify-end"><Button type="submit" disabled={saving}>{saving ? "Mentés…" : "WhatsApp beállítások mentése"}</Button></div></form></CardContent></Card>;
}
