import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ExternalLink, Github, GitFork, LoaderCircle, Star } from "lucide-react";
import { Header } from "../components/public/Header";
import { Footer } from "../components/public/Footer";
import { SiteSettings } from "../lib/types";

type Repository = { id: number; name: string; description: string; html_url: string; homepage: string; language: string; stargazers_count: number; forks_count: number; updated_at: string; topics: string[] };
export default function OpenSourcePage() {
  const [settings, setSettings] = useState<SiteSettings>({}); const [repositories, setRepositories] = useState<Repository[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/public/settings").then(r => r.ok ? r.json() : {}), fetch("/api/public/open-source").then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error || "A repók nem tölthetők be."); return data; })]).then(([nextSettings, data]) => { setSettings(nextSettings || {}); setRepositories(data.repositories || []); }).catch((err: any) => setError(err.message || "A repók nem tölthetők be.")).finally(() => setLoading(false)); }, []);
  return <div className="min-h-screen bg-background text-text"><Header settings={settings} /><main className="mx-auto max-w-7xl px-4 pb-20 pt-36 sm:px-6"><div className="max-w-3xl"><span className="inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-primary"><Github className="h-4 w-4" />Open Source</span><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">Nyílt forrású szoftvereink</h1><p className="mt-4 text-base leading-relaxed text-muted-text sm:text-lg">Az SPS Studio által kiadott, publikus GitHub-projektek és fejlesztői eszközök.</p></div>{loading ? <div className="flex justify-center py-24"><LoaderCircle className="h-8 w-8 animate-spin text-primary" /></div> : error ? <div className="mt-10 rounded-2xl border border-amber-500/25 bg-amber-500/10 p-5 text-sm text-muted-text">{error}</div> : !repositories.length ? <div className="mt-10 rounded-2xl border border-border bg-surface p-8 text-center text-muted-text">Még nincs megjeleníthető publikus repó.</div> : <div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{repositories.map(repo => <article key={repo.id} className="flex min-h-64 flex-col rounded-3xl border border-border bg-surface p-6 shadow-sm transition hover:-translate-y-1 hover:border-primary/40"><div className="flex items-start justify-between gap-3"><Github className="h-6 w-6 text-primary" /><a href={repo.html_url} target="_blank" rel="noopener noreferrer" className="rounded-lg p-2 text-muted-text hover:bg-background hover:text-primary" aria-label={`${repo.name} megnyitása GitHubon`}><ExternalLink className="h-4 w-4" /></a></div><Link to={`/open-source/${encodeURIComponent(repo.name)}`} className="mt-5 w-fit text-xl font-bold transition-colors hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary">{repo.name}</Link><p className="mt-2 line-clamp-3 text-sm leading-relaxed text-muted-text">{repo.description || "Nyílt forrású SPS Studio projekt."}</p><div className="mt-5 flex flex-wrap gap-1.5">{repo.language && <span className="rounded-full bg-primary/10 px-2 py-1 text-[11px] font-semibold text-primary">{repo.language}</span>}{repo.topics?.slice(0, 3).map(topic => <span key={topic} className="rounded-full bg-background px-2 py-1 text-[11px] text-muted-text">{topic}</span>)}</div><div className="mt-auto flex items-center gap-4 pt-6 text-xs text-muted-text"><span className="inline-flex items-center gap-1"><Star className="h-3.5 w-3.5" />{repo.stargazers_count}</span><span className="inline-flex items-center gap-1"><GitFork className="h-3.5 w-3.5" />{repo.forks_count}</span><span>Frissítve: {new Date(repo.updated_at).toLocaleDateString("hu-HU")}</span></div></article>)}</div>}</main><Footer settings={settings} /></div>;
}
