import { FormEvent, useState } from "react";
import { ArrowLeft, Building2, Eye, EyeOff, Loader2, LockKeyhole, Mail } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { Input } from "../components/ui/Input";
import { Label } from "../components/ui/Label";
import { usePageTitle } from "../hooks/usePageTitle";

export default function PropertyListingLoginPage() {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  usePageTitle("Ingatlanos bejelentkezés");
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/property-auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "A bejelentkezés sikertelen."); localStorage.setItem("property_listing_token", body.token); localStorage.setItem("property_listing_user", JSON.stringify(body.user)); navigate("/property-listings/manager", { replace: true }); } catch (error) { setError(error instanceof Error ? error.message : "Bejelentkezési hiba."); } finally { setLoading(false); } };
  return <div className="flex min-h-screen items-center justify-center bg-background p-4"><div className="w-full max-w-md"><Link to="/" className="mb-5 inline-flex items-center text-sm font-medium text-muted-text hover:text-text"><ArrowLeft className="mr-1.5 h-4 w-4" />Vissza a weboldalra</Link><div className="overflow-hidden rounded-2xl border border-border bg-surface shadow-xl"><div className="border-b border-border bg-primary/10 p-6 text-center"><div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Building2 className="h-7 w-7" /></div><h1 className="text-2xl font-bold text-text">Ingatlanhirdetés-kezelő</h1><p className="mt-2 text-sm text-muted-text">Közvetlen belépés a migrált hirdetői fiókba</p></div><form onSubmit={submit} className="space-y-5 p-6">{error && <div className="rounded-xl border border-red-500/25 bg-red-500/10 px-4 py-3 text-sm text-red-600 dark:text-red-400">{error}</div>}<div className="space-y-1.5"><Label htmlFor="property-email">Email-cím</Label><div className="relative"><Mail className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-text" /><Input id="property-email" type="email" autoComplete="email" required value={email} onChange={event => setEmail(event.target.value)} className="pl-10" /></div></div><div className="space-y-1.5"><Label htmlFor="property-password">Jelszó</Label><div className="relative"><LockKeyhole className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-text" /><Input id="property-password" type={showPassword ? "text" : "password"} autoComplete="current-password" required value={password} onChange={event => setPassword(event.target.value)} className="px-10" /><button type="button" onClick={() => setShowPassword(value => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-text">{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div><button type="submit" disabled={loading} className="inline-flex w-full items-center justify-center rounded-xl bg-primary px-5 py-3 text-sm font-bold text-primary-foreground disabled:opacity-60">{loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Bejelentkezés</button><p className="text-center text-xs leading-5 text-muted-text">Csak az ügyfélkapuból korábban migrált hirdetői fiókkal használható. Magic-linkes fióknál előbb állíts be jelszót az ügyfélkapuban.</p></form></div></div></div>;
}
