import { FormEvent, useState } from "react";
import { ArrowRight, Building2, CheckCircle2, Eye, EyeOff, Loader2, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { Input } from "../components/ui/Input";
import { Label } from "../components/ui/Label";
import { usePageTitle } from "../hooks/usePageTitle";
import { PropertySiteShell } from "../components/property/PropertySiteShell";

export default function PropertyListingLoginPage() {
  const navigate = useNavigate(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  usePageTitle("Ingatlanos bejelentkezés");
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/property-auth/login", { method: "POST", headers: { "Content-Type": "application/json", "Accept": "application/json" }, body: JSON.stringify({ email, password }) }); const rawBody = await response.text(); let body: any = {}; try { body = rawBody ? JSON.parse(rawBody) : {}; } catch { throw new Error(response.status === 404 ? "Az ingatlanos bejelentkezési végpont nem érhető el. Kérjük, frissítse az oldalt vagy próbálja újra később." : "A szerver érvénytelen választ adott. Kérjük, próbálja újra."); } if (!response.ok) throw new Error(body.error || body.message || "A bejelentkezés sikertelen."); if (!body.token || !body.user) throw new Error("A bejelentkezési válasz hiányos. Kérjük, próbálja újra."); localStorage.setItem("property_listing_token", body.token); localStorage.setItem("property_listing_user", JSON.stringify(body.user)); navigate("/property-listings/manager", { replace: true }); } catch (error) { setError(error instanceof Error ? error.message : "Bejelentkezési hiba."); } finally { setLoading(false); } };
  return <PropertySiteShell><main className="mx-auto grid min-h-[82vh] max-w-7xl items-center gap-8 px-4 pb-20 pt-28 sm:px-6 md:pt-36 lg:grid-cols-[1.1fr_.9fr] lg:px-8">
    <section className="hidden rounded-[2rem] border border-border bg-surface/80 p-10 shadow-sm backdrop-blur lg:block"><div className="inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] text-primary"><Building2 className="h-4 w-4" />Hirdetői központ</div><h1 className="mt-6 text-5xl font-black leading-[1.05] tracking-tight">Ingatlanhirdetései egy helyen.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-muted-text">Kezelje a hirdetéseket, képeket és publikációs állapotokat a weboldal vizuális rendszeréhez igazított, biztonságos felületen.</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{[[ShieldCheck,"Elkülönített, biztonságos belépés"],[CheckCircle2,"Azonnali publikus megjelenés"]].map(([Icon,label]) => { const FeatureIcon = Icon as typeof ShieldCheck; return <div key={String(label)} className="flex items-center gap-3 rounded-2xl border border-border bg-background/70 p-4"><FeatureIcon className="h-5 w-5 text-primary" /><span className="text-sm font-bold">{String(label)}</span></div>; })}</div><Link to="/properties" className="mt-8 inline-flex items-center text-sm font-black text-primary hover:opacity-80">Publikus ingatlanok megtekintése <ArrowRight className="ml-2 h-4 w-4" /></Link></section>
    <section className="mx-auto w-full max-w-lg overflow-hidden rounded-[2rem] border border-border bg-surface/90 shadow-2xl backdrop-blur-xl"><div className="border-b border-border bg-primary/10 px-6 py-8 text-center sm:px-8"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary text-primary-foreground shadow-lg"><Building2 className="h-8 w-8" /></div><h2 className="text-3xl font-black tracking-tight text-text">Ingatlanos belépés</h2><p className="mt-2 text-sm text-muted-text">Belépés a migrált hirdetői fiókba</p></div><form onSubmit={submit} className="space-y-5 p-6 sm:p-8">{error && <div role="alert" className="rounded-xl border border-red-500/25 bg-red-500/10 px-4 py-3 text-sm font-medium text-red-600 dark:text-red-400">{error}</div>}<div className="space-y-2"><Label htmlFor="property-email">Email-cím</Label><div className="relative"><Mail className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-text" /><Input id="property-email" type="email" autoComplete="email" required value={email} onChange={event => setEmail(event.target.value)} className="h-12 rounded-xl pl-11" /></div></div><div className="space-y-2"><Label htmlFor="property-password">Jelszó</Label><div className="relative"><LockKeyhole className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-text" /><Input id="property-password" type={showPassword ? "text" : "password"} autoComplete="current-password" required value={password} onChange={event => setPassword(event.target.value)} className="h-12 rounded-xl px-11" /><button type="button" onClick={() => setShowPassword(value => !value)} aria-label={showPassword ? "Jelszó elrejtése" : "Jelszó megjelenítése"} className="absolute right-4 top-1/2 -translate-y-1/2 rounded-md text-muted-text hover:text-text">{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div><button type="submit" disabled={loading} className="inline-flex h-12 w-full items-center justify-center rounded-xl bg-primary px-5 text-sm font-black text-primary-foreground shadow-lg transition hover:opacity-90 disabled:opacity-60">{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ArrowRight className="mr-2 h-4 w-4" />}Bejelentkezés</button><p className="text-center text-xs leading-5 text-muted-text">Csak az ügyfélkapuból migrált fiókkal használható. Magic-linkes fióknál előbb állítson be jelszót az ügyfélkapuban.</p></form></section>
  </main></PropertySiteShell>;
}
