import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Eye, EyeOff, Home, Loader2, LogOut, MapPin, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent } from "../../components/ui/Card";
import { Input } from "../../components/ui/Input";
import { usePageTitle } from "../../hooks/usePageTitle";
import { PropertyListing } from "../../lib/types";
import { PropertyListingModal } from "../admin/PropertyListingsPage";
import { PropertySiteShell } from "../../components/property/PropertySiteShell";

export default function ClientPropertyListingsPage() {
  const navigate = useNavigate(); const token = localStorage.getItem("property_listing_token");
  const fetchApi = useCallback(async (input: RequestInfo | URL, init?: RequestInit) => { const headers = new Headers(init?.headers); if (token) headers.set("Authorization", `Bearer ${token}`); const response = await fetch(input, { ...init, headers }); if (response.status === 401 || response.status === 403) { localStorage.removeItem("property_listing_token"); localStorage.removeItem("property_listing_user"); navigate("/property-listings/login", { replace: true }); } return response; }, [navigate, token]);
  const [items, setItems] = useState<PropertyListing[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<PropertyListing | null | "new">(null); const [error, setError] = useState("");
  usePageTitle("Saját ingatlanhirdetések");
  useEffect(() => { fetchApi("/api/property-manager/property-listings").then(async response => { const rawBody = await response.text(); let body: any = {}; try { body = rawBody ? JSON.parse(rawBody) : {}; } catch { throw new Error("A hirdetéskezelő szervervégpontja nem érhető el."); } if (!response.ok) throw new Error(body.error || "A hirdetések nem tölthetők be."); return body; }).then(body => setItems(body || [])).catch(error => setError(error.message || "A hirdetések nem tölthetők be.")).finally(() => setLoading(false)); }, [fetchApi]);
  const filtered = useMemo(() => items.filter(item => `${item.title} ${item.location}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const remove = async (item: PropertyListing) => { if (!confirm(`Biztosan törlöd a hirdetést és a képeit?\n${item.title}`)) return; const response = await fetchApi(`/api/property-manager/property-listings/${item.id}`, { method: "DELETE" }); const body = await response.json(); if (response.ok) setItems(current => current.filter(entry => entry.id !== item.id)); else setError(body.error || "A törlés sikertelen."); };
  const logout = () => { localStorage.removeItem("property_listing_token"); localStorage.removeItem("property_listing_user"); navigate("/property-listings/login", { replace: true }); };
  if (loading) return <PropertySiteShell><div className="flex min-h-[80vh] items-center justify-center pt-24"><div className="rounded-2xl border border-border bg-surface/80 p-8 shadow-xl backdrop-blur"><Loader2 className="mx-auto h-8 w-8 animate-spin text-primary" /><p className="mt-3 text-sm font-semibold text-muted-text">Hirdetések betöltése…</p></div></div></PropertySiteShell>;
  return <PropertySiteShell><main className="mx-auto min-h-[80vh] max-w-7xl space-y-6 px-4 pb-20 pt-28 sm:px-6 md:pt-36 lg:px-8"><section className="overflow-hidden rounded-[2rem] border border-border bg-surface/85 p-6 shadow-sm backdrop-blur sm:p-8"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-primary/25 bg-primary/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.14em] text-primary"><Building2 className="h-4 w-4" />Hirdetői központ</div><h1 className="text-3xl font-black tracking-tight text-text sm:text-4xl">Saját ingatlanhirdetéseim</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-text">Kezelje a hirdetések adatait, optimalizált képeit és publikus megjelenését.</p></div><div className="flex flex-wrap gap-3"><button onClick={logout} className="inline-flex items-center justify-center rounded-xl border border-border bg-background px-4 py-2.5 text-sm font-bold text-text hover:border-primary"><LogOut className="mr-2 h-4 w-4" />Kijelentkezés</button><button onClick={() => setEditing("new")} className="inline-flex items-center justify-center rounded-xl bg-primary px-4 py-2.5 text-sm font-black text-primary-foreground shadow-lg hover:opacity-90"><Plus className="mr-2 h-4 w-4" />Új hirdetés</button></div></div></section>
    {error && <div className="rounded-xl border border-red-500/25 bg-red-500/10 px-4 py-3 text-sm text-red-600">{error}</div>}
    <div className="flex flex-col gap-3 rounded-2xl border border-border bg-surface/75 p-4 backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full max-w-md"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-text" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Keresés cím vagy helyszín alapján…" className="h-11 rounded-xl pl-11" /></div><div className="text-sm font-semibold text-muted-text">{items.length} hirdetés · {items.filter(item => item.is_enabled).length} publikálva</div></div>
    {filtered.length === 0 ? <Card className="rounded-3xl border-dashed bg-surface/75 backdrop-blur"><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><div className="mb-4 rounded-2xl bg-primary/10 p-4 text-primary"><Building2 className="h-8 w-8" /></div><h2 className="text-lg font-black text-text">Még nincs saját hirdetése</h2><p className="mt-2 text-sm text-muted-text">Az első ingatlant az Új hirdetés gombbal adhatja fel.</p></CardContent></Card> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item => { const preview = item.image_urls[0]?.thumbnailUrl || item.image_urls[0]?.compressedUrl || item.image_urls[0]?.url; return <Card key={item.id} className="group overflow-hidden rounded-3xl bg-surface/85 shadow-sm backdrop-blur transition hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl"><div className="relative aspect-[16/10] overflow-hidden bg-background">{preview ? <img src={preview} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" alt={item.title} loading="lazy" decoding="async" /> : <div className="flex h-full items-center justify-center"><Home className="h-12 w-12 text-muted-text/35" /></div>}<span className={`absolute right-3 top-3 rounded-full px-3 py-1.5 text-[10px] font-black uppercase tracking-wide text-white shadow backdrop-blur ${item.is_enabled ? "bg-emerald-500/90" : "bg-slate-800/85"}`}>{item.is_enabled ? <Eye className="mr-1 inline h-3 w-3" /> : <EyeOff className="mr-1 inline h-3 w-3" />}{item.is_enabled ? "Publikálva" : "Rejtett"}</span></div><CardContent className="space-y-4 p-5"><div><h2 className="line-clamp-2 text-lg font-black tracking-tight text-text">{item.title}</h2><p className="mt-2 flex items-center gap-1.5 text-xs font-medium text-muted-text"><MapPin className="h-3.5 w-3.5 text-primary" />{item.location}</p></div><div className="text-lg font-black text-primary">{item.price_text || `${Number(item.price_huf).toLocaleString("hu-HU")} Ft`}</div><div className="flex justify-end gap-2 border-t border-border pt-4"><button onClick={() => setEditing(item)} className="inline-flex items-center rounded-xl border border-border bg-background px-3 py-2 text-xs font-bold text-text hover:border-primary"><Pencil className="mr-1.5 h-3.5 w-3.5" />Szerkesztés</button><button onClick={() => remove(item)} className="inline-flex items-center rounded-xl px-3 py-2 text-xs font-bold text-red-500 hover:bg-red-500/10"><Trash2 className="mr-1.5 h-3.5 w-3.5" />Törlés</button></div></CardContent></Card>; })}</div>}
    {editing && <PropertyListingModal apiBase="/api/property-manager/property-listings" authToken={token} fetcher={fetchApi} initial={editing === "new" ? null : editing} onClose={() => setEditing(null)} onSaved={saved => { setItems(current => current.some(item => item.id === saved.id) ? current.map(item => item.id === saved.id ? saved : item) : [saved, ...current]); setEditing(null); }} />}
  </main></PropertySiteShell>;
}
