import { Crown, LockKeyhole, Play } from "lucide-react";
import { useEffect, useState } from "react";
import { useApi } from "../../hooks/useApi";

type RawPost = { id: string; title: string; caption: string; video_url: string; poster_url?: string };
export default function ClientSpsRawPage() {
  const { fetchApi } = useApi(); const [posts, setPosts] = useState<RawPost[]>([]); const [access, setAccess] = useState<{ enabled: boolean; vip: boolean } | null>(null);
  useEffect(() => { (async () => { const permission = await fetchApi("/api/client/sps-raw/access"); const details = await permission.json(); setAccess(details); if (!details.enabled || !details.vip) return; const response = await fetchApi("/api/client/sps-raw/feed"); if (response.ok) setPosts(await response.json()); })().catch(() => setAccess({ enabled: false, vip: false })); }, [fetchApi]);
  if (!access) return <div className="flex min-h-72 items-center justify-center text-muted-text">SPS RAW betöltése…</div>;
  if (!access.enabled || !access.vip) return <div className="mx-auto flex min-h-[60vh] max-w-xl flex-col items-center justify-center rounded-3xl border border-border bg-surface p-8 text-center"><div className="rounded-2xl bg-amber-500/10 p-4 text-amber-600"><LockKeyhole className="h-8 w-8" /></div><h1 className="mt-5 text-2xl font-black text-text">SPS RAW</h1><p className="mt-3 text-sm leading-6 text-muted-text">Ez a zárt werk- és rövidvideó-folyam csak aktív VIP ügyfeleknek érhető el. A hozzáférést az SPS Studio csapata engedélyezi.</p></div>;
  return <div className="mx-auto max-w-md"><div className="mb-4 flex items-center gap-2"><div className="rounded-xl bg-amber-500/10 p-2 text-amber-600"><Crown className="h-5 w-5" /></div><div><h1 className="font-black text-text">SPS RAW</h1><p className="text-xs text-muted-text">VIP werkfolyam</p></div></div><div className="snap-y snap-mandatory space-y-5">{posts.map(post => <article key={post.id} className="snap-start overflow-hidden rounded-3xl border border-border bg-slate-950 shadow-xl"><video controls playsInline preload="metadata" poster={post.poster_url || undefined} className="aspect-[9/16] w-full bg-black object-cover"><source src={post.video_url} /></video><div className="bg-background p-4"><h2 className="font-bold text-text">{post.title}</h2>{post.caption && <p className="mt-1 text-sm text-muted-text">{post.caption}</p>}</div></article>)}{!posts.length && <div className="rounded-3xl border border-dashed border-border p-10 text-center text-muted-text"><Play className="mx-auto h-8 w-8 text-primary" /><p className="mt-3 text-sm">Hamarosan érkeznek az első SPS RAW videók.</p></div>}</div></div>;
}
