import { useCallback, useEffect, useMemo, useState } from "react";
import { Building2, Eye, EyeOff, Home, Loader2, LogOut, MapPin, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Card, CardContent } from "../../components/ui/Card";
import { Input } from "../../components/ui/Input";
import { usePageTitle } from "../../hooks/usePageTitle";
import { PropertyListing } from "../../lib/types";
import { PropertyListingModal } from "../admin/PropertyListingsPage";

export default function ClientPropertyListingsPage() {
  const navigate = useNavigate(); const token = localStorage.getItem("property_listing_token");
  const fetchApi = useCallback(async (input: RequestInfo | URL, init?: RequestInit) => { const headers = new Headers(init?.headers); if (token) headers.set("Authorization", `Bearer ${token}`); const response = await fetch(input, { ...init, headers }); if (response.status === 401 || response.status === 403) { localStorage.removeItem("property_listing_token"); localStorage.removeItem("property_listing_user"); navigate("/property-listings/login", { replace: true }); } return response; }, [navigate, token]);
  const [items, setItems] = useState<PropertyListing[]>([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<PropertyListing | null | "new">(null); const [error, setError] = useState("");
  usePageTitle("Saját ingatlanhirdetések");
  useEffect(() => { fetchApi("/api/property-manager/property-listings").then(async response => { const rawBody = await response.text(); let body: any = {}; try { body = rawBody ? JSON.parse(rawBody) : {}; } catch { throw new Error("A hirdetéskezelő szervervégpontja nem érhető el."); } if (!response.ok) throw new Error(body.error || "A hirdetések nem tölthetők be."); return body; }).then(body => setItems(body || [])).catch(error => setError(error.message || "A hirdetések nem tölthetők be.")).finally(() => setLoading(false)); }, [fetchApi]);
  const filtered = useMemo(() => items.filter(item => `${item.title} ${item.location}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const remove = async (item: PropertyListing) => { if (!confirm(`Biztosan törlöd a hirdetést és a képeit?\n${item.title}`)) return; const response = await fetchApi(`/api/property-manager/property-listings/${item.id}`, { method: "DELETE" }); const body = await response.json(); if (response.ok) setItems(current => current.filter(entry => entry.id !== item.id)); else setError(body.error || "A törlés sikertelen."); };
  const logout = () => { localStorage.removeItem("property_listing_token"); localStorage.removeItem("property_listing_user"); navigate("/property-listings/login", { replace: true }); };
  if (loading) return <div className="flex min-h-72 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;
  return <div className="min-h-screen bg-background"><header className="sticky top-0 z-20 border-b border-border bg-surface/95 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between"><div className="flex items-center gap-2 font-bold text-text"><Building2 className="h-5 w-5 text-primary" />Ingatlanhirdetés-kezelő</div><button onClick={logout} className="inline-flex items-center rounded-lg border border-border px-3 py-2 text-xs font-bold text-text"><LogOut className="mr-1.5 h-3.5 w-3.5" />Kijelentkezés</button></div></header><main className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold text-text">Saját ingatlanhirdetéseim</h1><p className="mt-1 text-sm text-muted-text">A bekapcsolt hirdetéseid megjelennek a publikus ingatlanoldalon.</p></div><button onClick={() => setEditing("new")} className="inline-flex items-center justify-center rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground"><Plus className="mr-2 h-4 w-4" />Új hirdetés</button></div>
    {error && <div className="rounded-xl border border-red-500/25 bg-red-500/10 px-4 py-3 text-sm text-red-600">{error}</div>}
    <div className="relative max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-text" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Keresés…" className="pl-10" /></div>
    {filtered.length === 0 ? <Card><CardContent className="flex min-h-56 flex-col items-center justify-center text-center"><Building2 className="mb-3 h-10 w-10 text-muted-text/50" /><h2 className="font-bold text-text">Még nincs saját hirdetésed</h2><p className="mt-1 text-sm text-muted-text">Az első ingatlanodat az Új hirdetés gombbal adhatod fel.</p></CardContent></Card> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(item => { const preview = item.image_urls[0]?.thumbnailUrl || item.image_urls[0]?.compressedUrl || item.image_urls[0]?.url; return <Card key={item.id} className="overflow-hidden"><div className="relative aspect-[16/10] bg-surface">{preview ? <img src={preview} className="h-full w-full object-cover" alt="" loading="lazy" /> : <div className="flex h-full items-center justify-center"><Home className="h-10 w-10 text-muted-text/40" /></div>}<span className={`absolute right-3 top-3 rounded-full px-2 py-1 text-[10px] font-bold text-white ${item.is_enabled ? "bg-emerald-500" : "bg-slate-700"}`}>{item.is_enabled ? <Eye className="mr-1 inline h-3 w-3" /> : <EyeOff className="mr-1 inline h-3 w-3" />}{item.is_enabled ? "Bekapcsolva" : "Kikapcsolva"}</span></div><CardContent className="space-y-3 p-4"><div><h2 className="font-bold text-text">{item.title}</h2><p className="mt-1 flex items-center gap-1 text-xs text-muted-text"><MapPin className="h-3 w-3" />{item.location}</p></div><div className="text-sm font-bold text-primary">{item.price_text || `${Number(item.price_huf).toLocaleString("hu-HU")} Ft`}</div><div className="flex justify-end gap-2 border-t border-border pt-3"><button onClick={() => setEditing(item)} className="inline-flex items-center rounded-lg border border-border px-3 py-1.5 text-xs font-bold text-text"><Pencil className="mr-1 h-3 w-3" />Szerkesztés</button><button onClick={() => remove(item)} className="inline-flex items-center rounded-lg px-3 py-1.5 text-xs font-bold text-red-500"><Trash2 className="mr-1 h-3 w-3" />Törlés</button></div></CardContent></Card>; })}</div>}
    {editing && <PropertyListingModal apiBase="/api/property-manager/property-listings" authToken={token} fetcher={fetchApi} initial={editing === "new" ? null : editing} onClose={() => setEditing(null)} onSaved={saved => { setItems(current => current.some(item => item.id === saved.id) ? current.map(item => item.id === saved.id ? saved : item) : [saved, ...current]); setEditing(null); }} />}
  </main></div>;
}
