import { useEffect, useState } from "react";
import { Send } from "lucide-react";
import { useApi } from "../../hooks/useApi";

export default function ClientFeedbackPage() {
  const { fetchApi } = useApi(); const [items, setItems] = useState<any[]>([]); const [active, setActive] = useState<any | null>(null); const [messages, setMessages] = useState<any[]>([]); const [draft, setDraft] = useState("");
  const load = async () => { const r = await fetchApi("/api/admin/client-feedback"); if (r.ok) setItems(await r.json()); };
  const open = async (item: any) => { setActive(item); const r = await fetchApi(`/api/admin/client-feedback/${item.id}/messages`); if (r.ok) setMessages(await r.json()); await load(); };
  useEffect(() => { void load(); const timer = window.setInterval(() => { void load(); if (active) void open(active); }, 12_000); return () => window.clearInterval(timer); }, [active?.id]);
  const reply = async (event: React.FormEvent) => { event.preventDefault(); if (!active || !draft.trim()) return; const r = await fetchApi(`/api/admin/client-feedback/${active.id}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: draft }) }); if (r.ok) { setDraft(""); await open(active); } };
  const status = async (value: string) => { if (!active) return; const r = await fetchApi(`/api/admin/client-feedback/${active.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: value }) }); if (r.ok) { setActive({ ...active, status: value }); await load(); } };
  return <div className="mx-auto grid max-w-7xl gap-5 p-6 lg:grid-cols-[20rem_minmax(0,1fr)]"><aside className="rounded-2xl border border-border bg-surface p-4"><h1 className="mb-4 text-xl font-bold">Ügyfél visszajelzések</h1><div className="space-y-2">{items.map(item => <button key={item.id} onClick={() => void open(item)} className={`w-full rounded-xl border p-3 text-left text-sm ${active?.id === item.id ? "border-primary bg-primary/5" : "border-border"}`}><b className="block truncate">{item.client_name}</b><span className="block truncate text-xs">{item.subject}</span><span className="text-[10px] text-muted-text">{item.status} · {item.unread_count} új</span></button>)}{!items.length && <p className="text-sm text-muted-text">Nincs aktív beszélgetés.</p>}</div></aside><main className="rounded-2xl border border-border bg-surface p-5">{active ? <><div className="mb-4 flex flex-wrap items-center justify-between gap-3 border-b border-border pb-3"><div><h2 className="font-bold">{active.subject}</h2><p className="text-xs text-muted-text">{active.client_name} · {active.client_email}</p></div><select value={active.status} onChange={event => void status(event.target.value)} className="rounded-lg border border-border bg-background px-2 py-1 text-sm"><option value="open">Nyitott</option><option value="pending">Válaszra vár</option><option value="resolved">Megoldva</option><option value="closed">Lezárva</option></select></div><div className="min-h-72 space-y-2">{messages.map(message => <div key={message.id} className={`max-w-[80%] rounded-xl px-3 py-2 text-sm ${message.sender_role === "admin" ? "ml-auto bg-primary text-primary-foreground" : "bg-background"}`}>{message.body}</div>)}</div><form onSubmit={reply} className="mt-4 flex gap-2"><textarea value={draft} onChange={event => setDraft(event.target.value)} required className="min-h-20 flex-1 rounded-xl border border-border bg-background p-3 text-sm" placeholder="Válasz az ügyfélnek…"/><button className="self-end rounded-xl bg-primary p-3 text-primary-foreground"><Send className="h-4 w-4"/></button></form></> : <p className="text-muted-text">Válassz egy beszélgetést.</p>}</main></div>;
}
