import { BarChart3, RefreshCw, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { useApi } from "../../hooks/useApi";

type Overview = any;
const label: Record<string, string> = { activeUsers: "Aktív felhasználók", sessions: "Munkamenetek", pageViews: "Oldalmegtekintések", newUsers: "Új felhasználók", engagedSessions: "Elkötelezett munkamenetek" };
export default function GoogleAnalyticsPage() {
  const { fetchApi } = useApi(); const [days, setDays] = useState(30); const [data, setData] = useState<Overview | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(""); try { const response = await fetchApi(`/api/admin/google-analytics?days=${days}`); const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); } catch (err: any) { setError(err.message || "Az analitika nem tölthető be."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [days]);
  if (loading && !data) return <div className="p-8 text-muted-text">Google Analytics betöltése…</div>;
  if (error || !data?.configured) return <div className="mx-auto max-w-3xl p-6"><section className="rounded-3xl border border-border bg-surface p-7"><BarChart3 className="h-9 w-9 text-primary" /><h1 className="mt-4 text-2xl font-black text-text">Google Analytics</h1><p className="mt-2 text-sm leading-6 text-muted-text">Az adminon belüli GA4 összesítő még nincs összekapcsolva.</p><div className="mt-5 rounded-2xl border border-border bg-background p-4 text-sm leading-6 text-muted-text"><p>Add meg a szerver környezeti változóiban a <code>GOOGLE_ANALYTICS_PROPERTY_ID</code> és <code>GOOGLE_ANALYTICS_SERVICE_ACCOUNT_JSON</code> értékét, majd add hozzá a szolgáltatásfiók e-mail-címét a GA4 tulajdon hozzáféréseihez.</p><p className="mt-2 text-rose-600">{error}</p></div></section></div>;
  return <div className="mx-auto max-w-7xl space-y-6 p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="rounded-2xl bg-primary/10 p-3 text-primary"><BarChart3 /></div><div><h1 className="text-2xl font-black text-text">Google Analytics</h1><p className="text-sm text-muted-text">GA4 tulajdon: {data.propertyId}</p></div></div><div className="flex gap-2"><select value={days} onChange={e => setDays(Number(e.target.value))} className="rounded-xl border border-border bg-surface px-3 py-2 text-sm"><option value={7}>Utolsó 7 nap</option><option value={30}>Utolsó 30 nap</option><option value={90}>Utolsó 90 nap</option></select><button onClick={() => void load()} className="rounded-xl border border-border bg-surface p-2 text-primary"><RefreshCw className="h-5 w-5" /></button></div></div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{Object.entries(data.totals || {}).map(([key, value]) => <div key={key} className="rounded-2xl border border-border bg-surface p-5"><p className="text-xs font-semibold text-muted-text">{label[key] || key}</p><p className="mt-2 text-2xl font-black text-text">{Number(value).toLocaleString("hu-HU")}</p></div>)}</section><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="flex items-center gap-2 font-bold text-text"><Users className="h-4 w-4 text-primary" />Legnézettebb oldalak</h2><div className="mt-4 space-y-2">{data.topPages.map((row: any) => <div key={row.path} className="flex justify-between rounded-xl bg-background px-3 py-2 text-sm"><span className="truncate text-text">{row.path}</span><b>{row.views.toLocaleString("hu-HU")}</b></div>)}</div></section><section className="rounded-2xl border border-border bg-surface p-5"><h2 className="font-bold text-text">Forgalmi csatornák</h2><div className="mt-4 space-y-2">{data.channels.map((row: any) => <div key={row.name} className="flex justify-between rounded-xl bg-background px-3 py-2 text-sm"><span className="text-text">{row.name}</span><b>{row.sessions.toLocaleString("hu-HU")}</b></div>)}</div></section></div></div>;
}
